// GENERATED by tools/gen_economy_table.py from data/economy.csv — do not hand-edit.
// Edit the CSV and re-run the generator; see [economy.h].
//
// This file carries Cyrillic string literals (the band and wealth-tier names), which
// is what makes /utf-8 load-bearing on MSVC rather than merely defensive.
#include "game/economy.h"

namespace giga::game {

const std::array<BankTerms, kEconomyBands> kBankTerms = {{
    // [0] E0  |floor| 0..3
    BankTerms{ 90, 250, 250, 35, 500,
               6, 9, 0, 3, {0, 0} },
    // [1] E1  |floor| 4..10
    BankTerms{ 450, 2000, 800, 70, 1600,
               5, 12, 4, 10, {0, 0} },
    // [2] E2  |floor| 11..22
    BankTerms{ 4000, 25000, 8000, 160, 8000,
               4, 18, 11, 22, {0, 0} },
    // [3] E3  |floor| 23..38
    BankTerms{ 80000, 250000, 45000, 420, 22500,
               2, 30, 23, 38, {0, 0} },
    // [4] E4  |floor| 39..127
    BankTerms{ 250000, 5000000, 250000, 1200, 50000,
               1, 45, 39, 127, {0, 0} },
}};

const std::array<const char*, kEconomyBands> kBandNames = {{
    "старт и хаб",
    "ранний маршрут",
    "средний маршрут",
    "поздний маршрут",
    "богатство эндгейма",
}};

const std::array<WealthTier, kWealthTierCount> kWealthTiers = {{
    // [0] poor
    WealthTier{ 0ll, 100ll },
    // [1] stable
    WealthTier{ 100ll, 2000ll },
    // [2] official
    WealthTier{ 2000ll, 50000ll },
    // [3] rich
    WealthTier{ 50000ll, 1000000ll },
    // [4] millionaire
    WealthTier{ 1000000ll, 5000000ll },
}};

const std::array<const char*, kWealthTierCount> kWealthTierNames = {{
    "бедняк",
    "устойчивый",
    "служебный",
    "богатый",
    "миллионер",
}};

} // namespace giga::game
