// GENERATED by tools/gen_interact_table.py from data/interactables.csv — do
// not hand-edit. Edit the CSV and re-run the generator; the `source_rules`
// ctest fails on drift.
//
// One row per INTERACTIVE — a self-sufficient mechanic module: what it says
// ([E] prompt), how close a body must stand, and (as the epic grows) what it
// gates on and which EventBus event it publishes. Attachment is a different
// system (the placement seeders + props.csv's interact column); this table is
// the interactive ITSELF, so app code keys on rows and never hardcodes a
// prompt string or a reach literal again.
#pragma once

#include <cstdint>

namespace giga::game {

// Row ordinals — GENERATED, in CSV order (append-only: PropDef.interactKind
// stores this ordinal).
enum class InteractKind : std::uint8_t {
    Terminal = 0,
    ElectricalShield = 1,
    LightBulb = 2,
    Corpse = 3,
    Loot = 4,
    Npc = 5,
    Crate = 6,
    Count
};

inline constexpr std::uint8_t kInteractCount = 7u;

struct InteractDef {
    const char* id;      // CSV slug
    const char* prompt;  // the [E] hint text
    float reachM;        // interaction reach, metres
};

inline constexpr InteractDef kInteractTable[kInteractCount] = {
    {"terminal", "TERMINAL (DOOR LOCKS)", 4.0f},
    {"electrical_shield", "SABOTAGE ELECTRICAL SHIELD", 3.5f},
    {"light_bulb", "LIGHT BULB", 2.5f},
    {"corpse", "LOOT CORPSE", 2.2f},
    {"loot", "PICK UP", 2.0f},
    {"npc", "BARTER / TRADE", 2.2f},
    {"crate", "SEARCH CRATE", 2.4f},
};

inline const InteractDef& interact_def(InteractKind k) {
    const std::uint8_t i = static_cast<std::uint8_t>(k);
    return kInteractTable[i < kInteractCount ? i : 0];
}

} // namespace giga::game
