// GENERATED by tools/gen_mob_table.py from data/mobs.csv — do not hand-edit.
// Edit the CSV and re-run the generator; see [monsters.md].
#include "game/mob_table.h"

#include <cmath>

namespace giga::game {
namespace {
constexpr std::uint8_t u8(MobKind v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint8_t u8(MobTier v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint8_t u8(MobBehaviour v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint8_t u8(ProjType v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint8_t u8(MobPackMode v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint8_t u8(FloorBit v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint16_t u16(RoomBit v) { return static_cast<std::uint16_t>(v); }
constexpr std::uint32_t f(AiFlag v) { return static_cast<std::uint32_t>(v); }
} // namespace

const std::array<MobDef, kMobKindCount> kMobTable = {{
    // [0] SBORKA
    MobDef{ f(AiFlag::FoodBait),
             8, 3, 3150, 650, 1200,
             0, 85, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::Sborka), u8(MobTier::Trash),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Crowd), 8, 16, 5 },
    // [1] TVAR
    MobDef{ f(AiFlag::FoodBait) | f(AiFlag::WallBias),
             54, 13, 1650, 1150, 1550,
             0, 62, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Living) | u16(RoomBit::Common) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::Tvar), u8(MobTier::Medium),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [2] POLZUN
    MobDef{ f(AiFlag::FoodBait),
             168, 22, 850, 2250, 1350,
             0, 43, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Bathroom) | u16(RoomBit::Production) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::Polzun), u8(MobTier::Elite),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [3] BETONNIK
    MobDef{ f(AiFlag::Rare),
             1000, 35, 800, 3000, 1200,
             0, 6, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Hq) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Betonnik), u8(MobTier::Boss),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [4] ZOMBIE
    MobDef{ 0u,
             35, 8, 1400, 1500, 1200,
             0, 34, static_cast<std::uint16_t>(u16(RoomBit::Living) | u16(RoomBit::Kitchen) | u16(RoomBit::Common) | u16(RoomBit::Office)),
             0, 0, 0,
             u8(MobKind::Zombie), u8(MobTier::Medium),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Crowd), 5, 10, 6 },
    // [5] EYE
    MobDef{ f(AiFlag::Flying) | f(AiFlag::Ranged),
             20, 14, 2200, 2500, 1200,
             8000, 31, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Office) | u16(RoomBit::Production) | u16(RoomBit::Common)),
             15000, 1500, 850,
             u8(MobKind::Eye), u8(MobTier::Light),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [6] NIGHTMARE
    MobDef{ f(AiFlag::Rare),
             260, 32, 1350, 1150, 1200,
             0, 14, static_cast<std::uint16_t>(u16(RoomBit::Common) | u16(RoomBit::Hq) | u16(RoomBit::Medical) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Nightmare), u8(MobTier::Elite),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [7] SHADOW
    MobDef{ 0u,
             50, 12, 2400, 1000, 1200,
             0, 36, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Smoking) | u16(RoomBit::Office) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Shadow), u8(MobTier::Medium),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [8] REBAR
    MobDef{ f(AiFlag::WallBias) | f(AiFlag::Rare),
             210, 24, 820, 2400, 1200,
             0, 11, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Rebar), u8(MobTier::Elite),
             u8(MobBehaviour::DebrisLurker), u8(ProjType::Bullet),
             5, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [9] MATKA
    MobDef{ f(AiFlag::Rare),
             350, 12, 400, 3500, 1200,
             0, 4, static_cast<std::uint16_t>(u16(RoomBit::Hq) | u16(RoomBit::Common) | u16(RoomBit::Production) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Matka), u8(MobTier::Boss),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [10] IDOL
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Rare) | f(AiFlag::Immobile),
             100, 30, 0, 2000, 1200,
             12000, 9, static_cast<std::uint16_t>(u16(RoomBit::Storage) | u16(RoomBit::Office) | u16(RoomBit::Smoking) | u16(RoomBit::Hq)),
             15000, 1250, 1050,
             u8(MobKind::Idol), u8(MobTier::Heavy),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [11] MANCOBUS
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Boss) | f(AiFlag::Rare),
             400, 40, 700, 3000, 1200,
             6000, 3, static_cast<std::uint16_t>(u16(RoomBit::Hq) | u16(RoomBit::Production) | u16(RoomBit::Common)),
             14000, 2200, 1050,
             u8(MobKind::Mancobus), u8(MobTier::Boss),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             6, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [12] HERALD
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Boss) | f(AiFlag::Rare),
             250, 30, 1400, 2000, 1200,
             7000, 3, static_cast<std::uint16_t>(u16(RoomBit::Common) | u16(RoomBit::Hq) | u16(RoomBit::Corridor)),
             16000, 1800, 900,
             u8(MobKind::Herald), u8(MobTier::Boss),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             5, static_cast<std::uint8_t>(u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [13] CREATOR
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Boss) | f(AiFlag::Rare),
             520, 44, 1050, 2350, 1200,
             7500, 0, static_cast<std::uint16_t>(u16(RoomBit::Common) | u16(RoomBit::Hq)),
             18000, 2400, 1250,
             u8(MobKind::Creator), u8(MobTier::Boss),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             99, static_cast<std::uint8_t>(u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [14] SPIRIT
    MobDef{ f(AiFlag::Flying) | f(AiFlag::Rare),
             40, 15, 2000, 1500, 1200,
             0, 11, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Office) | u16(RoomBit::Hq) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Spirit), u8(MobTier::Medium),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [15] ROBOT
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Rare),
             65, 18, 1800, 1800, 1200,
             9000, 14, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Hq) | u16(RoomBit::Corridor) | u16(RoomBit::Office)),
             15000, 1500, 620,
             u8(MobKind::Robot), u8(MobTier::Heavy),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [16] SHOVNIK
    MobDef{ f(AiFlag::WallBias),
             45, 11, 2100, 1100, 1200,
             0, 32, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Living) | u16(RoomBit::Office) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Shovnik), u8(MobTier::Medium),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [17] LAMPOVY
    MobDef{ 0u,
             38, 11, 1750, 1000, 1200,
             0, 28, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Office) | u16(RoomBit::Common) | u16(RoomBit::Production)),
             0, 0, 0,
             u8(MobKind::Lampovy), u8(MobTier::Medium),
             u8(MobBehaviour::LampPowered), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [18] PECHATEED
    MobDef{ 0u,
             58, 10, 1620, 1450, 1200,
             0, 26, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Common) | u16(RoomBit::Smoking) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Pechateed), u8(MobTier::Medium),
             u8(MobBehaviour::DocumentHunter), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [19] TUBE_EEL
    MobDef{ f(AiFlag::WaterStrider),
             60, 14, 1450, 1350, 1200,
             0, 43, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Bathroom)),
             0, 0, 0,
             u8(MobKind::TubeEel), u8(MobTier::Heavy),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [20] PARAGRAPH
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Rare),
             46, 15, 1050, 2350, 1200,
             6500, 15, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Hq) | u16(RoomBit::Corridor) | u16(RoomBit::Common)),
             15000, 1500, 800,
             u8(MobKind::Paragraph), u8(MobTier::Medium),
             u8(MobBehaviour::RangedClause), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [21] NELYUD
    MobDef{ f(AiFlag::Rare),
             80, 18, 1800, 1400, 1200,
             0, 12, static_cast<std::uint16_t>(u16(RoomBit::Living) | u16(RoomBit::Kitchen) | u16(RoomBit::Common) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Nelyud), u8(MobTier::Heavy),
             u8(MobBehaviour::CloseReveal), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Crowd), 5, 10, 6 },
    // [22] KRYSNOZHKA
    MobDef{ f(AiFlag::FoodBait),
             14, 3, 2450, 650, 1200,
             0, 32, static_cast<std::uint16_t>(u16(RoomBit::Kitchen) | u16(RoomBit::Storage) | u16(RoomBit::Corridor) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Krysnozhka), u8(MobTier::Light),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Crowd), 8, 16, 5 },
    // [23] KOSTOREZ
    MobDef{ f(AiFlag::Rare),
             150, 17, 1550, 2800, 1200,
             0, 4, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Kostorez), u8(MobTier::Elite),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             6, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [24] SAFEGUARD
    MobDef{ f(AiFlag::Rare),
             185, 24, 2150, 2400, 1200,
             0, 2, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Hq) | u16(RoomBit::Production) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Safeguard), u8(MobTier::Elite),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             7, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [25] BLACK_LIQUIDATOR
    MobDef{ f(AiFlag::Rare),
             92, 15, 1220, 1800, 1350,
             0, 1, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Office) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::BlackLiquidator), u8(MobTier::Heavy),
             u8(MobBehaviour::FalsePatrol), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Roamer), 2, 3, 8 },
    // [26] KHOROVAYA_MATKA
    MobDef{ f(AiFlag::Rare),
             420, 10, 280, 3800, 1200,
             0, 3, static_cast<std::uint16_t>(u16(RoomBit::Hq) | u16(RoomBit::Common) | u16(RoomBit::Production) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::KhorovayaMatka), u8(MobTier::Boss),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             5, static_cast<std::uint8_t>(u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Crowd), 8, 16, 5 },
    // [27] SLIMEVIK
    MobDef{ 0u,
             18, 2, 1050, 1800, 1200,
             0, 12, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Bathroom) | u16(RoomBit::Medical) | u16(RoomBit::Storage) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Slimevik), u8(MobTier::Light),
             u8(MobBehaviour::SlimeScavenger), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [28] SOBRANNYY
    MobDef{ f(AiFlag::Rare),
             260, 24, 1180, 3100, 1200,
             0, 3, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Sobrannyy), u8(MobTier::Elite),
             u8(MobBehaviour::MeatGrowth), u8(ProjType::Bullet),
             5, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Crowd), 5, 10, 6 },
    // [29] ZHORNAYA_TVAR
    MobDef{ f(AiFlag::FoodBait),
             62, 19, 1720, 2650, 1200,
             0, 22, static_cast<std::uint16_t>(u16(RoomBit::Kitchen) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::ZhornayaTvar), u8(MobTier::Heavy),
             u8(MobBehaviour::ScentOvercommit), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Territorial), 2, 4, 4 },
    // [30] BEZEKHIY
    MobDef{ 0u,
             58, 9, 1280, 1450, 1200,
             0, 16, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Living) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Office)),
             0, 0, 0,
             u8(MobKind::Bezekhiy), u8(MobTier::Medium),
             u8(MobBehaviour::DeadEcho), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZPlus14) | u8(FloorBit::ZPlus30)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [31] PSEUDOLIFT
    MobDef{ f(AiFlag::Rare),
             125, 24, 550, 780, 1200,
             0, 0, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Pseudolift), u8(MobTier::Elite),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [32] SLEPOGLAZ
    MobDef{ 0u,
             52, 24, 620, 3400, 1200,
             0, 10, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Slepoglaz), u8(MobTier::Medium),
             u8(MobBehaviour::LastSoundBeam), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [33] OLGOY
    MobDef{ f(AiFlag::FoodBait) | f(AiFlag::Rare),
             118, 22, 950, 2250, 1480,
             0, 8, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Bathroom)),
             0, 0, 0,
             u8(MobKind::Olgoy), u8(MobTier::Heavy),
             u8(MobBehaviour::MeatWorm), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [34] VODYANOY_KOSHMAR
    MobDef{ 0u,
             86, 10, 1340, 1200, 1200,
             0, 12, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Bathroom)),
             0, 0, 0,
             u8(MobKind::VodyanoyKoshmar), u8(MobTier::Heavy),
             u8(MobBehaviour::WaterPressureLine), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [35] LAMPOGLAZ
    MobDef{ f(AiFlag::Ranged),
             44, 10, 280, 1900, 1200,
             13000, 22, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Office) | u16(RoomBit::Common)),
             17000, 900, 950,
             u8(MobKind::Lampoglaz), u8(MobTier::Medium),
             u8(MobBehaviour::LightLock), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZPlus30)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [36] TUMANNIK
    MobDef{ 0u,
             64, 9, 1900, 720, 1200,
             0, 14, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Storage) | u16(RoomBit::Smoking)),
             0, 0, 0,
             u8(MobKind::Tumannik), u8(MobTier::Heavy),
             u8(MobBehaviour::FogOffset), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [37] CHERNOSLIZ
    MobDef{ f(AiFlag::Ranged),
             18, 18, 500, 3100, 1200,
             9000, 14, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Storage)),
             15000, 750, 550,
             u8(MobKind::Chernosliz), u8(MobTier::Light),
             u8(MobBehaviour::BlackWaterWake), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [38] RZHAVNIK
    MobDef{ 0u,
             72, 13, 1350, 1550, 1200,
             0, 8, static_cast<std::uint16_t>(u16(RoomBit::Storage) | u16(RoomBit::Production) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Rzhavnik), u8(MobTier::Heavy),
             u8(MobBehaviour::ScrapWake), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [39] BETONOED
    MobDef{ f(AiFlag::WallBias) | f(AiFlag::Rare),
             360, 28, 980, 2350, 1200,
             0, 1, static_cast<std::uint16_t>(u16(RoomBit::Storage) | u16(RoomBit::Corridor) | u16(RoomBit::Production)),
             0, 0, 0,
             u8(MobKind::Betonoed), u8(MobTier::Boss),
             u8(MobBehaviour::WeakWallBreach), u8(ProjType::Bullet),
             0, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [40] PANELNIK
    MobDef{ 0u,
             96, 16, 1080, 1450, 1160,
             0, 17, static_cast<std::uint16_t>(u16(RoomBit::Living) | u16(RoomBit::Common) | u16(RoomBit::Corridor) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::Panelnik), u8(MobTier::Heavy),
             u8(MobBehaviour::WallBrace), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [41] PAUPSINA
    MobDef{ f(AiFlag::Ranged),
             32, 0, 2250, 2650, 1200,
             9500, 12, static_cast<std::uint16_t>(u16(RoomBit::Storage) | u16(RoomBit::Production) | u16(RoomBit::Corridor) | u16(RoomBit::Common)),
             11500, 3400, 480,
             u8(MobKind::Paupsina), u8(MobTier::Medium),
             u8(MobBehaviour::WebSpitter), u8(ProjType::Web),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [42] BORSHCHEVIK
    MobDef{ f(AiFlag::Immobile),
             62, 12, 0, 1450, 1200,
             0, 12, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Borshchevik), u8(MobTier::Heavy),
             u8(MobBehaviour::RootedPlant), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [43] OBZHIVALSHCHIK
    MobDef{ 0u,
             92, 16, 1050, 1550, 1200,
             0, 7, static_cast<std::uint16_t>(u16(RoomBit::Living) | u16(RoomBit::Common) | u16(RoomBit::Kitchen) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::Obzhivalshchik), u8(MobTier::Heavy),
             u8(MobBehaviour::RoomBoundAberration), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [44] HEAD_SLUG
    MobDef{ f(AiFlag::Rare),
             58, 6, 1480, 1150, 1200,
             0, 4, static_cast<std::uint16_t>(u16(RoomBit::Medical) | u16(RoomBit::Common) | u16(RoomBit::Office) | u16(RoomBit::Corridor) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::HeadSlug), u8(MobTier::Medium),
             u8(MobBehaviour::HostParasite), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZPlus14) | u8(FloorBit::ZPlus30) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [45] PROTOKOLNIK
    MobDef{ f(AiFlag::Rare),
             112, 6, 1080, 2400, 1200,
             0, 7, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Storage) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Protokolnik), u8(MobTier::Heavy),
             u8(MobBehaviour::ProtocolPressure), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [46] DIKIY_MERTVYAK
    MobDef{ 0u,
             22, 7, 2550, 1050, 1200,
             0, 22, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Kitchen) | u16(RoomBit::Living)),
             0, 0, 0,
             u8(MobKind::DikiyMertvyak), u8(MobTier::Light),
             u8(MobBehaviour::CrowdShove), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Crowd), 5, 10, 6 },
    // [47] KONTORSHCHIK
    MobDef{ f(AiFlag::Rare),
             72, 12, 950, 1650, 1200,
             0, 10, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Kontorshchik), u8(MobTier::Heavy),
             u8(MobBehaviour::DocumentScent), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [48] TONKAYA_TEN
    MobDef{ 0u,
             28, 5, 2950, 1450, 1200,
             0, 12, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Office) | u16(RoomBit::Living) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::TonkayaTen), u8(MobTier::Medium),
             u8(MobBehaviour::BaitLine), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [49] KANTSELYARSKIY_IDOL
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Rare) | f(AiFlag::Immobile),
             72, 18, 0, 2900, 1200,
             7200, 7, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Corridor)),
             14500, 2350, 1120,
             u8(MobKind::KantselyarskiyIdol), u8(MobTier::Heavy),
             u8(MobBehaviour::OfficeField), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [50] LOZHNYY_DUKH
    MobDef{ f(AiFlag::Rare),
             34, 9, 2250, 1650, 1200,
             0, 7, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Corridor) | u16(RoomBit::Living) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::LozhnyyDukh), u8(MobTier::Medium),
             u8(MobBehaviour::FalsePhase), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [51] CHERVIE_AVATAR
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Rare),
             118, 17, 1450, 2150, 1200,
             5800, 4, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Hq) | u16(RoomBit::Production) | u16(RoomBit::Corridor)),
             15000, 1500, 700,
             u8(MobKind::ChervieAvatar), u8(MobTier::Heavy),
             u8(MobBehaviour::NetPossessor), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [52] POMOYNY_ROY
    MobDef{ f(AiFlag::FoodBait),
             38, 2, 2180, 380, 1200,
             0, 29, static_cast<std::uint16_t>(u16(RoomBit::Kitchen) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::PomoynyRoy), u8(MobTier::Medium),
             u8(MobBehaviour::GarbageSurround), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Crowd), 8, 16, 5 },
    // [53] SCULPTURE
    MobDef{ f(AiFlag::Rare),
             250, 1000, 8500, 250, 1200,
             0, 1, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Storage) | u16(RoomBit::Production)),
             0, 0, 0,
             u8(MobKind::Sculpture), u8(MobTier::Elite),
             u8(MobBehaviour::WeepingAngel), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [54] TRUBNYY_AVTOMAT
    MobDef{ f(AiFlag::Ranged) | f(AiFlag::Rare),
             150, 25, 820, 2750, 1200,
             13000, 12, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Storage)),
             18000, 2250, 1050,
             u8(MobKind::TrubnyyAvtomat), u8(MobTier::Elite),
             u8(MobBehaviour::WetLineShot), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [55] LOTOCHNIK
    MobDef{ f(AiFlag::WaterStrider),
             74, 13, 1250, 1250, 1200,
             0, 21, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Bathroom) | u16(RoomBit::Common)),
             0, 0, 0,
             u8(MobKind::Lotochnik), u8(MobTier::Heavy),
             u8(MobBehaviour::DrainArmor), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::Z0)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [56] TRESKOTNIK
    MobDef{ 0u,
             18, 15, 2750, 1650, 1200,
             0, 24, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Storage) | u16(RoomBit::Living)),
             0, 0, 0,
             u8(MobKind::Treskotnik), u8(MobTier::Light),
             u8(MobBehaviour::FractureSprint), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [57] ZAKALENNAYA_ARMATURA
    MobDef{ f(AiFlag::Rare),
             265, 31, 620, 2900, 1200,
             0, 3, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::ZakalennayaArmatura), u8(MobTier::Elite),
             u8(MobBehaviour::Plain), u8(ProjType::Bullet),
             5, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [58] GLUBINNAYA_TEN
    MobDef{ 0u,
             64, 18, 1820, 1700, 1200,
             0, 6, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Hq) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::GlubinnayaTen), u8(MobTier::Heavy),
             u8(MobBehaviour::SecondBeat), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [59] GREEN_DOG
    MobDef{ f(AiFlag::FoodBait),
             34, 9, 2550, 820, 1200,
             0, 24, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Storage) | u16(RoomBit::Living) | u16(RoomBit::Kitchen)),
             0, 0, 0,
             u8(MobKind::GreenDog), u8(MobTier::Medium),
             u8(MobBehaviour::GreenDogPack), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Crowd), 3, 6, 6 },
    // [60] SLIME_WOMAN
    MobDef{ f(AiFlag::Rare),
             118, 17, 1180, 1550, 1380,
             0, 4, static_cast<std::uint16_t>(u16(RoomBit::Bathroom) | u16(RoomBit::Production) | u16(RoomBit::Medical) | u16(RoomBit::Storage) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::SlimeWoman), u8(MobTier::Heavy),
             u8(MobBehaviour::SlimeStrider), u8(ProjType::Bullet),
             3, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::Z0)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [61] GNILUSHKA
    MobDef{ f(AiFlag::Rare),
             74, 16, 1420, 1050, 1200,
             0, 2, static_cast<std::uint16_t>(u16(RoomBit::Living) | u16(RoomBit::Common) | u16(RoomBit::Storage) | u16(RoomBit::Kitchen) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::Gnilushka), u8(MobTier::Heavy),
             u8(MobBehaviour::DefensiveNeutral), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZPlus14)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [62] MUKHOZHUK_HOST
    MobDef{ f(AiFlag::FoodBait) | f(AiFlag::Rare),
             118, 13, 1280, 1280, 1200,
             0, 2, static_cast<std::uint16_t>(u16(RoomBit::Office) | u16(RoomBit::Hq) | u16(RoomBit::Storage) | u16(RoomBit::Corridor)),
             0, 0, 0,
             u8(MobKind::MukhozhukHost), u8(MobTier::Heavy),
             u8(MobBehaviour::ParasiteLeader), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [63] FOG_SHARK
    MobDef{ 0u,
             18, 12, 2850, 780, 1200,
             0, 10, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Production) | u16(RoomBit::Common) | u16(RoomBit::Bathroom)),
             0, 0, 0,
             u8(MobKind::FogShark), u8(MobTier::Light),
             u8(MobBehaviour::FogSwimmer), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Roamer), 2, 4, 10 },
    // [64] BLOOD_PLANT
    MobDef{ f(AiFlag::Rare) | f(AiFlag::Immobile),
             96, 19, 0, 2850, 1200,
             0, 2, static_cast<std::uint16_t>(u16(RoomBit::Production) | u16(RoomBit::Storage) | u16(RoomBit::Common) | u16(RoomBit::Living)),
             0, 0, 0,
             u8(MobKind::BloodPlant), u8(MobTier::Heavy),
             u8(MobBehaviour::RootHive), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::Z0) | u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Territorial), 1, 3, 3 },
    // [65] SWARM
    MobDef{ f(AiFlag::FoodBait),
             12, 2, 2750, 240, 1050,
             0, 12, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Storage) | u16(RoomBit::Production) | u16(RoomBit::Kitchen)),
             0, 0, 0,
             u8(MobKind::Swarm), u8(MobTier::Trash),
             u8(MobBehaviour::SourceSwarm), u8(ProjType::Bullet),
             2, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZMinus36)),
             u8(MobPackMode::Crowd), 8, 16, 5 },
    // [66] SPORE_CARPET
    MobDef{ 0u,
             24, 4, 820, 1400, 1200,
             0, 7, static_cast<std::uint16_t>(u16(RoomBit::Living) | u16(RoomBit::Office) | u16(RoomBit::Storage) | u16(RoomBit::Corridor) | u16(RoomBit::Production)),
             0, 0, 0,
             u8(MobKind::SporeCarpet), u8(MobTier::Light),
             u8(MobBehaviour::LurkingFurniture), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZPlus30) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0) | u8(FloorBit::ZMinus26)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [67] LISHENNYY
    MobDef{ 0u,
             76, 11, 1720, 1050, 1200,
             0, 6, static_cast<std::uint16_t>(u16(RoomBit::Corridor) | u16(RoomBit::Common) | u16(RoomBit::Hq) | u16(RoomBit::Storage)),
             0, 0, 0,
             u8(MobKind::Lishennyy), u8(MobTier::Heavy),
             u8(MobBehaviour::LightFollower), u8(ProjType::Bullet),
             4, static_cast<std::uint8_t>(u8(FloorBit::ZMinus36) | u8(FloorBit::ZMinus50)),
             u8(MobPackMode::Loner), 1, 1, 0 },
    // [68] GNOME
    MobDef{ 0u,
             25, 8, 2800, 800, 1200,
             0, 15, static_cast<std::uint16_t>(u16(RoomBit::Storage) | u16(RoomBit::Corridor) | u16(RoomBit::Production)),
             0, 0, 0,
             u8(MobKind::Gnome), u8(MobTier::Light),
             u8(MobBehaviour::Melee), u8(ProjType::Bullet),
             1, static_cast<std::uint8_t>(u8(FloorBit::ZMinus26) | u8(FloorBit::ZPlus14) | u8(FloorBit::Z0)),
             u8(MobPackMode::Crowd), 3, 6, 6 },
}};

const std::array<const char*, kMobKindCount> kMobNames = {{
    "Сборка",
    "Тварь",
    "Ползун",
    "Бетонник",
    "Мертвяк",
    "Глаз",
    "Кошмарище",
    "Теневик",
    "Арматура",
    "Матка",
    "Идол",
    "Манкобус",
    "Вестник",
    "Творец",
    "Дух",
    "Робот",
    "Шовник",
    "Ламповый",
    "Печатеед",
    "Трубный угорь",
    "Параграф",
    "Нелюдь",
    "Крысоножка",
    "Косторез",
    "Сейфгард",
    "Черный ликвидатор",
    "Хоровая Матка",
    "Слизневик",
    "Собранный человек",
    "Жорная Тварь",
    "Безэхий",
    "Псевдолифт",
    "Слепоглаз",
    "Олгой-Хорхой",
    "Водяной кошмар",
    "Лампоглаз",
    "Туманник",
    "Чернослиз",
    "Ржавник",
    "Бетоноед",
    "Панельник",
    "Паупсина",
    "Борщевик",
    "Комнатный обживальщик",
    "Головной слизень",
    "Протокольник",
    "Дикий Мертвяк",
    "Конторщик",
    "Тонкая Тень",
    "Канцелярский Идол",
    "Ложный Дух",
    "Червие",
    "Помойный Рой",
    "Скульптура",
    "Трубный Автомат",
    "Лоточник",
    "Трескотник",
    "Закаленная Арматура",
    "Глубинная Тень",
    "Зеленая собака",
    "Жижевая женщина",
    "Гнилушка",
    "Мухожук-носитель",
    "Туманная акула",
    "Кровавое Растение",
    "Рой",
    "Ковер",
    "Лишенный",
    "Гном",
}};

// --- Per-floor budgets: the V-shape --------------------------------------
// These are the reference's shipped formulas (population_profiles.ts:285-306,
// design_floor_population.ts:2067-2071), not a reinvention.

namespace {
constexpr float kThemeMult[static_cast<std::size_t>(FloorTheme::Count)] = {
    0.80f,  // Living      — the hub, deliberately emptiest
    0.86f,  // Kvartiry
    1.00f,  // Ministry
    1.12f,  // Maintenance
    1.28f,  // Hell
    1.36f,  // Void
};
} // namespace

float mob_depth01(int floorZ) {
    int a = floorZ < 0 ? -floorZ : floorZ;
    if (a >= kFloorZSpan) return 1.0f;
    return static_cast<float>(a) / static_cast<float>(kFloorZSpan);
}

int mob_count_for_floor(int floorZ, std::uint8_t danger, FloorTheme theme) {
    const float d = mob_depth01(floorZ);
    // Head-count is driven by |floor| alone; theme and danger only trim it.
    const float base = 100.0f + (static_cast<float>(kMobBudgetCap) - 100.0f) *
                                    (1.0f - std::exp(-3.1f * std::pow(d, 2.35f)));
    float share = (base < 100.0f ? 100.0f : base) /
                  static_cast<float>(kMobBudgetCap);
    if (share > 0.96f) share = 0.96f;

    const std::uint8_t dg = danger < 1 ? 1 : (danger > 5 ? 5 : danger);
    const float dangerMult = 0.92f + static_cast<float>(dg) * 0.045f;
    const std::size_t ti = static_cast<std::size_t>(theme) <
                                   static_cast<std::size_t>(FloorTheme::Count)
                               ? static_cast<std::size_t>(theme)
                               : static_cast<std::size_t>(FloorTheme::Ministry);

    const float n = static_cast<float>(kMobBudgetCap) * share *
                    kThemeMult[ti] * dangerMult;
    const int r = static_cast<int>(n + 0.5f);
    return r < 0 ? 0 : (r > kMobBudgetCap ? kMobBudgetCap : r);
}

std::uint8_t mob_level_for_floor(int floorZ, std::uint8_t danger) {
    const std::uint8_t dg = danger < 1 ? 1 : (danger > 5 ? 5 : danger);
    const float lv = 1.0f + mob_depth01(floorZ) * 8.0f +
                     (static_cast<float>(dg) - 1.0f) * 0.55f;
    int base = static_cast<int>(lv + 0.5f);
    if (base < 1) base = 1;
    if (base > 12) base = 12;
    // A high-danger shallow floor is never weaker than its authored danger.
    return static_cast<std::uint8_t>(base < dg ? dg : base);
}

std::uint16_t mob_hp_at_level(std::uint16_t baseHp, std::uint8_t level) {
    const std::uint8_t lv = level < 1 ? 1 : (level > 12 ? 12 : level);
    const float hp = static_cast<float>(baseHp) *
                     (1.0f + 0.12f * (static_cast<float>(lv) - 1.0f));
    const int r = static_cast<int>(hp + 0.5f);
    return static_cast<std::uint16_t>(r < 1 ? 1 : (r > 65535 ? 65535 : r));
}

} // namespace giga::game
