// GENERATED by tools/gen_monster_traits.py from data/monster_traits.csv — do not
// hand-edit. Edit the CSV and re-run the generator; see [monsters.md] and the long
// note in game/monster_traits.h.
//
// 21 authored rows expanded to a DENSE 68-entry table, one per MobKind in kMobTable
// order. The unauthored entries are the default row (every multiplier 100, no resist,
// no vulnerability, no bait) and carry `authored = 0` so a reader can tell "this kind
// has no trait" from "this kind's trait happens to be neutral".
#include "game/monster_traits.h"

namespace giga::game {
namespace {
constexpr std::uint8_t u8(MobKind v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint8_t t(TerrainPref v) { return static_cast<std::uint8_t>(v); }
constexpr std::uint16_t b(BaitBit v) { return static_cast<std::uint16_t>(v); }
} // namespace

const std::array<MonsterTraits, kMobKindCount> kMonsterTraits = {{
    // [0] SBORKA  monster_bait.ts:74 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_sborka
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Starch) | b(BaitBit::Sugar) | b(BaitBit::Stale) | b(BaitBit::Govnyak)),
                   u8(MobKind::Sborka), 1 },
    // [1] TVAR  monster_bait.ts:75 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_tvar
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Meat) | b(BaitBit::Govnyak)),
                   u8(MobKind::Tvar), 1 },
    // [2] POLZUN  ai/monster.ts:5139 inPolzunKillCell 1.35 + monster_bait.ts:77
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 135, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Fungal) | b(BaitBit::Wet) | b(BaitBit::Govnyak)),
                   u8(MobKind::Polzun), 1 },
    // [3] BETONNIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Betonnik), 0 },
    // [4] ZOMBIE  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Zombie), 0 },
    // [5] EYE  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Eye), 0 },
    // [6] NIGHTMARE  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Nightmare), 0 },
    // [7] SHADOW  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Shadow), 0 },
    // [8] REBAR  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Rebar), 0 },
    // [9] MATKA  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Matka), 0 },
    // [10] IDOL  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Idol), 0 },
    // [11] MANCOBUS  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Mancobus), 0 },
    // [12] HERALD  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Herald), 0 },
    // [13] CREATOR  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Creator), 0 },
    // [14] SPIRIT  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Spirit), 0 },
    // [15] ROBOT  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Robot), 0 },
    // [16] SHOVNIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Shovnik), 0 },
    // [17] LAMPOVY  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Lampovy), 0 },
    // [18] PECHATEED  monster_bait.ts:80 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_pechateed
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Document)),
                   u8(MobKind::Pechateed), 1 },
    // [19] PARAGRAPH  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Paragraph), 0 },
    // [20] NELYUD  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Nelyud), 0 },
    // [21] KRYSNOZHKA  monster_bait.ts:71 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_krysnozhka
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Meat) | b(BaitBit::Fungal) | b(BaitBit::Stale) | b(BaitBit::Govnyak)),
                   u8(MobKind::Krysnozhka), 1 },
    // [22] KOSTOREZ  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Kostorez), 0 },
    // [23] SAFEGUARD  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Safeguard), 0 },
    // [24] BLACK_LIQUIDATOR  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::BlackLiquidator), 0 },
    // [25] KHOROVAYA_MATKA  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::KhorovayaMatka), 0 },
    // [26] SLIMEVIK  monster_ecology.ts:125 BAIT_ATTRACTED_MONSTER_KINDS with no trait row
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Govnyak)),
                   u8(MobKind::Slimevik), 1 },
    // [27] SOBRANNYY  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Sobrannyy), 0 },
    // [28] ZHORNAYA_TVAR  monster_bait.ts:76 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_zhornaya_tvar
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Meat) | b(BaitBit::Food) | b(BaitBit::Stale) | b(BaitBit::Risky) | b(BaitBit::Govnyak)),
                   u8(MobKind::ZhornayaTvar), 1 },
    // [29] BEZEKHIY  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Bezekhiy), 0 },
    // [30] PSEUDOLIFT  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Pseudolift), 0 },
    // [31] SLEPOGLAZ  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Slepoglaz), 0 },
    // [32] OLGOY  ai/monster.ts:3464 olgoyTerrainMoveMult + :3468 olgoyTerrainDmgMult
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Wet),
                   kNoVulnChannel, 0, 112, 55, 144, 82, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Meat) | b(BaitBit::Wet) | b(BaitBit::Risky) | b(BaitBit::Govnyak)),
                   u8(MobKind::Olgoy), 1 },
    // [33] VODYANOY_KOSHMAR  ai/monster.ts:5104 waterPressureLine 1.16/0.86
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Wet),
                   kNoVulnChannel, 0, 116, 86, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::VodyanoyKoshmar), 1 },
    // [34] LAMPOGLAZ  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Lampoglaz), 0 },
    // [35] TUMANNIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Tumannik), 0 },
    // [36] CHERNOSLIZ  ai/monster.ts:5089 blackWaterWake 1.0 on water / 0.46 off it
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Wet),
                   kNoVulnChannel, 0, 100, 46, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::Chernosliz), 1 },
    // [37] RZHAVNIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Rzhavnik), 0 },
    // [38] BETONOED  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Betonoed), 0 },
    // [39] PANELNIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Panelnik), 0 },
    // [40] PAUPSINA  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Paupsina), 0 },
    // [41] BORSHCHEVIK  borshchevik.ts:265 max(base ceil(maxHp*0.44))
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   3, 44, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::Borshchevik), 1 },
    // [42] OBZHIVALSHCHIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Obzhivalshchik), 0 },
    // [43] HEAD_SLUG  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::HeadSlug), 0 },
    // [44] PROTOKOLNIK  monster_bait.ts:82 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_protokolnik
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Document)),
                   u8(MobKind::Protokolnik), 1 },
    // [45] DIKIY_MERTVYAK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::DikiyMertvyak), 0 },
    // [46] KONTORSHCHIK  monster_bait.ts:81 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_kontorshchik
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Document)),
                   u8(MobKind::Kontorshchik), 1 },
    // [47] TONKAYA_TEN  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::TonkayaTen), 0 },
    // [48] KANTSELYARSKIY_IDOL  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::KantselyarskiyIdol), 0 },
    // [49] LOZHNYY_DUKH  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::LozhnyyDukh), 0 },
    // [50] CHERVIE_AVATAR  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::ChervieAvatar), 0 },
    // [51] POMOYNY_ROY  monster_bait.ts:72 BAIT_TRAITS_BY_ECOLOGY_TAG.monster_pomoyny_roy
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Food) | b(BaitBit::Meat) | b(BaitBit::Fungal) | b(BaitBit::Stale) | b(BaitBit::Govnyak)),
                   u8(MobKind::PomoynyRoy), 1 },
    // [52] SCULPTURE  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Sculpture), 0 },
    // [53] TRUBNYY_AVTOMAT  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::TrubnyyAvtomat), 0 },
    // [54] LOTOCHNIK  monster_traits.ts:104 drainArmor 0.58 + ai/monster.ts:286 wet regen 1.35/s
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Wet),
                   kNoVulnChannel, 0, 145, 72, 118, 78, 58, 1350,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::Lotochnik), 1 },
    // [55] TRESKOTNIK  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Treskotnik), 0 },
    // [56] ZAKALENNAYA_ARMATURA  monster_armor.ts:18 WEAK_DAMAGE_MULT 0.28 HEAVY_DAMAGE_MULT 0.68
    MonsterTraits{ {72, 32, 32, 32, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::ZakalennayaArmatura), 1 },
    // [57] GLUBINNAYA_TEN  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::GlubinnayaTen), 0 },
    // [58] GREEN_DOG  monster_ecology.ts:126 BAIT_ATTRACTED_MONSTER_KINDS with no trait row
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Govnyak)),
                   u8(MobKind::GreenDog), 1 },
    // [59] SLIME_WOMAN  ai/monster.ts:5110 slimeStrider 1.48 wet / 0.86 unlit dry
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Wet),
                   kNoVulnChannel, 0, 148, 86, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::SlimeWoman), 1 },
    // [60] GNILUSHKA  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Gnilushka), 0 },
    // [61] MUKHOZHUK_HOST  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::MukhozhukHost), 0 },
    // [62] FOG_SHARK  fog_shark.ts:61 max(base maxHp+1) — a guaranteed kill
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   3, 100, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::FogShark), 1 },
    // [63] BLOOD_PLANT  blood_plant.ts:245 max(base ceil(maxHp*0.38))
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   3, 38, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(0),
                   u8(MobKind::BloodPlant), 1 },
    // [64] SWARM  swarm_nests.ts:439 max(base hp) + monster_bait.ts:73
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   3, 100, 100, 100, 100, 100, 100, 0,
                   static_cast<std::uint16_t>(b(BaitBit::Meat) | b(BaitBit::Fungal) | b(BaitBit::Stale) | b(BaitBit::Govnyak)),
                   u8(MobKind::Swarm), 1 },
    // [65] SPORE_CARPET  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::SporeCarpet), 0 },
    // [66] LISHENNYY  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Lishennyy), 0 },
    // [67] GNOME  (default row)
    MonsterTraits{ {0, 0, 0, 0, 0}, t(TerrainPref::Any),
                   kNoVulnChannel, 0, 100, 100, 100, 100, 100, 0, 0,
                   u8(MobKind::Gnome), 0 },
}};

// Every row's `kind` must equal its index, or `monster_traits(k)` silently returns
// another monster's traits and nothing fails — the exact hazard kMobTable's own `kind`
// column exists to catch.
//
// NOT a static_assert, and the reason is worth stating so nobody "fixes" it back:
// `kMonsterTraits` is a runtime `const std::array` with external linkage, matching
// `kMobTable` and `kItemTable`, so a constexpr function may not read it (MSVC C2131 —
// measured, not guessed). Making the array `constexpr` to win the compile-time check
// would push 1,656 B of table into every translation unit that includes the header, to
// verify something the suite verifies in 69 comparisons at startup. So it is a runtime
// predicate that tests/suite_monster.inl asserts, which makes it a ctest failure rather
// than a compile failure — mechanical either way.
bool monster_traits_rows_indexed() {
    for (std::size_t i = 0; i < kMobKindCount; ++i)
        if (kMonsterTraits[i].kind != static_cast<std::uint8_t>(i)) return false;
    return true;
}

} // namespace giga::game
