// GENERATED by tools/gen_particle_table.py from data/particles.csv — do not
// hand-edit. Edit the CSV and re-run the generator; the `source_rules` ctest
// fails on drift.
//
// One row per PARTICLE TYPE of the unified GPU pool: mob blood and concrete
// dust differ by a row, never by code. The physics knobs (gravity multiplier,
// per-tick drag, restitution) are stamped onto each particle at spawn, so the
// compute sim (shaders/particle_sim.comp) needs no table of its own and can
// never drift from this one. `colorFromMaterial` rows take their tint from the
// generated kMaterial albedo of whatever was hit; the rest carry their own.
#pragma once

#include <cstdint>

namespace giga::game {

// Row ordinals — GENERATED, in CSV order (append-only: ParticleBurst stores
// this ordinal).
enum class ParticleKind : std::uint8_t {
    Dust = 0,
    Debris = 1,
    Blood = 2,
    Spark = 3,
    Drip = 4,
    Count
};

inline constexpr std::uint8_t kParticleKindCount = 5u;

struct ParticleDef {
    const char* id;         // CSV slug
    bool colorFromMaterial; // tint = kMaterial[matId] instead of r/g/b
    float r, g, b;          // fixed tint (ignored when colorFromMaterial)
    std::uint8_t emissive;  // 0..255, glows through fog like prop emissives
    float gravityMul;       // x world gravity (dust floats, debris drops)
    float drag;             // velocity retained per 60 Hz step (pow'd by dt)
    float bounce;           // restitution; 0 = the hit kills the particle
    float sizeM;            // billboard edge, metres
    float lifeS;            // seconds from spawn to gone
    float speedMps;         // writers' base burst speed
};

inline constexpr ParticleDef kParticleTable[kParticleKindCount] = {
    {"dust", true, 0.0f, 0.0f, 0.0f, 0, 0.30f, 0.93f, 0.0f, 0.07f, 2.2f, 1.6f},
    {"debris", true, 0.0f, 0.0f, 0.0f, 0, 1.0f, 0.997f, 0.35f, 0.14f, 3.5f, 2.6f},
    {"blood", false, 0.42f, 0.03f, 0.03f, 0, 1.0f, 0.99f, 0.0f, 0.075f, 1.8f, 2.8f},
    {"spark", false, 1.0f, 0.72f, 0.28f, 235, 0.45f, 0.996f, 0.55f, 0.035f, 0.8f, 6.5f},
    {"drip", false, 0.32f, 0.36f, 0.40f, 0, 1.0f, 1.0f, 0.0f, 0.055f, 4.0f, 0.3f},
};

inline const ParticleDef& particle_def(ParticleKind k) {
    const std::uint8_t i = static_cast<std::uint8_t>(k);
    return kParticleTable[i < kParticleKindCount ? i : 0];
}

} // namespace giga::game
