// GENERATED by tools/gen_prop_table.py from data/props.csv — do not
// hand-edit kPropCount or the PropId enum. Edit the CSV and re-run the generator.
// Hand-maintained helpers below the GENERATED marker are allowed only if the
// generator is updated to emit them; today the whole header is generated.
#pragma once

#include <array>
#include <cstdint>
#include <cstring>
#include <type_traits>

#include "core/math.h"

namespace giga::game {

inline constexpr std::size_t kPropCount = 12;

// Row order is data/props.csv row order and is load-bearing: a PropId is an
// index into the generated table. Append only — never reorder or insert.
enum class PropId : std::uint16_t {
    Terminal = 0,
    ElectricalShield = 1,
    BareBulb = 2,
    FloodLamp = 3,
    PadicStairBulb = 4,
    KitchenStove = 5,
    KitchenTable = 6,
    ToiletPan = 7,
    BedCot = 8,
    SupplyCrate = 9,
    Grenade = 10,
    FuelBarrel = 11,
};

// POD row. shape is the PropShape ordinal (render/prop_mesh.h); game never
// includes render headers. fallMode / interactKind are ordinals matching
// PropFallMode and Interactable::Kind in prop_system.h (255 = no interact).
// color*E3 are RGB x1000 (1000 = 1.0). reachMm is Interactable.reachM * 1000.
//
// MASS IS GRAMS IN A uint32, AND IT IS THE SAME UNIT EVERYWHERE — MobDef carries
// the identical field, and any future ItemDef weight will too. It used to be grams
// in a uint16 here and kg x10 in a uint16 there: the same 16 bits with two
// different meanings, which is [problems.md] §20's class exactly, and it was not
// theoretical — data/mobs.csv already carried 900 kg, fourteen times this table's
// old 65.5 kg ceiling, so a stove had to be authored at 65 kg instead of 80.
//
// The widening COST NOTHING: this row already carried `pad0_` and `pad1_`, so the
// four bytes came out of padding and the row is still exactly 24. Range is now
// 1 g .. 4294 tonnes, which brackets a 9 mm cartridge and a lift cabin with one
// encoding and no per-table conversion to misremember.
//
// СВЕТ — ИЗ ЭТОЙ ЖЕ СТРОКИ ([ddalight.md]): lightRadiusMm != 0 означает «проп
// излучает», и коллектор света видит ЛЮБОЙ такой проп — спец-случаев
// «лампочка» в коде нет. Радиус в мм, как reachMm — одна единица на таблицу.
// lightConeDeg — ПОЛУугол конуса, 0 = омни (занял бывший pad0_).
//
// Layout is explicit: 1 x uint32, 6 x uint8, 9 x uint16, 1 x uint32 pad = 32 bytes.
struct PropDef {
    std::uint32_t massG;            // 0  universal mass, GRAMS ([ecs] Mass)
    std::uint8_t  shape;            // 4  PropShape ordinal
    std::uint8_t  fallMode;         // 5  PropFallMode ordinal
    std::uint8_t  interactKind;     // 6  Interactable::Kind or 255
    std::uint8_t  emissive;         // 7  0..255 PropPass emissive
    std::uint8_t  matId;            // 8
    std::uint8_t  lightConeDeg;     // 9  полуугол конуса света, 0 = омни
    std::uint16_t colorRE3;         // 10 RGB x1000
    std::uint16_t colorGE3;         // 12
    std::uint16_t colorBE3;         // 14
    std::uint16_t reachMm;          // 16 Interactable reach in millimetres
    std::uint16_t sizeXMm;          // 18 authored mesh size, millimetres — the
    std::uint16_t sizeYMm;          // 20 unit shape is scaled to exactly this,
    std::uint16_t sizeZMm;          // 22 so a bulb is a bulb and not a 1 m drum
    std::uint16_t lightRadiusMm;    // 24 0 = не светит
    std::uint16_t lightIntensityE3; // 26 интенсивность x1000
    std::uint8_t  flickerProfile;   // 28 FlickerProfile ([game/flicker.h]):
                                    //    свет И emissive носителя, синхронно
    // ЗАРЯД ([combat.h] Charge, решение владельца 2026-08-21: «пропы в целом
    // могут взрываться»). explosiveG — масса ВВ в граммах, 0 = не заряд;
    // урон и радиус детонации ВЫВОДЯТСЯ из неё (S11), не назначаются.
    // Оба поля заняли бывшие pad0_/pad1_ — строка осталась 32 байта.
    std::uint8_t  chargeTrigger;    // 29 ChargeTrigger ниже
    std::uint16_t explosiveG;       // 30 масса ВВ, граммы
};
static_assert(sizeof(PropDef) == 32, "PropDef must stay a tight 32-byte row");
static_assert(alignof(PropDef) == 4);
static_assert(std::is_trivially_copyable_v<PropDef>);

// Как заряд срабатывает. none — сам не детонирует (взводится извне: фитиль
// гранаты взводит бросающий, [combat.h] spawn_grenade); damage — детонация
// вместо детача, когда проп сбивают выстрелом (бочка, баллон).
// Lockstep с CHARGE_TRIGGERS генератора.
enum class ChargeTrigger : std::uint8_t { None = 0, Damage = 1 };

// Строка — заряд? Выводится из массы ВВ, не объявляется отдельным флагом.
inline bool prop_is_charge(const PropDef& d) { return d.explosiveG > 0; }


// Generated from data/props.csv by tools/gen_prop_table.py.
extern const std::array<PropDef, kPropCount> kPropTable;
extern const std::array<const char*, kPropCount> kPropNames;
extern const std::array<const char*, kPropCount> kPropIds;

inline bool prop_valid(PropId id) {
    return static_cast<std::size_t>(id) < kPropCount;
}

inline const PropDef& prop_def(PropId id) {
    return kPropTable[static_cast<std::size_t>(id)];
}

inline const char* prop_name(PropId id) {
    return prop_valid(id) ? kPropNames[static_cast<std::size_t>(id)] : "";
}

inline const char* prop_id_str(PropId id) {
    return prop_valid(id) ? kPropIds[static_cast<std::size_t>(id)] : "";
}

// O(n) string lookup for tools/console — never call in the hot tick.
// Returns kPropCount-sized invalid sentinel when missing (check prop_valid).
inline PropId prop_id_by_string(const char* id) {
    if (!id || !*id) return static_cast<PropId>(kPropCount);
    for (std::size_t i = 0; i < kPropCount; ++i) {
        if (std::strcmp(kPropIds[i], id) == 0)
            return static_cast<PropId>(i);
    }
    return static_cast<PropId>(kPropCount);
}

// Строка светит? Радиус и интенсивность обязаны идти парой — одинокий ноль
// в любой из колонок означает «не источник».
inline bool prop_emits_light(const PropDef& d) {
    return d.lightRadiusMm != 0 && d.lightIntensityE3 != 0;
}

// Color as vec3 in 0..2 range (e3 / 1000).
inline vec3 prop_color(const PropDef& d) {
    return vec3{
        static_cast<float>(d.colorRE3) * 0.001f,
        static_cast<float>(d.colorGE3) * 0.001f,
        static_cast<float>(d.colorBE3) * 0.001f,
    };
}

inline vec3 prop_color(PropId id) {
    return prop_color(prop_def(id));
}
} // namespace giga::game
