// GENERATED by tools/gen_prop_form_table.py from data/prop_forms.csv — do
// not hand-edit. Edit the CSV and re-run the generator; the `source_rules`
// ctest fails on drift.
//
// ФОРМА СОСТАВНОГО ТЕЛА КАК ДАННЫЕ ([markoaudit/plans/ragdoll.md] §9, решение
// владельца 2026-08-21). Словарь движка замкнут — сфера и бокс; составное тело
// (труп, люстра на тросе, многосегментная мебель) — это строки: сегмент, его
// родитель, примитив, офсет и габарит В ДОЛЯХ габарита носителя, доля массы,
// вид связи. Новая форма = строки таблицы, не код.
//
// Доли, а не метры: одна строка обслуживает и ребёнка, и громилу — тело
// масштабируется собственным габаритом (S11). ox/oy и sx/sy — доли ШИРИНЫ
// тела, oz/sz — доли РОСТА; у сферы sx — доля роста для радиуса.
#pragma once

#include <cstdint>

namespace giga::game {

enum class FormPrim : std::uint8_t { Sphere = 0, Box = 1 };

// Индекс родителя внутри формы; 0xFF — корень (носитель сам).
inline constexpr std::uint8_t kFormNoParent = 0xFFu;

struct FormSegDef {
    const char* seg;        // CSV slug, для диагностики
    std::uint8_t parent;    // индекс сегмента-родителя, kFormNoParent у корня
    FormPrim prim;
    float ox, oy, oz;       // офсет от КОРНЯ в долях (W, W, H)
    float sx, sy, sz;       // полугабарит в долях (W, W, H); сфера — sx от H
    float massFrac;         // доля полной массы тела
    std::uint8_t rope;      // 1 — связь только тянет (верёвка), 0 — штанга
};

struct FormDef {
    const char* id;
    std::uint16_t first;    // индекс первого сегмента в kFormSegs
    std::uint16_t count;
};

inline constexpr std::uint16_t kFormCount = 1u;
inline constexpr std::uint16_t kFormSegCount = 4u;
// Длина самой большой формы — предел буфера сборщика (выведен из таблицы).
inline constexpr std::uint16_t kMaxFormSegs = 4u;

// Ordinals — GENERATED, CSV order.
enum class FormId : std::uint16_t {
    Humanoid = 0,
    Count
};

inline constexpr FormSegDef kFormSegs[kFormSegCount] = {
    {"pelvis", kFormNoParent, FormPrim::Box, 0.000000f, 0.000000f, 0.000000f, 0.450000f, 0.300000f, 0.100000f, 0.260000f, 0},
    {"chest", 0, FormPrim::Box, 0.010000f, 0.000000f, 0.250000f, 0.500000f, 0.300000f, 0.150000f, 0.330000f, 0},
    {"head", 1, FormPrim::Sphere, 0.020000f, 0.000000f, 0.470000f, 0.066700f, 0.066700f, 0.066700f, 0.080000f, 0},
    {"legs", 0, FormPrim::Box, -0.010000f, 0.000000f, -0.340000f, 0.400000f, 0.300000f, 0.220000f, 0.330000f, 0},
};

inline constexpr FormDef kFormTable[kFormCount] = {
    {"humanoid", 0, 4},
};

inline const FormDef& form_def(FormId f) {
    const std::uint16_t i = static_cast<std::uint16_t>(f);
    return kFormTable[i < kFormCount ? i : 0];
}

} // namespace giga::game
