// GENERATED by tools/gen_prop_table.py from data/props.csv — do not
// hand-edit. Edit the CSV and re-run the generator.
#include "game/prop_table.h"

namespace giga::game {

const std::array<PropDef, kPropCount> kPropTable = {{
    // [0] terminal
    PropDef{ 0, 0, 0, 0, 3, 0, 45000, 320, 350, 380, 2500, 900, 450, 1400 },
    // [1] electrical_shield
    PropDef{ 0, 0, 1, 0, 4, 0, 25000, 180, 200, 220, 2500, 600, 220, 900 },
    // [2] bare_bulb
    PropDef{ 3, 1, 2, 210, 0, 0, 300, 1000, 780, 450, 2500, 120, 120, 220 },
    // [3] flood_lamp
    PropDef{ 0, 1, 2, 150, 0, 0, 6000, 1000, 780, 450, 2500, 500, 140, 280 },
    // [4] padic_stair_bulb
    PropDef{ 2, 2, 2, 250, 0, 0, 0, 0, 1000, 950, 700, 2500 },
    // [5] elevator_door_fast
    PropDef{ 0, 0, 255, 0, 3, 0, 0, 0, 200, 250, 800, 2500 },
    // [6] elevator_door_down
    PropDef{ 0, 0, 255, 0, 3, 0, 0, 0, 800, 200, 200, 2500 },
    // [7] elevator_door_up
    PropDef{ 0, 0, 255, 0, 3, 0, 0, 0, 200, 800, 200, 2500 },
}};

// Display names. Cyrillic; suites assert non-empty / lead bytes.
const std::array<const char*, kPropCount> kPropNames = {{
    "Терминал",  // terminal
    "Электрощиток",  // electrical_shield
    "Лампочка Ильича",  // bare_bulb
    "Прожектор",  // flood_lamp
    "Лампочка падика",  // padic_stair_bulb
    "Лифт Фаст-тревела",  // elevator_door_fast
    "Лифт Вниз",  // elevator_door_down
    "Лифт Вверх",  // elevator_door_up
}};

const std::array<const char*, kPropCount> kPropIds = {{
    "terminal",
    "electrical_shield",
    "bare_bulb",
    "flood_lamp",
    "padic_stair_bulb",
    "elevator_door_fast",
    "elevator_door_down",
    "elevator_door_up",
}};

} // namespace giga::game
