// GENERATED by tools/gen_prop_table.py from data/props.csv — do not
// hand-edit kPropCount or the PropId enum. Edit the CSV and re-run the generator.
// Hand-maintained helpers below the GENERATED marker are allowed only if the
// generator is updated to emit them; today the whole header is generated.
#pragma once

#include <array>
#include <cstdint>
#include <cstring>
#include <type_traits>

#include "core/math.h"

namespace giga::game {

inline constexpr std::size_t kPropCount = 9;

// Row order is data/props.csv row order and is load-bearing: a PropId is an
// index into the generated table. Append only — never reorder or insert.
enum class PropId : std::uint16_t {
    Terminal = 0,
    ElectricalShield = 1,
    BareBulb = 2,
    FloodLamp = 3,
    PadicStairBulb = 4,
    KitchenStove = 5,
    KitchenTable = 6,
    ToiletPan = 7,
    BedCot = 8,
};

// POD row. shape is the PropShape ordinal (render/prop_mesh.h); game never
// includes render headers. fallMode / interactKind are ordinals matching
// PropFallMode and Interactable::Kind in prop_system.h (255 = no interact).
// color*E3 are RGB x1000 (1000 = 1.0). reachMm is Interactable.reachM * 1000.
// Layout is explicit: 6 x uint8 then 9 x uint16 = 24 bytes (no hidden padding).
struct PropDef {
    std::uint8_t  shape;         // 0  PropShape ordinal
    std::uint8_t  fallMode;      // 1  PropFallMode ordinal
    std::uint8_t  interactKind;  // 2  Interactable::Kind or 255
    std::uint8_t  emissive;      // 3  0..255 PropPass emissive
    std::uint8_t  matId;         // 4
    std::uint8_t  pad0_ = 0;     // 5
    std::uint16_t massG;         // 6  universal mass, grams ([ecs] Mass)
    std::uint16_t colorRE3;      // 8  RGB x1000
    std::uint16_t colorGE3;      // 10
    std::uint16_t colorBE3;      // 12
    std::uint16_t reachMm;       // 14 Interactable reach in millimetres
    std::uint16_t sizeXMm;       // 16 authored mesh size, millimetres — the
    std::uint16_t sizeYMm;       // 18 unit shape is scaled to exactly this,
    std::uint16_t sizeZMm;       // 20 so a bulb is a bulb and not a 1 m drum
    std::uint16_t pad1_ = 0;     // 22
};
static_assert(sizeof(PropDef) == 24, "PropDef must stay a tight 24-byte row");
static_assert(std::is_trivially_copyable_v<PropDef>);


// Generated from data/props.csv by tools/gen_prop_table.py.
extern const std::array<PropDef, kPropCount> kPropTable;
extern const std::array<const char*, kPropCount> kPropNames;
extern const std::array<const char*, kPropCount> kPropIds;

inline bool prop_valid(PropId id) {
    return static_cast<std::size_t>(id) < kPropCount;
}

inline const PropDef& prop_def(PropId id) {
    return kPropTable[static_cast<std::size_t>(id)];
}

inline const char* prop_name(PropId id) {
    return prop_valid(id) ? kPropNames[static_cast<std::size_t>(id)] : "";
}

inline const char* prop_id_str(PropId id) {
    return prop_valid(id) ? kPropIds[static_cast<std::size_t>(id)] : "";
}

// O(n) string lookup for tools/console — never call in the hot tick.
// Returns kPropCount-sized invalid sentinel when missing (check prop_valid).
inline PropId prop_id_by_string(const char* id) {
    if (!id || !*id) return static_cast<PropId>(kPropCount);
    for (std::size_t i = 0; i < kPropCount; ++i) {
        if (std::strcmp(kPropIds[i], id) == 0)
            return static_cast<PropId>(i);
    }
    return static_cast<PropId>(kPropCount);
}

// Color as vec3 in 0..2 range (e3 / 1000).
inline vec3 prop_color(const PropDef& d) {
    return vec3{
        static_cast<float>(d.colorRE3) * 0.001f,
        static_cast<float>(d.colorGE3) * 0.001f,
        static_cast<float>(d.colorBE3) * 0.001f,
    };
}

inline vec3 prop_color(PropId id) {
    return prop_color(prop_def(id));
}
} // namespace giga::game
