// GENERATED by tools/gen_prop_table.py from data/props.csv — do not
// hand-edit. Edit the CSV and re-run the generator.
#include "game/prop_table.h"

namespace giga::game {

const std::array<PropDef, kPropCount> kPropTable = {{
    // [0] terminal
    PropDef{ 45000, 0, 0, 0, 0, 3, 0, 320, 350, 380, 2500, 900, 450, 1400, 3000, 400, 4, 0, 0 },
    // [1] electrical_shield
    PropDef{ 25000, 0, 0, 1, 0, 4, 0, 180, 200, 220, 2500, 600, 220, 900, 0, 0, 0, 0, 0 },
    // [2] bare_bulb
    PropDef{ 300, 3, 2, 2, 210, 20, 0, 1000, 780, 450, 2500, 120, 120, 220, 12000, 1800, 1, 0, 0 },
    // [3] flood_lamp
    PropDef{ 6000, 0, 2, 2, 150, 20, 0, 1000, 780, 450, 2500, 500, 140, 280, 24000, 3000, 1, 0, 0 },
    // [4] padic_stair_bulb
    PropDef{ 300, 3, 2, 2, 210, 20, 0, 1000, 950, 700, 2500, 120, 120, 220, 12000, 1800, 1, 0, 0 },
    // [5] kitchen_stove
    PropDef{ 80000, 0, 0, 255, 0, 4, 0, 420, 430, 400, 2500, 700, 600, 900, 0, 0, 0, 0, 0 },
    // [6] kitchen_table
    PropDef{ 25000, 0, 0, 255, 0, 3, 0, 520, 420, 300, 2500, 1100, 700, 780, 0, 0, 0, 0, 0 },
    // [7] toilet_pan
    PropDef{ 35000, 3, 0, 255, 0, 3, 0, 880, 890, 870, 2500, 400, 400, 750, 0, 0, 0, 0, 0 },
    // [8] bed_cot
    PropDef{ 40000, 0, 0, 255, 0, 3, 0, 300, 340, 420, 2500, 1900, 850, 500, 0, 0, 0, 0, 0 },
    // [9] supply_crate
    PropDef{ 30000, 0, 0, 6, 0, 4, 0, 420, 460, 380, 2400, 1100, 1100, 900, 0, 0, 0, 0, 0 },
    // [10] grenade
    PropDef{ 600, 3, 1, 255, 0, 19, 0, 420, 500, 280, 0, 60, 60, 120, 0, 0, 0, 1, 60 },
}};

// Display names. Cyrillic; suites assert non-empty / lead bytes.
const std::array<const char*, kPropCount> kPropNames = {{
    "Терминал",  // terminal
    "Электрощиток",  // electrical_shield
    "Лампочка Ильича",  // bare_bulb
    "Прожектор",  // flood_lamp
    "Лампочка падика",  // padic_stair_bulb
    "Плита",  // kitchen_stove
    "Стол",  // kitchen_table
    "Унитаз",  // toilet_pan
    "Койка",  // bed_cot
    "Ящик",  // supply_crate
    "Граната Ф-1",  // grenade
}};

const std::array<const char*, kPropCount> kPropIds = {{
    "terminal",
    "electrical_shield",
    "bare_bulb",
    "flood_lamp",
    "padic_stair_bulb",
    "kitchen_stove",
    "kitchen_table",
    "toilet_pan",
    "bed_cot",
    "supply_crate",
    "grenade",
}};

} // namespace giga::game
