// GENERATED by tools/gen_quest_table.py from data/quests.csv -- do not hand-edit.
// Edit the CSV and re-run the generator.
//
// This file carries Cyrillic string literals (quest names and briefs), which is what
// makes /utf-8 load-bearing on MSVC rather than merely defensive -- the same reason
// item_table.cpp and mob_table.cpp need it ([AGENTS.md] section Build).
//
// Every row here was checked at generate time against data/items.csv and
// data/mobs.csv: a Fetch target can spawn at the shallowest floor it is offered on,
// a Hunt target can be rolled and lives at every habitat anchor in its offer band,
// and a Descend target is past the band it is offered in. See the generator's
// docstring for why that validation is the whole reason quests are a table.
#include "game/quest.h"

namespace giga::game {

namespace {
constexpr std::uint8_t u8(ObjectiveKind v) { return static_cast<std::uint8_t>(v); }
} // namespace

const std::array<QuestDef, kQuestCount> kQuestTable = {{
    // [0] QuestId 1  pump_1
    QuestDef{ 0u, 3, 120, 418, 0,
              0, u8(ObjectiveKind::Fetch), 0, 0, 2, {0, 0, 0} },
    // [1] QuestId 2  pump_2
    QuestDef{ 900000u, 1, 260, 227, 352,
              1, u8(ObjectiveKind::Fetch), 1, -14, 2, {0, 0, 0} },
    // [2] QuestId 3  medpost_1
    QuestDef{ 0u, 6, 90, 40, 0,
              0, u8(ObjectiveKind::Fetch), 0, 0, 2, {0, 0, 0} },
    // [3] QuestId 4  medpost_2
    QuestDef{ 600000u, 2, 300, 25, 407,
              2, u8(ObjectiveKind::Fetch), 3, -8, 2, {0, 0, 0} },
    // [4] QuestId 5  medpost_3
    QuestDef{ 900000u, 5, 420, 21, 0,
              0, u8(ObjectiveKind::Hunt), 4, 0, 14, {0, 0, 0} },
    // [5] QuestId 6  kantselyariya_1
    QuestDef{ 0u, 2, 140, 46, 0,
              0, u8(ObjectiveKind::Fetch), 0, 14, 30, {0, 0, 0} },
    // [6] QuestId 7  kantselyariya_2
    QuestDef{ 1200000u, 1, 700, 237, 404,
              1, u8(ObjectiveKind::Fetch), 6, 14, 30, {0, 0, 0} },
    // [7] QuestId 8  kantselyariya_3
    QuestDef{ 1500000u, 3, 1200, 44, 0,
              0, u8(ObjectiveKind::Hunt), 7, 23, 30, {0, 0, 0} },
    // [8] QuestId 9  bread_line
    QuestDef{ 420000u, 10, 110, 64, 0,
              0, u8(ObjectiveKind::Fetch), 0, 0, 2, {0, 0, 0} },
    // [9] QuestId 10  sbor_cleanup
    QuestDef{ 300000u, 8, 180, 0, 0,
              0, u8(ObjectiveKind::Hunt), 0, 0, 2, {0, 0, 0} },
    // [10] QuestId 11  hermo_leak
    QuestDef{ 480000u, 1, 220, 183, 0,
              0, u8(ObjectiveKind::Fetch), 0, -14, 2, {0, 0, 0} },
    // [11] QuestId 12  filter_run
    QuestDef{ 600000u, 2, 320, 159, 137,
              1, u8(ObjectiveKind::Fetch), 0, 0, 14, {0, 0, 0} },
    // [12] QuestId 13  dogs_at_the_door
    QuestDef{ 480000u, 4, 500, 58, 0,
              0, u8(ObjectiveKind::Hunt), 0, -8, 14, {0, 0, 0} },
    // [13] QuestId 14  urgent_morphine
    QuestDef{ 90000u, 1, 400, 239, 392,
              2, u8(ObjectiveKind::Fetch), 0, -14, -4, {0, 0, 0} },
    // [14] QuestId 15  eel_pit
    QuestDef{ 900000u, 2, 1100, 53, 0,
              0, u8(ObjectiveKind::Hunt), 0, -26, -14, {0, 0, 0} },
    // [15] QuestId 16  psi_supply
    QuestDef{ 1200000u, 1, 1800, 301, 239,
              1, u8(ObjectiveKind::Fetch), 0, -26, -14, {0, 0, 0} },
    // [16] QuestId 17  deep_shadow
    QuestDef{ 1800000u, 3, 2400, 57, 0,
              0, u8(ObjectiveKind::Hunt), 0, -50, -31, {0, 0, 0} },
    // [17] QuestId 18  go_deep
    QuestDef{ 2400000u, 26, 2600, 0, 0,
              0, u8(ObjectiveKind::Descend), 0, 0, 2, {0, 0, 0} },
    // [18] QuestId 19  deep_dive
    QuestDef{ 3600000u, 50, 6000, 0, 136,
              2, u8(ObjectiveKind::Descend), 0, -26, -14, {0, 0, 0} },
}};

const std::array<const char*, kQuestCount> kQuestNames = {{
    "Бирки вентилей",
    "Манометр для насоса",
    "Бинты на медпост",
    "Антибиотик до закрытия",
    "Крысоножки в кухонном блоке",
    "Пустые бланки",
    "Пропавшее дело",
    "Протокольник в архиве",
    "Хлеб к раздаче",
    "Сборки в коридоре",
    "Гермопрокладка на люк",
    "Фильтры на смену",
    "Стая у входа",
    "Ампула срочно",
    "Трубные автоматы",
    "ПСИ-стабилизатор",
    "Глубинные тени",
    "Отчёт с глубины",
    "Пятидесятый",
}};

const std::array<const char*, kQuestCount> kQuestBriefs = {{
    "Три бирки с производства — без них насос не примут.",
    "Манометр целый — не битый. Насос стоит и вода не идёт.",
    "Шесть бинтов. Смена кончается — перевязывать нечем.",
    "Два антибиотика и быстро — до закрытия медпоста.",
    "Пять крысоножек — и продукты перестанут пропадать.",
    "Два бланка. Без бланка заявку не примут — без заявки нет смены.",
    "Найди личное дело — закроем вопрос без доноса.",
    "Три протокольника. Они жрут архив быстрее описи.",
    "Десять паек хлеба. Очередь уже стоит.",
    "Восемь сборок. Мелочь — но детей не выпустить.",
    "Одна прокладка. Течёт — а до аварийной смены час.",
    "Два фильтра противогаза. Наши намокли ещё вчера.",
    "Четыре зелёные собаки — и можно открывать двери.",
    "Одна ампула морфина. У него минута — не больше.",
    "Два автомата в цеху. Пока стоят — линию не пустят.",
    "Один стабилизатор из медблока. Без него смена вниз не пойдёт.",
    "Три тени. Ниже тридцатого они уже не прячутся.",
    "Дойди до глубины 26 и вернись. Нужен живой отчёт.",
    "Глубина 50. Дойди и вернись — платим за отчёт а не за геройство.",
}};

} // namespace giga::game
