// GENERATED by tools/gen_status_table.py from data/status.csv — do not
// hand-edit. Edit the CSV and re-run the generator.
#include "game/status.h"

namespace giga::game {

const std::array<StatusDef, kStatusCount> kStatusTable = {{
    // [0] zhelemish_skin
    StatusDef{ 180000, 150000, 820, 820, 1000, 1000, 0, 700, 550, 45, 0, 0 },
    // [1] paupsina_web
    StatusDef{ 4200, 4200, 540, 220, 1000, 1000, 650, 1000, 1000, 0, 0, 0 },
    // [2] spore_haze
    StatusDef{ 4800, 2200, 1000, 1000, 1650, 1180, 0, 1000, 1000, 0, 196, 0 },
    // [3] govnyak_relief
    StatusDef{ 70000, 70000, 1000, 1000, 1000, 1000, 0, 1000, 1000, 0, 0, 1 },
    // [4] govnyak_cough
    StatusDef{ 210000, 210000, 1000, 1000, 1000, 1000, 0, 1000, 1000, 0, 0, 1 },
    // [5] govnyak_debt
    StatusDef{ 480000, 480000, 1000, 1000, 1000, 1000, 0, 1000, 1000, 0, 0, 1 },
    // [6] psi_stun
    StatusDef{ 10000, 10000, 1, 1, 1000, 1000, 10000, 1000, 1000, 0, 0, 0 },
}};

// Display names. Cyrillic, and never printed by a test: this host's
// console is CP1251 and would emit mojibake. Suites assert non-empty
// and count 0xD0/0xD1 lead bytes instead.
const std::array<const char*, kStatusCount> kStatusNames = {{
    "Кожа желемиша",  // zhelemish_skin
    "Паутина паупсины",  // paupsina_web
    "Споровая мгла",  // spore_haze
    "Облегчение",  // govnyak_relief
    "Кашель",  // govnyak_cough
    "Долг говняка",  // govnyak_debt
    "Пси-Оглушение",  // psi_stun
}};

} // namespace giga::game
