// GENERATED by tools/gen_verb_table.py from data/verbs.csv — do not
// hand-edit. Edit the CSV and re-run the generator; the `source_rules`
// ctest fails on drift.
//
// THE VERB VOCABULARY (CANON S12.2-S12.3): the shared language of prop,
// item, room, agent and deed. K = kVerbCount comes from the CSV and is
// never a literal in code. Ids are the CSV row order, STABLE BY CONTRACT
// (saved vectors key on them): append, never insert.
//
// PATIENCE (S13.5): 0..1 stored x1000; the urgency threshold is derived
// from it, never listed. shelter 0 = tolerates nothing; wander 1000 =
// never urgent, never zero demand.
#pragma once

#include <cstddef>
#include <cstdint>

namespace giga::game {

// Ordinal into every verb-indexed vector (demand, offer, declared, price).
using VerbId = std::uint8_t;

inline constexpr VerbId kVerbSleep = 0;  // канон S13.5
inline constexpr VerbId kVerbEat = 1;  // канон S13.5
inline constexpr VerbId kVerbDrink = 2;  // реф npc_utility: жажда чуть острее голода
inline constexpr VerbId kVerbToilet = 3;  // канон S13.5
inline constexpr VerbId kVerbWork = 4;  // канон S13.5
inline constexpr VerbId kVerbHeal = 5;  // реф: боль не терпит
inline constexpr VerbId kVerbTrade = 6;  // реф NPC_UTILITY_INTENT_PATIENCE
inline constexpr VerbId kVerbStore = 7;  // плановое дело — как работа
inline constexpr VerbId kVerbSocial = 8;  // реф NPC_UTILITY_INTENT_PATIENCE
inline constexpr VerbId kVerbShelter = 9;  // канон S13.5 — не терпит вовсе
inline constexpr VerbId kVerbPatrol = 10;  // канон S13.5
inline constexpr VerbId kVerbWander = 11;  // канон S13.5 — никогда не срочно и никогда не ноль
inline constexpr VerbId kVerbNest = 12;  // мобье: тяга домой уступает угрозам
inline constexpr VerbId kVerbHunt = 13;  // голод хищника
inline constexpr VerbId kVerbHaul = 14;  // донести важнее прогулки но уступает угрозе
inline constexpr VerbId kVerbProfit = 15;  // ценность — глагол (S12.3); шкала как у торговли

inline constexpr std::size_t kVerbCount = 16;

// Patience x1000 (S13.5), CSV column patience_e3.
inline constexpr std::uint16_t kVerbPatienceE3[kVerbCount] = {
    600,  // sleep
    350,  // eat
    300,  // drink
    200,  // toilet
    900,  // work
    150,  // heal
    850,  // trade
    900,  // store
    850,  // social
    0,  // shelter
    900,  // patrol
    1000,  // wander
    700,  // nest
    500,  // hunt
    400,  // haul
    850,  // profit
};

// CSV tokens — for sibling generators' column names and debug output.
inline constexpr const char* kVerbIds[kVerbCount] = {
    "sleep",
    "eat",
    "drink",
    "toilet",
    "work",
    "heal",
    "trade",
    "store",
    "social",
    "shelter",
    "patrol",
    "wander",
    "nest",
    "hunt",
    "haul",
    "profit",
};

// Display names — text for the player, never a lookup key (S13.9).
inline constexpr const char* kVerbNames[kVerbCount] = {
    "спать",
    "есть",
    "пить",
    "сортир",
    "работать",
    "лечиться",
    "торговать",
    "хранить",
    "общаться",
    "укрыться",
    "обходить",
    "шататься",
    "логово",
    "охотиться",
    "нести добычу",
    "нажива",
};

} // namespace giga::game
