// GENERATED by tools/gen_material_table.py from data/materials.csv + data/textures.csv
// — do not hand-edit. Edit the CSV and re-run the generator; the
// `source_rules` ctest fails on drift.
//
// The RENDER side of the material vocabulary: mean albedo per id (display-
// referred — the shading linearises once with pow(2.2)), and which KTX2 texture
// set skins an id. Albedos bound to a texture are MEASURED off the real
// photograph (data/textures.csv carries the linear mean and provenance);
// unbound rows are authored. Consumed by render/cube_pass.cpp only.
#pragma once

#include "core/math.h"
#include "world/materials.h"

namespace giga {

inline constexpr vec3 kMaterial[kMatCount] = {
    {0.00f, 0.00f, 0.00f},  //  0 air
    {0.30f, 0.30f, 0.28f},  //  1 concrete
    {0.24f, 0.36f, 0.18f},  //  2 soil
    {0.18f, 0.28f, 0.55f},  //  3 water_mark
    {0.36f, 0.30f, 0.22f},  //  4 slab_tan
    {0.10f, 0.85f, 0.42f},  //  5 extract
    {0.16f, 0.24f, 0.42f},  //  6 door
    {0.00f, 0.80f, 0.95f},  //  7 hub_pad
    {0.48f, 0.44f, 0.38f},  //  8 plaster
    {0.32f, 0.20f, 0.10f},  //  9 parquet
    {0.38f, 0.40f, 0.42f},  // 10 shop_shutter
    {0.26f, 0.16f, 0.12f},  // 11 lino
    {0.22f, 0.30f, 0.22f},  // 12 factory_wall
    {0.38f, 0.24f, 0.15f},  // 13 tread
    {0.40f, 0.20f, 0.08f},  // 14 rust
    {0.22f, 0.18f, 0.14f},  // 15 rubble
    {0.85f, 0.70f, 0.15f},  // 16 electric_grate
    {0.15f, 0.75f, 0.12f},  // 17 acid_pool
    {0.85f, 0.25f, 0.04f},  // 18 fire_cell
    {0.13f, 0.16f, 0.14f}   // 19 pipe_metal
};
static_assert(sizeof(kMaterial) / sizeof(kMaterial[0]) == kMatCount,
              "one albedo row per material id");

// Texture bindings: ids skinned by a KTX2 set. File names are the asset
// catalog's (data/textures.csv), joined onto the texture directory by the pass.
struct MaterialMap {
    CellType id;
    const char* albedo;     // never null for a row in this table
    const char* normal;     // "" when the set carries no normal map
    const char* roughness;  // "" when the set carries no roughness map
    float tileScale;        // world-space tiling multiplier
};
inline constexpr MaterialMap kMaterialMaps[] = {
    {kMatShopShutter, "painted_metal_shutter.ktx2", "painted_metal_shutter_normal.ktx2", "painted_metal_shutter_roughness.ktx2", 0.5f},  //  0 shop_shutter
    {kMatLino, "rubber_tiles.ktx2", "rubber_tiles_normal.ktx2", "rubber_tiles_roughness.ktx2", 0.5f}                                  ,  //  1 lino
    {kMatFactoryWall, "factory_wall.ktx2", "factory_wall_normal.ktx2", "factory_wall_roughness.ktx2", 0.5f}                           ,  //  2 factory_wall
    {kMatTread, "metal_grate_rusty.ktx2", "metal_grate_rusty_normal.ktx2", "metal_grate_rusty_roughness.ktx2", 0.5f}                  ,  //  3 tread
    {kMatRust, "rusty_metal_03.ktx2", "rusty_metal_03_normal.ktx2", "rusty_metal_03_roughness.ktx2", 0.5f}                            ,  //  4 rust
    {kMatRubble, "rusty_corrugated_iron.ktx2", "rusty_corrugated_iron_normal.ktx2", "rusty_corrugated_iron_roughness.ktx2", 0.5f}        //  5 rubble
};
inline constexpr int kMaterialMapCount = 6;
static_assert(sizeof(kMaterialMaps) / sizeof(kMaterialMaps[0]) == kMaterialMapCount,
              "kMaterialMaps count must match kMaterialMapCount");

} // namespace giga
