// GENERATED by tools/gen_material_table.py from data/materials.csv + data/textures.csv
// — do not hand-edit. Edit the CSV and re-run the generator; the
// `source_rules` ctest fails on drift.
//
// Physical material properties — the SIMULATION side of the vocabulary.
// Hardness is the integer resistance a hit's `power` is rolled against
// ([destruct.h]): power == hardness removes the sub-voxel with certainty,
// power == hardness/2 with probability 1/2, and so on. 0 = removed by any
// touch; kHardnessUnbreakable = infrastructure protected as DATA (doors carry
// their own HP machine, the hub/extract pads are the nav lattice's ground
// truth) — rows, not special cases in the carve loop.
#pragma once
#include <cstdint>

#include "world/materials.h"

namespace giga {

inline constexpr std::uint16_t kHardnessUnbreakable = 0xFFFF;

// Indexed by CellType. Scale anchored on concrete = 256 ([jirnyak.md] §1).
inline constexpr std::uint16_t kMatHardness[kMatCount] = {
    0                   ,  //  0 air
    256                 ,  //  1 concrete
    64                  ,  //  2 soil
    96                  ,  //  3 water
    192                 ,  //  4 slab_tan
    kHardnessUnbreakable,  //  5 extract
    kHardnessUnbreakable,  //  6 door
    kHardnessUnbreakable,  //  7 hub_pad
    32                  ,  //  8 plaster
    48                  ,  //  9 parquet
    128                 ,  // 10 shop_shutter
    40                  ,  // 11 lino
    256                 ,  // 12 factory_wall
    320                 ,  // 13 tread
    112                 ,  // 14 rust
    24                  ,  // 15 rubble
    384                 ,  // 16 electric_grate
    16                  ,  // 17 acid_pool
    16                  ,  // 18 fire_cell
    180                 ,  // 19 pipe_metal
    48                  ,  // 20 neon_tube
    96                  ,  // 21 glass
    0                   ,  // 22 toxic_gas
    224                 ,  // 23 asphalt
    384                 ,  // 24 door_steel
    kHardnessUnbreakable,  // 25 door_hermetic
    32                  ,  // 26 rubble_concrete
    8                   ,  // 27 rubble_soil
    24                  ,  // 28 rubble_slab_tan
    8                   ,  // 29 rubble_plaster
    8                   ,  // 30 rubble_parquet
    16                  ,  // 31 rubble_shop_shutter
    8                   ,  // 32 rubble_lino
    32                  ,  // 33 rubble_factory_wall
    40                  ,  // 34 rubble_tread
    14                  ,  // 35 rubble_rust
    48                  ,  // 36 rubble_electric_grate
    8                   ,  // 37 rubble_fire_cell
    22                  ,  // 38 rubble_pipe_metal
    8                   ,  // 39 rubble_neon_tube
    12                  ,  // 40 rubble_glass
    28                  ,  // 41 rubble_asphalt
    48                     // 42 rubble_door_steel
};

static_assert(sizeof(kMatHardness) / sizeof(kMatHardness[0]) == kMatCount,
              "every material needs a hardness row");

inline std::uint16_t material_hardness(CellType t) {
    return t < kMatCount ? kMatHardness[t] : kHardnessUnbreakable;
}

// Density in kg/m^3 — THE universal mass context ([jirnyak, 2026-08-02]): the
// mass of one sub-voxel is density * (0.25 m)^3, so debris, a falling chunk and
// a carve's ejecta all weigh what their material says with no per-thing
// authoring. Every impact law in the game is E = m v^2 / 2 and p = m v over
// masses that ultimately come from here or from a table's mass column.
inline constexpr float kMatDensity[kMatCount] = {
    0.0f   ,  //  0 air
    2400.0f,  //  1 concrete
    1600.0f,  //  2 soil
    1000.0f,  //  3 water
    2200.0f,  //  4 slab_tan
    2400.0f,  //  5 extract
    7800.0f,  //  6 door
    2400.0f,  //  7 hub_pad
    800.0f ,  //  8 plaster
    700.0f ,  //  9 parquet
    7800.0f,  // 10 shop_shutter
    1200.0f,  // 11 lino
    7800.0f,  // 12 factory_wall
    7800.0f,  // 13 tread
    5200.0f,  // 14 rust
    1800.0f,  // 15 rubble
    7800.0f,  // 16 electric_grate
    1100.0f,  // 17 acid_pool
    200.0f ,  // 18 fire_cell
    7800.0f,  // 19 pipe_metal
    1400.0f,  // 20 neon_tube
    2500.0f,  // 21 glass
    3.0f   ,  // 22 toxic_gas
    2300.0f,  // 23 asphalt
    2900.0f,  // 24 door_steel
    7800.0f,  // 25 door_hermetic
    1800.0f,  // 26 rubble_concrete
    1200.0f,  // 27 rubble_soil
    1650.0f,  // 28 rubble_slab_tan
    600.0f ,  // 29 rubble_plaster
    525.0f ,  // 30 rubble_parquet
    5850.0f,  // 31 rubble_shop_shutter
    900.0f ,  // 32 rubble_lino
    5850.0f,  // 33 rubble_factory_wall
    5850.0f,  // 34 rubble_tread
    3900.0f,  // 35 rubble_rust
    5850.0f,  // 36 rubble_electric_grate
    150.0f ,  // 37 rubble_fire_cell
    5850.0f,  // 38 rubble_pipe_metal
    1050.0f,  // 39 rubble_neon_tube
    1875.0f,  // 40 rubble_glass
    1725.0f,  // 41 rubble_asphalt
    2175.0f   // 42 rubble_door_steel
};

// (material_subvoxel_mass_kg СНЕСЁН аудитом 2026-08-25 решением владельца:
// ноль вызывающих — детач/рыхлое массу атомов не считает. ЗАМЫСЕЛ записан
// вердиктом владельца 2026-08-27: закон «масса = kMatDensity × 0.25³»
// вернётся с эпиком цельных кусков-пропов — когда обломок мира из вокселей
// конвертируется в ПРОП (S3/S16.3: тяжёлый кусок, обязанный бить больно,
// = RagdollRoll) и его масса обязана быть Σ масс атомов, а не назначением;
// без неё урон падения E = mv²/2 (impact.cpp) посчитать нечем. До того
// эпика функции не существует намеренно — мёртвый API дороже надгробия.)

// СРЕДЫ (CANON S16, мир-автомат). Движение материи читает ТОЛЬКО параметры:
//   flow      — доля, перетекающая вбок за подтик автомата: 0 = твёрдое
//               (лежит; падает, когда опоры нет — это и есть обломки),
//               1 = вода (референс: вязкость 1 мПа·с; прочие жидкости =
//               вязкость_воды/вязкость — вывод в note строки CSV);
//   diffusion — расползание без гравитации (газы); 1 = воздух (референс:
//               выравнивается за один подтик).
// phase — МЕТКА для геймплейных предикатов (проходимость, плавучесть,
// дыхание); физика движения её НЕ читает и ветки по ней не имеет (S16.2).
// Метка и параметры не могут разойтись — генератор это гейтит (жидкость
// обязана течь, газ обязан диффундировать; воздух обязан быть газом).
enum class MatPhase : std::uint8_t { Solid = 0, Liquid = 1, Gas = 2 };

inline constexpr std::uint8_t kMatPhase[kMatCount] = {
    2,  //  0 air
    0,  //  1 concrete
    0,  //  2 soil
    1,  //  3 water
    0,  //  4 slab_tan
    0,  //  5 extract
    0,  //  6 door
    0,  //  7 hub_pad
    0,  //  8 plaster
    0,  //  9 parquet
    0,  // 10 shop_shutter
    0,  // 11 lino
    0,  // 12 factory_wall
    0,  // 13 tread
    0,  // 14 rust
    0,  // 15 rubble
    0,  // 16 electric_grate
    1,  // 17 acid_pool
    0,  // 18 fire_cell
    0,  // 19 pipe_metal
    0,  // 20 neon_tube
    0,  // 21 glass
    2,  // 22 toxic_gas
    0,  // 23 asphalt
    0,  // 24 door_steel
    0,  // 25 door_hermetic
    0,  // 26 rubble_concrete
    0,  // 27 rubble_soil
    0,  // 28 rubble_slab_tan
    0,  // 29 rubble_plaster
    0,  // 30 rubble_parquet
    0,  // 31 rubble_shop_shutter
    0,  // 32 rubble_lino
    0,  // 33 rubble_factory_wall
    0,  // 34 rubble_tread
    0,  // 35 rubble_rust
    0,  // 36 rubble_electric_grate
    0,  // 37 rubble_fire_cell
    0,  // 38 rubble_pipe_metal
    0,  // 39 rubble_neon_tube
    0,  // 40 rubble_glass
    0,  // 41 rubble_asphalt
    0   // 42 rubble_door_steel
};

inline constexpr float kMatFlow[kMatCount] = {
    1.000f,  //  0 air
    0.000f,  //  1 concrete
    0.000f,  //  2 soil
    1.000f,  //  3 water
    0.000f,  //  4 slab_tan
    0.000f,  //  5 extract
    0.000f,  //  6 door
    0.000f,  //  7 hub_pad
    0.000f,  //  8 plaster
    0.000f,  //  9 parquet
    0.000f,  // 10 shop_shutter
    0.000f,  // 11 lino
    0.000f,  // 12 factory_wall
    0.000f,  // 13 tread
    0.000f,  // 14 rust
    1.000f,  // 15 rubble
    0.000f,  // 16 electric_grate
    0.100f,  // 17 acid_pool
    0.000f,  // 18 fire_cell
    0.000f,  // 19 pipe_metal
    0.000f,  // 20 neon_tube
    0.000f,  // 21 glass
    0.000f,  // 22 toxic_gas
    0.000f,  // 23 asphalt
    0.000f,  // 24 door_steel
    0.000f,  // 25 door_hermetic
    1.000f,  // 26 rubble_concrete
    1.000f,  // 27 rubble_soil
    1.000f,  // 28 rubble_slab_tan
    1.000f,  // 29 rubble_plaster
    1.000f,  // 30 rubble_parquet
    1.000f,  // 31 rubble_shop_shutter
    1.000f,  // 32 rubble_lino
    1.000f,  // 33 rubble_factory_wall
    1.000f,  // 34 rubble_tread
    1.000f,  // 35 rubble_rust
    1.000f,  // 36 rubble_electric_grate
    1.000f,  // 37 rubble_fire_cell
    1.000f,  // 38 rubble_pipe_metal
    1.000f,  // 39 rubble_neon_tube
    1.000f,  // 40 rubble_glass
    1.000f,  // 41 rubble_asphalt
    1.000f   // 42 rubble_door_steel
};

inline constexpr float kMatDiffusion[kMatCount] = {
    1.000f,  //  0 air
    0.000f,  //  1 concrete
    0.000f,  //  2 soil
    0.500f,  //  3 water
    0.000f,  //  4 slab_tan
    0.000f,  //  5 extract
    0.000f,  //  6 door
    0.000f,  //  7 hub_pad
    0.000f,  //  8 plaster
    0.000f,  //  9 parquet
    0.000f,  // 10 shop_shutter
    0.000f,  // 11 lino
    0.000f,  // 12 factory_wall
    0.000f,  // 13 tread
    0.000f,  // 14 rust
    0.000f,  // 15 rubble
    0.000f,  // 16 electric_grate
    0.050f,  // 17 acid_pool
    0.000f,  // 18 fire_cell
    0.000f,  // 19 pipe_metal
    0.000f,  // 20 neon_tube
    0.000f,  // 21 glass
    0.500f,  // 22 toxic_gas
    0.000f,  // 23 asphalt
    0.000f,  // 24 door_steel
    0.000f,  // 25 door_hermetic
    0.000f,  // 26 rubble_concrete
    0.000f,  // 27 rubble_soil
    0.000f,  // 28 rubble_slab_tan
    0.000f,  // 29 rubble_plaster
    0.000f,  // 30 rubble_parquet
    0.000f,  // 31 rubble_shop_shutter
    0.000f,  // 32 rubble_lino
    0.000f,  // 33 rubble_factory_wall
    0.000f,  // 34 rubble_tread
    0.000f,  // 35 rubble_rust
    0.000f,  // 36 rubble_electric_grate
    0.000f,  // 37 rubble_fire_cell
    0.000f,  // 38 rubble_pipe_metal
    0.000f,  // 39 rubble_neon_tube
    0.000f,  // 40 rubble_glass
    0.000f,  // 41 rubble_asphalt
    0.000f   // 42 rubble_door_steel
};

inline MatPhase material_phase(CellType t) {
    return t < kMatCount ? static_cast<MatPhase>(kMatPhase[t]) : MatPhase::Solid;
}

// «Материя сред» — строка даёт движение (flow или diffusion > 0) и это не
// воздух. ЕДИНСТВЕННАЯ выписка закона: класс-байт 3 зеркала
// (render/voxel_mirror.cpp), агностичный карв (world/destruct.cpp) и
// GPU-двойник (shaders/medium_sim.comp, mobile()) обязаны совпадать с ней.
inline bool material_is_medium(CellType t) {
    return t != 0 && t < kMatCount &&
           (kMatFlow[t] > 0.0f || kMatDiffusion[t] > 0.0f);
}

// ОПОРА (CANON S20.5, «подвижное — не опора», решение владельца 2026-08-29):
// атом ПОДВИЖНОГО материала — материи сред, включая рыхлых двойников — не
// передаёт опору судье связности (world/destruct.cpp) и не держит якорь
// (world/anchor.h). Куча рыхлого не несёт балкон; балка, держащаяся только
// за кучу, конвертируется одним судом — петля «дебрис рождает дебрис»
// разомкнута по построению. Выведено из параметров строки (S16.2), ни
// флага, ни ветки по имени материала.
inline bool material_bears_load(CellType t) {
    return t != 0 && t < kMatCount && !material_is_medium(t);
}

// РЫХЛЫЙ ДВОЙНИК строки (решение владельца 2026-08-24): детач меняет строку
// куска на двойника — тот выглядит исходником (альбедо/текстура
// наследуются) и падает автоматом. Не-рушимое и среды — сами себя.
inline constexpr CellType kMatRubbleOf[kMatCount] = {
    0 ,  //  0 air
    26,  //  1 concrete
    27,  //  2 soil
    3 ,  //  3 water
    28,  //  4 slab_tan
    5 ,  //  5 extract
    6 ,  //  6 door
    7 ,  //  7 hub_pad
    29,  //  8 plaster
    30,  //  9 parquet
    31,  // 10 shop_shutter
    32,  // 11 lino
    33,  // 12 factory_wall
    34,  // 13 tread
    35,  // 14 rust
    15,  // 15 rubble
    36,  // 16 electric_grate
    17,  // 17 acid_pool
    37,  // 18 fire_cell
    38,  // 19 pipe_metal
    39,  // 20 neon_tube
    40,  // 21 glass
    22,  // 22 toxic_gas
    41,  // 23 asphalt
    42,  // 24 door_steel
    25,  // 25 door_hermetic
    26,  // 26 rubble_concrete
    27,  // 27 rubble_soil
    28,  // 28 rubble_slab_tan
    29,  // 29 rubble_plaster
    30,  // 30 rubble_parquet
    31,  // 31 rubble_shop_shutter
    32,  // 32 rubble_lino
    33,  // 33 rubble_factory_wall
    34,  // 34 rubble_tread
    35,  // 35 rubble_rust
    36,  // 36 rubble_electric_grate
    37,  // 37 rubble_fire_cell
    38,  // 38 rubble_pipe_metal
    39,  // 39 rubble_neon_tube
    40,  // 40 rubble_glass
    41,  // 41 rubble_asphalt
    42   // 42 rubble_door_steel
};

inline CellType material_rubble_of(CellType t) {
    return t < kMatCount ? kMatRubbleOf[t] : t;
}

// СВЕТОМАТЕРИАЛЫ ([ddalight.md]): light_radius_mm != 0 — ячейки этого
// материала излучают; бейк этажа кластеризует их в статические эмиттеры
// (game/light_bake.h). Цвет источника = альбедо материала: нарисованный
// неон светит тем цветом, каким покрашен. Единицы — мм и x1000, как в
// data/props.csv (одна величина = одна единица во всех таблицах).
inline constexpr std::uint16_t kMatLightRadiusMm[kMatCount] = {
    0   ,  //  0 air
    0   ,  //  1 concrete
    0   ,  //  2 soil
    0   ,  //  3 water
    0   ,  //  4 slab_tan
    0   ,  //  5 extract
    0   ,  //  6 door
    0   ,  //  7 hub_pad
    0   ,  //  8 plaster
    0   ,  //  9 parquet
    0   ,  // 10 shop_shutter
    0   ,  // 11 lino
    0   ,  // 12 factory_wall
    0   ,  // 13 tread
    0   ,  // 14 rust
    0   ,  // 15 rubble
    0   ,  // 16 electric_grate
    0   ,  // 17 acid_pool
    0   ,  // 18 fire_cell
    0   ,  // 19 pipe_metal
    8000,  // 20 neon_tube
    0   ,  // 21 glass
    0   ,  // 22 toxic_gas
    0   ,  // 23 asphalt
    0   ,  // 24 door_steel
    0   ,  // 25 door_hermetic
    0   ,  // 26 rubble_concrete
    0   ,  // 27 rubble_soil
    0   ,  // 28 rubble_slab_tan
    0   ,  // 29 rubble_plaster
    0   ,  // 30 rubble_parquet
    0   ,  // 31 rubble_shop_shutter
    0   ,  // 32 rubble_lino
    0   ,  // 33 rubble_factory_wall
    0   ,  // 34 rubble_tread
    0   ,  // 35 rubble_rust
    0   ,  // 36 rubble_electric_grate
    0   ,  // 37 rubble_fire_cell
    0   ,  // 38 rubble_pipe_metal
    0   ,  // 39 rubble_neon_tube
    0   ,  // 40 rubble_glass
    0   ,  // 41 rubble_asphalt
    0      // 42 rubble_door_steel
};

inline constexpr std::uint16_t kMatLightIntensityE3[kMatCount] = {
    0   ,  //  0 air
    0   ,  //  1 concrete
    0   ,  //  2 soil
    0   ,  //  3 water
    0   ,  //  4 slab_tan
    0   ,  //  5 extract
    0   ,  //  6 door
    0   ,  //  7 hub_pad
    0   ,  //  8 plaster
    0   ,  //  9 parquet
    0   ,  // 10 shop_shutter
    0   ,  // 11 lino
    0   ,  // 12 factory_wall
    0   ,  // 13 tread
    0   ,  // 14 rust
    0   ,  // 15 rubble
    0   ,  // 16 electric_grate
    0   ,  // 17 acid_pool
    0   ,  // 18 fire_cell
    0   ,  // 19 pipe_metal
    1500,  // 20 neon_tube
    0   ,  // 21 glass
    0   ,  // 22 toxic_gas
    0   ,  // 23 asphalt
    0   ,  // 24 door_steel
    0   ,  // 25 door_hermetic
    0   ,  // 26 rubble_concrete
    0   ,  // 27 rubble_soil
    0   ,  // 28 rubble_slab_tan
    0   ,  // 29 rubble_plaster
    0   ,  // 30 rubble_parquet
    0   ,  // 31 rubble_shop_shutter
    0   ,  // 32 rubble_lino
    0   ,  // 33 rubble_factory_wall
    0   ,  // 34 rubble_tread
    0   ,  // 35 rubble_rust
    0   ,  // 36 rubble_electric_grate
    0   ,  // 37 rubble_fire_cell
    0   ,  // 38 rubble_pipe_metal
    0   ,  // 39 rubble_neon_tube
    0   ,  // 40 rubble_glass
    0   ,  // 41 rubble_asphalt
    0      // 42 rubble_door_steel
};

// Linear albedo per id — the light colour source for emitters (and the same
// numbers render/material_table.h carries for shading).
inline constexpr float kMatAlbedoR[kMatCount] = {
    0.000f,  //  0 air
    0.300f,  //  1 concrete
    0.240f,  //  2 soil
    0.180f,  //  3 water
    0.360f,  //  4 slab_tan
    0.100f,  //  5 extract
    0.160f,  //  6 door
    0.000f,  //  7 hub_pad
    0.480f,  //  8 plaster
    0.320f,  //  9 parquet
    0.380f,  // 10 shop_shutter
    0.260f,  // 11 lino
    0.220f,  // 12 factory_wall
    0.380f,  // 13 tread
    0.400f,  // 14 rust
    0.220f,  // 15 rubble
    0.850f,  // 16 electric_grate
    0.150f,  // 17 acid_pool
    0.850f,  // 18 fire_cell
    0.130f,  // 19 pipe_metal
    0.250f,  // 20 neon_tube
    0.620f,  // 21 glass
    0.350f,  // 22 toxic_gas
    0.090f,  // 23 asphalt
    0.340f,  // 24 door_steel
    0.300f,  // 25 door_hermetic
    0.255f,  // 26 rubble_concrete
    0.204f,  // 27 rubble_soil
    0.306f,  // 28 rubble_slab_tan
    0.408f,  // 29 rubble_plaster
    0.272f,  // 30 rubble_parquet
    0.323f,  // 31 rubble_shop_shutter
    0.221f,  // 32 rubble_lino
    0.187f,  // 33 rubble_factory_wall
    0.323f,  // 34 rubble_tread
    0.340f,  // 35 rubble_rust
    0.722f,  // 36 rubble_electric_grate
    0.722f,  // 37 rubble_fire_cell
    0.111f,  // 38 rubble_pipe_metal
    0.212f,  // 39 rubble_neon_tube
    0.527f,  // 40 rubble_glass
    0.076f,  // 41 rubble_asphalt
    0.289f   // 42 rubble_door_steel
};
inline constexpr float kMatAlbedoG[kMatCount] = {
    0.000f,  //  0 air
    0.300f,  //  1 concrete
    0.360f,  //  2 soil
    0.280f,  //  3 water
    0.300f,  //  4 slab_tan
    0.850f,  //  5 extract
    0.240f,  //  6 door
    0.800f,  //  7 hub_pad
    0.440f,  //  8 plaster
    0.200f,  //  9 parquet
    0.400f,  // 10 shop_shutter
    0.160f,  // 11 lino
    0.300f,  // 12 factory_wall
    0.240f,  // 13 tread
    0.200f,  // 14 rust
    0.180f,  // 15 rubble
    0.700f,  // 16 electric_grate
    0.750f,  // 17 acid_pool
    0.250f,  // 18 fire_cell
    0.160f,  // 19 pipe_metal
    0.950f,  // 20 neon_tube
    0.700f,  // 21 glass
    0.550f,  // 22 toxic_gas
    0.090f,  // 23 asphalt
    0.360f,  // 24 door_steel
    0.330f,  // 25 door_hermetic
    0.255f,  // 26 rubble_concrete
    0.306f,  // 27 rubble_soil
    0.255f,  // 28 rubble_slab_tan
    0.374f,  // 29 rubble_plaster
    0.170f,  // 30 rubble_parquet
    0.340f,  // 31 rubble_shop_shutter
    0.136f,  // 32 rubble_lino
    0.255f,  // 33 rubble_factory_wall
    0.204f,  // 34 rubble_tread
    0.170f,  // 35 rubble_rust
    0.595f,  // 36 rubble_electric_grate
    0.212f,  // 37 rubble_fire_cell
    0.136f,  // 38 rubble_pipe_metal
    0.807f,  // 39 rubble_neon_tube
    0.595f,  // 40 rubble_glass
    0.076f,  // 41 rubble_asphalt
    0.306f   // 42 rubble_door_steel
};
inline constexpr float kMatAlbedoB[kMatCount] = {
    0.000f,  //  0 air
    0.280f,  //  1 concrete
    0.180f,  //  2 soil
    0.550f,  //  3 water
    0.220f,  //  4 slab_tan
    0.420f,  //  5 extract
    0.420f,  //  6 door
    0.950f,  //  7 hub_pad
    0.380f,  //  8 plaster
    0.100f,  //  9 parquet
    0.420f,  // 10 shop_shutter
    0.120f,  // 11 lino
    0.220f,  // 12 factory_wall
    0.150f,  // 13 tread
    0.080f,  // 14 rust
    0.140f,  // 15 rubble
    0.150f,  // 16 electric_grate
    0.120f,  // 17 acid_pool
    0.040f,  // 18 fire_cell
    0.140f,  // 19 pipe_metal
    0.850f,  // 20 neon_tube
    0.720f,  // 21 glass
    0.250f,  // 22 toxic_gas
    0.100f,  // 23 asphalt
    0.380f,  // 24 door_steel
    0.310f,  // 25 door_hermetic
    0.238f,  // 26 rubble_concrete
    0.153f,  // 27 rubble_soil
    0.187f,  // 28 rubble_slab_tan
    0.323f,  // 29 rubble_plaster
    0.085f,  // 30 rubble_parquet
    0.357f,  // 31 rubble_shop_shutter
    0.102f,  // 32 rubble_lino
    0.187f,  // 33 rubble_factory_wall
    0.128f,  // 34 rubble_tread
    0.068f,  // 35 rubble_rust
    0.128f,  // 36 rubble_electric_grate
    0.034f,  // 37 rubble_fire_cell
    0.119f,  // 38 rubble_pipe_metal
    0.722f,  // 39 rubble_neon_tube
    0.612f,  // 40 rubble_glass
    0.085f,  // 41 rubble_asphalt
    0.323f   // 42 rubble_door_steel
};

inline bool material_emits_light(CellType t) {
    return t < kMatCount && kMatLightRadiusMm[t] != 0 && kMatLightIntensityE3[t] != 0;
}

// ПРОЗРАЧНОСТЬ ДЛЯ СВЕТА (data/materials.csv light_transparent; решение
// владельца 2026-08-24, neon-topology): теневой луч и бейк видимости прощают
// субвоксель, если его материал ПРОЗРАЧЕН — а не если светится. Воздух и
// эмиттеры прозрачны по построению (выведено кодогеном); стекло — строкой
// CSV: свет проходит, материя стоит. Оба места одного закона читают эту
// колонку: shaders/raymarch.frag shadow_cell_occluded (kMatLightPass) и
// game/light_vis_bake.cpp light_ray_passes (material_passes_light).
inline constexpr std::uint8_t kMatLightPass[kMatCount] = {
    1,  //  0 air
    0,  //  1 concrete
    0,  //  2 soil
    0,  //  3 water
    0,  //  4 slab_tan
    0,  //  5 extract
    0,  //  6 door
    0,  //  7 hub_pad
    0,  //  8 plaster
    0,  //  9 parquet
    0,  // 10 shop_shutter
    0,  // 11 lino
    0,  // 12 factory_wall
    0,  // 13 tread
    0,  // 14 rust
    0,  // 15 rubble
    0,  // 16 electric_grate
    0,  // 17 acid_pool
    0,  // 18 fire_cell
    0,  // 19 pipe_metal
    1,  // 20 neon_tube
    1,  // 21 glass
    1,  // 22 toxic_gas
    0,  // 23 asphalt
    0,  // 24 door_steel
    0,  // 25 door_hermetic
    0,  // 26 rubble_concrete
    0,  // 27 rubble_soil
    0,  // 28 rubble_slab_tan
    0,  // 29 rubble_plaster
    0,  // 30 rubble_parquet
    0,  // 31 rubble_shop_shutter
    0,  // 32 rubble_lino
    0,  // 33 rubble_factory_wall
    0,  // 34 rubble_tread
    0,  // 35 rubble_rust
    0,  // 36 rubble_electric_grate
    0,  // 37 rubble_fire_cell
    0,  // 38 rubble_pipe_metal
    0,  // 39 rubble_neon_tube
    0,  // 40 rubble_glass
    0,  // 41 rubble_asphalt
    0   // 42 rubble_door_steel
};

inline bool material_passes_light(CellType t) {
    return t < kMatCount && kMatLightPass[t] != 0;
}

} // namespace giga
