// GENERATED by tools/gen_material_table.py from data/materials.csv + data/textures.csv
// — do not hand-edit. Edit the CSV and re-run the generator; the
// `source_rules` ctest fails on drift.
//
// Physical material properties — the SIMULATION side of the vocabulary.
// Hardness is the integer resistance a hit's `power` is rolled against
// ([destruct.h]): power == hardness removes the sub-voxel with certainty,
// power == hardness/2 with probability 1/2, and so on. 0 = removed by any
// touch; kHardnessUnbreakable = infrastructure protected as DATA (doors carry
// their own HP machine, the hub/extract pads are the nav lattice's ground
// truth) — rows, not special cases in the carve loop.
#pragma once
#include <cstdint>

#include "world/materials.h"

namespace giga {

inline constexpr std::uint16_t kHardnessUnbreakable = 0xFFFF;

// Indexed by CellType. Scale anchored on concrete = 256 ([jirnyak.md] §1).
inline constexpr std::uint16_t kMatHardness[kMatCount] = {
    0                   ,  //  0 air
    256                 ,  //  1 concrete
    64                  ,  //  2 soil
    96                  ,  //  3 water_mark
    192                 ,  //  4 slab_tan
    kHardnessUnbreakable,  //  5 extract
    kHardnessUnbreakable,  //  6 door
    kHardnessUnbreakable,  //  7 hub_pad
    32                  ,  //  8 plaster
    48                  ,  //  9 parquet
    128                 ,  // 10 shop_shutter
    40                  ,  // 11 lino
    256                 ,  // 12 factory_wall
    320                 ,  // 13 tread
    112                 ,  // 14 rust
    24                  ,  // 15 rubble
    384                 ,  // 16 electric_grate
    16                  ,  // 17 acid_pool
    16                  ,  // 18 fire_cell
    180                    // 19 pipe_metal
};

static_assert(sizeof(kMatHardness) / sizeof(kMatHardness[0]) == kMatCount,
              "every material needs a hardness row");

inline std::uint16_t material_hardness(CellType t) {
    return t < kMatCount ? kMatHardness[t] : kHardnessUnbreakable;
}

// Density in kg/m^3 — THE universal mass context ([jirnyak, 2026-08-02]): the
// mass of one sub-voxel is density * (0.25 m)^3, so debris, a falling chunk and
// a carve's ejecta all weigh what their material says with no per-thing
// authoring. Every impact law in the game is E = m v^2 / 2 and p = m v over
// masses that ultimately come from here or from a table's mass column.
inline constexpr float kMatDensity[kMatCount] = {
    0.0f   ,  //  0 air
    2400.0f,  //  1 concrete
    1600.0f,  //  2 soil
    1000.0f,  //  3 water_mark
    2200.0f,  //  4 slab_tan
    2400.0f,  //  5 extract
    7800.0f,  //  6 door
    2400.0f,  //  7 hub_pad
    800.0f ,  //  8 plaster
    700.0f ,  //  9 parquet
    7800.0f,  // 10 shop_shutter
    1200.0f,  // 11 lino
    7800.0f,  // 12 factory_wall
    7800.0f,  // 13 tread
    5200.0f,  // 14 rust
    1800.0f,  // 15 rubble
    7800.0f,  // 16 electric_grate
    1100.0f,  // 17 acid_pool
    200.0f ,  // 18 fire_cell
    7800.0f   // 19 pipe_metal
};

// Mass of ONE sub-voxel (0.25 m cube) of this material, in kg.
inline constexpr float kSubVoxelVolumeM3 = 0.25f * 0.25f * 0.25f;
inline float material_subvoxel_mass_kg(CellType t) {
    return (t < kMatCount ? kMatDensity[t] : 0.0f) * kSubVoxelVolumeM3;
}

} // namespace giga
