// GENERATED by tools/gen_material_table.py from data/materials.csv + data/textures.csv
// — do not hand-edit. Edit the CSV and re-run the generator; the
// `source_rules` ctest fails on drift.
//
// Cell material ids — the shared vocabulary between the generators that WRITE
// cells and the render pass that gives them a colour. `CellType` is an opaque
// uint16 to the engine ([voxels.md]); these constants are the game's meanings
// for it. They live in world/ because the render pass needs them and render
// must never include game/ ([ARCHITECTURE.md] layering). A material id is a
// LABEL: the only tables keyed on it are generated siblings of this file.
//
// Ids are the CSV row order and STABLE BY CONTRACT: geometry in saves stores
// CellType verbatim, so a new material is appended, never inserted.
#pragma once

#include "world/macro_grid.h"  // CellType, kCellAir

namespace giga {

inline constexpr CellType kMatConcrete = 1;       // aged Soviet panel concrete; poured smooth, no panel seams
inline constexpr CellType kMatSoil = 2;           // organic earth / soil mottle
inline constexpr CellType kMatWaterMark = 3;      // legacy water marker
inline constexpr CellType kMatSlabTan = 4;        // muted tan concrete slab
inline constexpr CellType kMatExtract = 5;        // the bank pad: signage, not surface — unbreakable infrastructure
inline constexpr CellType kMatDoor = 6;           // door leaf + frame; carve-immune, owned by the door state machine
inline constexpr CellType kMatHubPad = 7;         // nav / fast-travel pad: lattice ground truth, unbreakable
inline constexpr CellType kMatPlaster = 8;        // AUTHORED: dirty whitewash over precast panel; broad stains ~2.9 m
inline constexpr CellType kMatParquet = 9;        // AUTHORED: varnished oak, board-to-board tone; 10 cm boards
inline constexpr CellType kMatShopShutter = 10;    // roller-shutter slats, 7 cm
inline constexpr CellType kMatLino = 11;           // dark rubber with seams; 50 cm tiles
inline constexpr CellType kMatFactoryWall = 12;    // green corrugated factory metal, 15 cm corrugation
inline constexpr CellType kMatTread = 13;          // walkway grate, 25 cm studs
inline constexpr CellType kMatRust = 14;           // thresholded low-frequency patches ~1.5 m; corroded, weaker than fresh st
inline constexpr CellType kMatRubble = 15;         // chunk plateaus at 33 cm; already broken once
inline constexpr CellType kMatElectricGrate = 16;  // AUTHORED: electrified floor grate — tread lattice, hot hazard tint
inline constexpr CellType kMatAcidPool = 17;       // AUTHORED: caustic pool surface, broad slicks
inline constexpr CellType kMatFireCell = 18;       // AUTHORED: burning floor cell
inline constexpr CellType kMatPipeMetal = 19;      // AUTHORED: baked wall-pipe runs (antourage) — painted steel conduit, dent
inline constexpr CellType kMatNeonTube = 20;       // неоновая трубка — светоматериал: лепи вывески/лампы вокселями, бейк клас

// One past the last id in use. Every generated sibling table is sized from the
// same CSV, so a row added without regenerating fails the source_rules gate
// rather than rendering as an unremarkable default.
inline constexpr CellType kMatCount = 21;

} // namespace giga
