// GENERATED by tools/gen_material_table.py from data/materials.csv + data/textures.csv
// — do not hand-edit. Edit the CSV and re-run the generator; the
// `source_rules` ctest fails on drift.
//
// Cell material ids — the shared vocabulary between the generators that WRITE
// cells and the render pass that gives them a colour. `CellType` is an opaque
// uint16 to the engine ([voxels.md]); these constants are the game's meanings
// for it. They live in world/ because the render pass needs them and render
// must never include game/ ([ARCHITECTURE.md] layering). A material id is a
// LABEL: the only tables keyed on it are generated siblings of this file.
//
// Ids are the CSV row order and STABLE BY CONTRACT: geometry in saves stores
// CellType verbatim, so a new material is appended, never inserted.
#pragma once

#include "world/macro_grid.h"  // CellType, kCellAir

namespace giga {

inline constexpr CellType kMatConcrete = 1;       // aged Soviet panel concrete; poured smooth, no panel seams
inline constexpr CellType kMatSoil = 2;           // organic earth / soil mottle
inline constexpr CellType kMatWater = 3;          // вода — настоящая материя автомата (S16); референс текучести: flow 1.0 пр
inline constexpr CellType kMatSlabTan = 4;        // muted tan concrete slab
inline constexpr CellType kMatExtract = 5;        // the bank pad: signage, not surface — unbreakable infrastructure
inline constexpr CellType kMatDoor = 6;           // door leaf + frame; carve-immune, owned by the door state machine
inline constexpr CellType kMatHubPad = 7;         // nav / fast-travel pad: lattice ground truth, unbreakable
inline constexpr CellType kMatPlaster = 8;        // AUTHORED: dirty whitewash over precast panel; broad stains ~2.9 m
inline constexpr CellType kMatParquet = 9;        // AUTHORED: varnished oak, board-to-board tone; 10 cm boards
inline constexpr CellType kMatShopShutter = 10;    // roller-shutter slats, 7 cm
inline constexpr CellType kMatLino = 11;           // dark rubber with seams; 50 cm tiles
inline constexpr CellType kMatFactoryWall = 12;    // green corrugated factory metal, 15 cm corrugation
inline constexpr CellType kMatTread = 13;          // walkway grate, 25 cm studs
inline constexpr CellType kMatRust = 14;           // thresholded low-frequency patches ~1.5 m; corroded, weaker than fresh st
inline constexpr CellType kMatRubble = 15;         // chunk plateaus at 33 cm; already broken once; рыхлое: flow 0.1 из угла е
inline constexpr CellType kMatElectricGrate = 16;  // AUTHORED: electrified floor grate — tread lattice, hot hazard tint
inline constexpr CellType kMatAcidPool = 17;       // AUTHORED: caustic pool surface, broad slicks; жижа ~10 мПа·с → flow = вя
inline constexpr CellType kMatFireCell = 18;       // AUTHORED: burning floor cell
inline constexpr CellType kMatPipeMetal = 19;      // AUTHORED: baked wall-pipe runs (antourage) — painted steel conduit, dent
inline constexpr CellType kMatNeonTube = 20;       // неоновая трубка — светоматериал: лепи вывески/лампы вокселями, бейк клас
inline constexpr CellType kMatGlass = 21;          // стекло — первый потребитель колонки прозрачности: свет проходит (light_t

// One past the last id in use. Every generated sibling table is sized from the
// same CSV, so a row added without regenerating fails the source_rules gate
// rather than rendering as an unremarkable default.
inline constexpr CellType kMatCount = 22;

// CSV-имена строк по id — словарь команд и логов (консоль `sphere <имя>`
// говорит на языке таблицы, не констант). Указатели на литералы, без аллокаций.
inline constexpr const char* kMatNames[kMatCount] = {
    "air"           ,  //  0 air
    "concrete"      ,  //  1 concrete
    "soil"          ,  //  2 soil
    "water"         ,  //  3 water
    "slab_tan"      ,  //  4 slab_tan
    "extract"       ,  //  5 extract
    "door"          ,  //  6 door
    "hub_pad"       ,  //  7 hub_pad
    "plaster"       ,  //  8 plaster
    "parquet"       ,  //  9 parquet
    "shop_shutter"  ,  // 10 shop_shutter
    "lino"          ,  // 11 lino
    "factory_wall"  ,  // 12 factory_wall
    "tread"         ,  // 13 tread
    "rust"          ,  // 14 rust
    "rubble"        ,  // 15 rubble
    "electric_grate",  // 16 electric_grate
    "acid_pool"     ,  // 17 acid_pool
    "fire_cell"     ,  // 18 fire_cell
    "pipe_metal"    ,  // 19 pipe_metal
    "neon_tube"     ,  // 20 neon_tube
    "glass"            // 21 glass
};

// id по CSV-имени (линейный скан таблицы — она мала, зов из консоли).
// kMatCount = «нет такого материала».
inline CellType material_id_by_name(const char* name) {
    for (CellType i = 0; i < kMatCount; ++i) {
        const char* a = kMatNames[i];
        const char* b = name;
        while (*a && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0) return i;
    }
    return kMatCount;
}

} // namespace giga
