// GENERATED by tools/gen_material_table.py from data/materials.csv + data/textures.csv
// — do not hand-edit. Edit the CSV and re-run the generator; the
// `source_rules` ctest fails on drift.
//
// Physical material properties — the SIMULATION side of the vocabulary.
// Hardness is the integer resistance a hit's `power` is rolled against
// ([destruct.h]): power == hardness removes the sub-voxel with certainty,
// power == hardness/2 with probability 1/2, and so on. 0 = removed by any
// touch; kHardnessUnbreakable = infrastructure protected as DATA (doors carry
// their own HP machine, the hub/extract pads are the nav lattice's ground
// truth) — rows, not special cases in the carve loop.
#pragma once
#include <cstdint>

#include "world/materials.h"

namespace giga {

inline constexpr std::uint16_t kHardnessUnbreakable = 0xFFFF;

// Indexed by CellType. Scale anchored on concrete = 256 ([jirnyak.md] §1).
inline constexpr std::uint16_t kMatHardness[kMatCount] = {
    0                   ,  //  0 air
    256                 ,  //  1 concrete
    64                  ,  //  2 soil
    96                  ,  //  3 water
    192                 ,  //  4 slab_tan
    kHardnessUnbreakable,  //  5 extract
    kHardnessUnbreakable,  //  6 door
    kHardnessUnbreakable,  //  7 hub_pad
    32                  ,  //  8 plaster
    48                  ,  //  9 parquet
    128                 ,  // 10 shop_shutter
    40                  ,  // 11 lino
    256                 ,  // 12 factory_wall
    320                 ,  // 13 tread
    112                 ,  // 14 rust
    24                  ,  // 15 rubble
    384                 ,  // 16 electric_grate
    16                  ,  // 17 acid_pool
    16                  ,  // 18 fire_cell
    180                 ,  // 19 pipe_metal
    48                  ,  // 20 neon_tube
    96                     // 21 glass
};

static_assert(sizeof(kMatHardness) / sizeof(kMatHardness[0]) == kMatCount,
              "every material needs a hardness row");

inline std::uint16_t material_hardness(CellType t) {
    return t < kMatCount ? kMatHardness[t] : kHardnessUnbreakable;
}

// Density in kg/m^3 — THE universal mass context ([jirnyak, 2026-08-02]): the
// mass of one sub-voxel is density * (0.25 m)^3, so debris, a falling chunk and
// a carve's ejecta all weigh what their material says with no per-thing
// authoring. Every impact law in the game is E = m v^2 / 2 and p = m v over
// masses that ultimately come from here or from a table's mass column.
inline constexpr float kMatDensity[kMatCount] = {
    0.0f   ,  //  0 air
    2400.0f,  //  1 concrete
    1600.0f,  //  2 soil
    1000.0f,  //  3 water
    2200.0f,  //  4 slab_tan
    2400.0f,  //  5 extract
    7800.0f,  //  6 door
    2400.0f,  //  7 hub_pad
    800.0f ,  //  8 plaster
    700.0f ,  //  9 parquet
    7800.0f,  // 10 shop_shutter
    1200.0f,  // 11 lino
    7800.0f,  // 12 factory_wall
    7800.0f,  // 13 tread
    5200.0f,  // 14 rust
    1800.0f,  // 15 rubble
    7800.0f,  // 16 electric_grate
    1100.0f,  // 17 acid_pool
    200.0f ,  // 18 fire_cell
    7800.0f,  // 19 pipe_metal
    1400.0f,  // 20 neon_tube
    2500.0f   // 21 glass
};

// Mass of ONE sub-voxel (0.25 m cube) of this material, in kg.
inline constexpr float kSubVoxelVolumeM3 = 0.25f * 0.25f * 0.25f;
inline float material_subvoxel_mass_kg(CellType t) {
    return (t < kMatCount ? kMatDensity[t] : 0.0f) * kSubVoxelVolumeM3;
}

// СРЕДЫ (CANON S16, мир-автомат). Движение материи читает ТОЛЬКО параметры:
//   flow      — доля, перетекающая вбок за подтик автомата: 0 = твёрдое
//               (лежит; падает, когда опоры нет — это и есть обломки),
//               1 = вода (референс: вязкость 1 мПа·с; прочие жидкости =
//               вязкость_воды/вязкость — вывод в note строки CSV);
//   diffusion — расползание без гравитации (газы); 1 = воздух (референс:
//               выравнивается за один подтик).
// phase — МЕТКА для геймплейных предикатов (проходимость, плавучесть,
// дыхание); физика движения её НЕ читает и ветки по ней не имеет (S16.2).
// Метка и параметры не могут разойтись — генератор это гейтит (жидкость
// обязана течь, газ обязан диффундировать; воздух обязан быть газом).
enum class MatPhase : std::uint8_t { Solid = 0, Liquid = 1, Gas = 2 };

inline constexpr std::uint8_t kMatPhase[kMatCount] = {
    2,  //  0 air
    0,  //  1 concrete
    0,  //  2 soil
    1,  //  3 water
    0,  //  4 slab_tan
    0,  //  5 extract
    0,  //  6 door
    0,  //  7 hub_pad
    0,  //  8 plaster
    0,  //  9 parquet
    0,  // 10 shop_shutter
    0,  // 11 lino
    0,  // 12 factory_wall
    0,  // 13 tread
    0,  // 14 rust
    0,  // 15 rubble
    0,  // 16 electric_grate
    1,  // 17 acid_pool
    0,  // 18 fire_cell
    0,  // 19 pipe_metal
    0,  // 20 neon_tube
    0   // 21 glass
};

inline constexpr float kMatFlow[kMatCount] = {
    1.000f,  //  0 air
    0.000f,  //  1 concrete
    0.000f,  //  2 soil
    1.000f,  //  3 water
    0.000f,  //  4 slab_tan
    0.000f,  //  5 extract
    0.000f,  //  6 door
    0.000f,  //  7 hub_pad
    0.000f,  //  8 plaster
    0.000f,  //  9 parquet
    0.000f,  // 10 shop_shutter
    0.000f,  // 11 lino
    0.000f,  // 12 factory_wall
    0.000f,  // 13 tread
    0.000f,  // 14 rust
    0.100f,  // 15 rubble
    0.000f,  // 16 electric_grate
    0.100f,  // 17 acid_pool
    0.000f,  // 18 fire_cell
    0.000f,  // 19 pipe_metal
    0.000f,  // 20 neon_tube
    0.000f   // 21 glass
};

inline constexpr float kMatDiffusion[kMatCount] = {
    1.000f,  //  0 air
    0.000f,  //  1 concrete
    0.000f,  //  2 soil
    0.500f,  //  3 water
    0.000f,  //  4 slab_tan
    0.000f,  //  5 extract
    0.000f,  //  6 door
    0.000f,  //  7 hub_pad
    0.000f,  //  8 plaster
    0.000f,  //  9 parquet
    0.000f,  // 10 shop_shutter
    0.000f,  // 11 lino
    0.000f,  // 12 factory_wall
    0.000f,  // 13 tread
    0.000f,  // 14 rust
    0.000f,  // 15 rubble
    0.000f,  // 16 electric_grate
    0.050f,  // 17 acid_pool
    0.000f,  // 18 fire_cell
    0.000f,  // 19 pipe_metal
    0.000f,  // 20 neon_tube
    0.000f   // 21 glass
};

inline MatPhase material_phase(CellType t) {
    return t < kMatCount ? static_cast<MatPhase>(kMatPhase[t]) : MatPhase::Solid;
}

// «Материя сред» — строка даёт движение (flow или diffusion > 0) и это не
// воздух. ЕДИНСТВЕННАЯ выписка закона: класс-байт 3 зеркала
// (render/voxel_mirror.cpp), агностичный карв (world/destruct.cpp) и
// GPU-двойник (shaders/medium_sim.comp, mobile()) обязаны совпадать с ней.
inline bool material_is_medium(CellType t) {
    return t != 0 && t < kMatCount &&
           (kMatFlow[t] > 0.0f || kMatDiffusion[t] > 0.0f);
}

// СВЕТОМАТЕРИАЛЫ ([ddalight.md]): light_radius_mm != 0 — ячейки этого
// материала излучают; бейк этажа кластеризует их в статические эмиттеры
// (game/light_bake.h). Цвет источника = альбедо материала: нарисованный
// неон светит тем цветом, каким покрашен. Единицы — мм и x1000, как в
// data/props.csv (одна величина = одна единица во всех таблицах).
inline constexpr std::uint16_t kMatLightRadiusMm[kMatCount] = {
    0   ,  //  0 air
    0   ,  //  1 concrete
    0   ,  //  2 soil
    0   ,  //  3 water
    0   ,  //  4 slab_tan
    0   ,  //  5 extract
    0   ,  //  6 door
    0   ,  //  7 hub_pad
    0   ,  //  8 plaster
    0   ,  //  9 parquet
    0   ,  // 10 shop_shutter
    0   ,  // 11 lino
    0   ,  // 12 factory_wall
    0   ,  // 13 tread
    0   ,  // 14 rust
    0   ,  // 15 rubble
    0   ,  // 16 electric_grate
    0   ,  // 17 acid_pool
    0   ,  // 18 fire_cell
    0   ,  // 19 pipe_metal
    8000,  // 20 neon_tube
    0      // 21 glass
};

inline constexpr std::uint16_t kMatLightIntensityE3[kMatCount] = {
    0   ,  //  0 air
    0   ,  //  1 concrete
    0   ,  //  2 soil
    0   ,  //  3 water
    0   ,  //  4 slab_tan
    0   ,  //  5 extract
    0   ,  //  6 door
    0   ,  //  7 hub_pad
    0   ,  //  8 plaster
    0   ,  //  9 parquet
    0   ,  // 10 shop_shutter
    0   ,  // 11 lino
    0   ,  // 12 factory_wall
    0   ,  // 13 tread
    0   ,  // 14 rust
    0   ,  // 15 rubble
    0   ,  // 16 electric_grate
    0   ,  // 17 acid_pool
    0   ,  // 18 fire_cell
    0   ,  // 19 pipe_metal
    1500,  // 20 neon_tube
    0      // 21 glass
};

// Linear albedo per id — the light colour source for emitters (and the same
// numbers render/material_table.h carries for shading).
inline constexpr float kMatAlbedoR[kMatCount] = {
    0.000f,  //  0 air
    0.300f,  //  1 concrete
    0.240f,  //  2 soil
    0.180f,  //  3 water
    0.360f,  //  4 slab_tan
    0.100f,  //  5 extract
    0.160f,  //  6 door
    0.000f,  //  7 hub_pad
    0.480f,  //  8 plaster
    0.320f,  //  9 parquet
    0.380f,  // 10 shop_shutter
    0.260f,  // 11 lino
    0.220f,  // 12 factory_wall
    0.380f,  // 13 tread
    0.400f,  // 14 rust
    0.220f,  // 15 rubble
    0.850f,  // 16 electric_grate
    0.150f,  // 17 acid_pool
    0.850f,  // 18 fire_cell
    0.130f,  // 19 pipe_metal
    0.250f,  // 20 neon_tube
    0.620f   // 21 glass
};
inline constexpr float kMatAlbedoG[kMatCount] = {
    0.000f,  //  0 air
    0.300f,  //  1 concrete
    0.360f,  //  2 soil
    0.280f,  //  3 water
    0.300f,  //  4 slab_tan
    0.850f,  //  5 extract
    0.240f,  //  6 door
    0.800f,  //  7 hub_pad
    0.440f,  //  8 plaster
    0.200f,  //  9 parquet
    0.400f,  // 10 shop_shutter
    0.160f,  // 11 lino
    0.300f,  // 12 factory_wall
    0.240f,  // 13 tread
    0.200f,  // 14 rust
    0.180f,  // 15 rubble
    0.700f,  // 16 electric_grate
    0.750f,  // 17 acid_pool
    0.250f,  // 18 fire_cell
    0.160f,  // 19 pipe_metal
    0.950f,  // 20 neon_tube
    0.700f   // 21 glass
};
inline constexpr float kMatAlbedoB[kMatCount] = {
    0.000f,  //  0 air
    0.280f,  //  1 concrete
    0.180f,  //  2 soil
    0.550f,  //  3 water
    0.220f,  //  4 slab_tan
    0.420f,  //  5 extract
    0.420f,  //  6 door
    0.950f,  //  7 hub_pad
    0.380f,  //  8 plaster
    0.100f,  //  9 parquet
    0.420f,  // 10 shop_shutter
    0.120f,  // 11 lino
    0.220f,  // 12 factory_wall
    0.150f,  // 13 tread
    0.080f,  // 14 rust
    0.140f,  // 15 rubble
    0.150f,  // 16 electric_grate
    0.120f,  // 17 acid_pool
    0.040f,  // 18 fire_cell
    0.140f,  // 19 pipe_metal
    0.850f,  // 20 neon_tube
    0.720f   // 21 glass
};

inline bool material_emits_light(CellType t) {
    return t < kMatCount && kMatLightRadiusMm[t] != 0 && kMatLightIntensityE3[t] != 0;
}

// ПРОЗРАЧНОСТЬ ДЛЯ СВЕТА (data/materials.csv light_transparent; решение
// владельца 2026-08-24, neon-topology): теневой луч и бейк видимости прощают
// субвоксель, если его материал ПРОЗРАЧЕН — а не если светится. Воздух и
// эмиттеры прозрачны по построению (выведено кодогеном); стекло — строкой
// CSV: свет проходит, материя стоит. Оба места одного закона читают эту
// колонку: shaders/raymarch.frag shadow_cell_occluded (kMatLightPass) и
// game/light_vis_bake.cpp light_ray_passes (material_passes_light).
inline constexpr std::uint8_t kMatLightPass[kMatCount] = {
    1,  //  0 air
    0,  //  1 concrete
    0,  //  2 soil
    0,  //  3 water
    0,  //  4 slab_tan
    0,  //  5 extract
    0,  //  6 door
    0,  //  7 hub_pad
    0,  //  8 plaster
    0,  //  9 parquet
    0,  // 10 shop_shutter
    0,  // 11 lino
    0,  // 12 factory_wall
    0,  // 13 tread
    0,  // 14 rust
    0,  // 15 rubble
    0,  // 16 electric_grate
    0,  // 17 acid_pool
    0,  // 18 fire_cell
    0,  // 19 pipe_metal
    1,  // 20 neon_tube
    1   // 21 glass
};

inline bool material_passes_light(CellType t) {
    return t < kMatCount && kMatLightPass[t] != 0;
}

} // namespace giga
