// gigahrush2 entry point.
//
// Brings up an SDL3 window + Vulkan, builds the level stack, seeds an alife
// population and embodies one of its records as the player (who owns the
// CameraTag + Controller — the "player is just an embodied record" model,
// [npcs.md]), and runs a fixed-timestep sim loop against a variable-rate render
// loop with an ImGui HUD.
//
// The default world is the floor-MODULE stack: several distinct 128^3 floors,
// each its own LevelStack layer generated by generate_floor() and themed by its
// FloorKind (floor_gen.h / floors.md), wired through a FloorRegistry. `[` and
// `]` travel down/up a floor so the separate modules are visible. `gigahrush2
// maze` selects the single-world labyrinth test bed instead.
//
// Controls: WASD move, mouse look (hold right mouse / press Tab to toggle),
// Space jump, F toggles fly, [ / ] change floor, Esc quits.
#include <SDL3/SDL.h>
#include <SDL3/SDL_vulkan.h>

#include <cstdint>
#include <cstdio>
#include <string>

#include "imgui.h"
#include "imgui_impl_sdl3.h"

#include "app/worldgen.h"
#include "core/math.h"
#include "ecs/components.h"
#include "ecs/registry.h"
#include "game/embody.h"
#include "game/elevator.h"
#include "game/floor_gen.h"
#include "game/floor_registry.h"
#include "game/floor_spec.h"
#include "game/npc_pool.h"
#include "game/population.h"
#include "input/input.h"
#include "render/body_pass.h"
#include "render/cube_pass.h"
#include "render/imgui_layer.h"
#include "render/vk_device.h"
#include "render/vk_renderer.h"
#include "render/vk_swapchain.h"
#include "sim/camera.h"
#include "sim/controller.h"
#include "sim/fluid.h"
#include "sim/physics.h"
#include "world/level_stack.h"

using namespace giga;

namespace {

constexpr int kWinW = 1280;
constexpr int kWinH = 720;

// Fixed sim step (seconds). Physics + controller run at this rate; rendering is
// uncapped and interpolation is skipped for simplicity (the step is small).
constexpr float kSimDt = 1.0f / 120.0f;

// The demo floor stack: one row per floor MODULE. Numbers are the in-game labels
// the FloorRegistry assigns (floors.md); kinds are picked to show every geometry
// family side by side. Floor 0 is the residential hub the player starts on.
struct DemoFloor {
    int number;
    game::FloorKind kind;
};
constexpr DemoFloor kDemoFloors[] = {
    {0, game::FloorKind::Residential}, // start / hub
    {1, game::FloorKind::Commercial},
    {2, game::FloorKind::Industrial},
    {3, game::FloorKind::Derelict},
    {4, game::FloorKind::Residential},
};
constexpr int kDemoFloorCount =
    static_cast<int>(sizeof(kDemoFloors) / sizeof(kDemoFloors[0]));
constexpr int kMaxLayers = 16; // upper bound for the per-layer HUD lookup arrays

// Point the fresh player's camera somewhere interesting and start in fly mode
// (F toggles) so the view is free to explore.
void aim_player(Registry& reg, Entity player) {
    auto& cam = reg.get<CameraTag>(player);
    cam.yaw = 0.8f;
    cam.pitch = -0.5f;
    reg.get<Controller>(player).fly = true;
}

// Maze test bed: seed a plain crowd on one layer, pin the player to an open maze
// cell (the labyrinth has no apartment lattice), and return the player entity.
Entity setup_maze(game::NpcPool& pool, Registry& reg, LayerId layer) {
    game::NpcId playerId =
        game::seed_floor_population(pool, /*floor=*/0, /*n=*/64, /*seed=*/1337u);
    if (playerId == game::kInvalidNpc) return entt::null;

    vec3 mazeCell{30.0f, 30.0f, 90.0f};
    pool.cx(playerId) = static_cast<std::uint8_t>(mazeCell.x);
    pool.cy(playerId) = static_cast<std::uint8_t>(mazeCell.y);
    pool.cz(playerId) = static_cast<std::uint8_t>(mazeCell.z);

    Entity player = entt::null;
    for (game::NpcId id = 0; id < pool.count(); ++id) {
        if (!pool.alive(id)) continue;
        if (id == playerId)
            player = game::embody_as_player(reg, pool, id, layer);
        else
            game::embody(reg, pool, id, layer);
    }
    if (player != entt::null) aim_player(reg, player);
    return player;
}

// Populate one floor module: seed its crowd from the spec and embody exactly the
// freshly-allocated records onto `layer` (using the bump-allocated id range, so
// it never rescans the whole pool). Designates the player only when makePlayer.
Entity populate_module(game::NpcPool& pool, Registry& reg, LayerId layer,
                       int number, const game::FloorSpec& spec,
                       std::uint32_t seed, bool makePlayer) {
    game::NpcId before = pool.count();
    game::NpcId cand = game::seed_floor_from_spec(
        pool, static_cast<std::uint16_t>(number), spec, seed);
    if (cand == game::kInvalidNpc) return entt::null;
    game::NpcId after = pool.count();

    Entity player = entt::null;
    for (game::NpcId id = before; id < after; ++id) {
        if (!pool.alive(id)) continue;
        if (makePlayer && id == cand)
            player = game::embody_as_player(reg, pool, id, layer);
        else
            game::embody(reg, pool, id, layer);
    }
    if (makePlayer && player != entt::null) aim_player(reg, player);
    return player;
}

} // namespace

int main(int argc, char** argv) {
    // World select: `gigahrush2 maze` for the labyrinth test bed, otherwise the
    // floor-module stack (default).
    WorldGenMode genMode = WorldGenMode::FloorStack;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "maze") genMode = WorldGenMode::Maze;
        else if (a == "floors" || a == "stack") genMode = WorldGenMode::FloorStack;
    }

    if (!SDL_Init(SDL_INIT_VIDEO)) {
        std::fprintf(stderr, "SDL_Init: %s\n", SDL_GetError());
        return 1;
    }

    SDL_Window* window = SDL_CreateWindow(
        "gigahrush2 — voxel core", kWinW, kWinH,
        SDL_WINDOW_VULKAN | SDL_WINDOW_RESIZABLE);
    if (!window) {
        std::fprintf(stderr, "SDL_CreateWindow: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }

    gpu::VulkanDevice device;
#ifdef NDEBUG
    const bool wantValidation = false;
#else
    const bool wantValidation = true;
#endif
    if (!device.init(window, wantValidation)) {
        std::fprintf(stderr, "Vulkan device init failed\n");
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    gpu::VulkanRenderer renderer;
    if (!renderer.init(device, window)) {
        std::fprintf(stderr, "Renderer init failed\n");
        device.destroy();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    gpu::CubePass cubePass;
    if (!cubePass.init(device, renderer.renderPass, GIGA_SHADER_DIR)) {
        std::fprintf(stderr, "Cube pass init failed\n");
        renderer.destroy();
        device.destroy();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    // Draws the population: one instanced, lit box per embodied entity, sharing
    // the world pass's render pass + depth so bodies and voxels occlude cleanly.
    gpu::BodyPass bodyPass;
    if (!bodyPass.init(device, renderer.renderPass, GIGA_SHADER_DIR)) {
        std::fprintf(stderr, "Body pass init failed\n");
        cubePass.destroy();
        renderer.destroy();
        device.destroy();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    gpu::ImGuiLayer hud;
    if (!hud.init(device, window, renderer.renderPass,
                  static_cast<std::uint32_t>(renderer.swap().images.size()))) {
        std::fprintf(stderr, "ImGui init failed\n");
        bodyPass.destroy();
        cubePass.destroy();
        renderer.destroy();
        device.destroy();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    // --- World + ECS setup -------------------------------------------------
    // Build the world population-first, then embody the player from it ([npcs.md]).
    LevelStack stack;
    Registry reg;
    game::NpcPool pool;
    pool.init();
    game::FloorRegistry registry;

    // Per-layer lookup for the HUD (floor label + rule-set behind the active
    // layer). Indexed by LayerId; layer i is pushed for demo floor i.
    int layerFloorNumber[kMaxLayers] = {};
    const game::FloorSpec* layerSpec[kMaxLayers] = {};

    Entity player = entt::null;

    if (genMode == WorldGenMode::Maze) {
        LayerId ground = stack.push_layer();
        generate_demo_world(stack.layer(ground), 1337u, genMode);
        if (ground < kMaxLayers) {
            layerFloorNumber[ground] = 0;
            layerSpec[ground] = nullptr;
        }
        player = setup_maze(pool, reg, ground);
    } else {
        // One 128^3 module per demo floor: generate its themed geometry (#6),
        // register the number -> module -> layer chain, then populate + embody.
        for (int i = 0; i < kDemoFloorCount && i < kMaxLayers; ++i) {
            LayerId layer = stack.push_layer();
            const game::FloorSpec& spec = game::floor_spec(kDemoFloors[i].kind);
            // Vary the seed per floor so same-kind floors still differ.
            std::uint32_t fseed =
                1337u ^ (static_cast<std::uint32_t>(kDemoFloors[i].number) *
                         0x9e3779b9u);
            game::generate_floor(stack.layer(layer), kDemoFloors[i].number, spec,
                                 fseed);

            registry.assign(kDemoFloors[i].number,
                            static_cast<game::ModuleId>(i));
            registry.set_resident(static_cast<game::ModuleId>(i), layer);
            layerFloorNumber[layer] = kDemoFloors[i].number;
            layerSpec[layer] = &spec;

            const bool isStart = (i == 0);
            Entity p = populate_module(pool, reg, layer, kDemoFloors[i].number,
                                       spec, fseed ^ 0x51ed270bu, isStart);
            if (isStart) player = p;
        }
    }

    if (player == entt::null) {
        std::fprintf(stderr, "population seeding failed to embody a player\n");
        hud.destroy();
        bodyPass.destroy();
        cubePass.destroy();
        renderer.destroy();
        device.destroy();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    InputState input;
    // Start with mouse-look on so the camera rotates immediately. Tab toggles
    // it (freeing the cursor for the HUD); holding the right mouse button also
    // engages look while held.
    input.set_mouselook(true);
    SDL_SetWindowRelativeMouseMode(window, true);

    bool running = true;
    bool fluidPaused = false;
    float simAccum = 0.0f;
    std::uint64_t prevTicks = SDL_GetPerformanceCounter();
    const double freq = static_cast<double>(SDL_GetPerformanceFrequency());
    int fluidStepEvery = 4; // sim steps between fluid updates
    int fluidCounter = 0;

    while (running) {
        std::uint64_t now = SDL_GetPerformanceCounter();
        float frameDt = static_cast<float>((now - prevTicks) / freq);
        prevTicks = now;
        if (frameDt > 0.1f) frameDt = 0.1f; // clamp after a stall

        // --- events --------------------------------------------------------
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            hud.process_event(e);
            if (e.type == SDL_EVENT_QUIT) running = false;
            if (e.type == SDL_EVENT_KEY_DOWN && !e.key.repeat) {
                if (e.key.scancode == SDL_SCANCODE_ESCAPE) running = false;
                if (e.key.scancode == SDL_SCANCODE_TAB) {
                    bool on = !input.mouselook();
                    input.set_mouselook(on);
                    SDL_SetWindowRelativeMouseMode(window, on);
                }
                // Floor travel (#8): [ down a floor, ] up a floor. The real
                // elevator — fold the player's record back on the floor it
                // leaves and re-embody it on the destination, resolved through
                // the FloorRegistry by floor NUMBER (not raw layer). Cell z=2 is
                // air on the ground storey for every floor kind; the player keeps
                // x/y and fly mode frees them if boxed in. No-op at the ends of
                // the stack (destination floor not loaded).
                if (e.key.scancode == SDL_SCANCODE_LEFTBRACKET ||
                    e.key.scancode == SDL_SCANCODE_RIGHTBRACKET) {
                    const int dir =
                        e.key.scancode == SDL_SCANCODE_RIGHTBRACKET ? +1 : -1;
                    LayerId curLayer = reg.get<Transform>(player).layer;
                    int fromFloor =
                        curLayer < kMaxLayers ? layerFloorNumber[curLayer] : 0;
                    game::RideResult ride =
                        game::ride_elevator(reg, pool, registry, player,
                                            fromFloor, dir, /*arrivalZ=*/2);
                    if (ride.moved) player = ride.player;
                }
            }
            // Hold right mouse button to look, release to free the cursor.
            if (e.type == SDL_EVENT_MOUSE_BUTTON_DOWN &&
                e.button.button == SDL_BUTTON_RIGHT) {
                input.set_mouselook(true);
                SDL_SetWindowRelativeMouseMode(window, true);
            }
            if (e.type == SDL_EVENT_MOUSE_BUTTON_UP &&
                e.button.button == SDL_BUTTON_RIGHT) {
                input.set_mouselook(false);
                SDL_SetWindowRelativeMouseMode(window, false);
            }
            // Feed movement/look events unless the HUD wants the cursor (only
            // relevant when look is off — relative mode hides the cursor).
            if (input.mouselook() || !ImGui::GetIO().WantCaptureMouse)
                input.handle_event(e);
        }

        // The layer the player is currently on drives sim + render below.
        LayerId activeLayer = reg.get<Transform>(player).layer;

        // --- fixed-step simulation ----------------------------------------
        simAccum += frameDt;
        int guard = 0;
        while (simAccum >= kSimDt && guard++ < 8) {
            input.apply(reg, kSimDt);
            controller_step(reg, kSimDt);
            physics_step(reg, stack, kSimDt);
            // Fluid only lives in the maze test bed (the floor modules seed no
            // puddles yet); step it on the active layer there.
            if (genMode == WorldGenMode::Maze && !fluidPaused &&
                ++fluidCounter >= fluidStepEvery) {
                fluid_step(stack.layer(activeLayer));
                fluidCounter = 0;
            }
            simAccum -= kSimDt;
        }

        // --- render --------------------------------------------------------
        int fbw = 0, fbh = 0;
        SDL_GetWindowSizeInPixels(window, &fbw, &fbh);
        float aspect = fbh > 0 ? static_cast<float>(fbw) / fbh : 1.0f;
        CameraMatrices camMat = compute_camera(reg, aspect);

        hud.begin_frame();
        {
            ImGui::SetNextWindowPos(ImVec2(10, 10), ImGuiCond_FirstUseEver);
            ImGui::Begin("gigahrush2");
            ImGui::Text("%.1f FPS (%.2f ms)", frameDt > 0 ? 1.0f / frameDt : 0.0f,
                        frameDt * 1000.0f);
            auto& tr = reg.get<Transform>(player);
            auto& ctl = reg.get<Controller>(player);
            auto& ga = reg.get<GravityAffected>(player);
            ImGui::Text("pos  %.1f %.1f %.1f (layer %u)", tr.pos.x, tr.pos.y,
                        tr.pos.z, tr.layer);
            ImGui::Text("mode %s%s", ctl.fly ? "fly" : "walk",
                        ga.grounded ? " (grounded)" : "");
            ImGui::Text("instances drawn: %u / %zu cells",
                        cubePass.last_instance_count(), kMacroCells);
            ImGui::Text("bodies drawn: %u  (pop %u alive / %u slots)",
                        bodyPass.last_instance_count(), pool.count(),
                        pool.capacity());
            const game::FloorSpec* as =
                activeLayer < kMaxLayers ? layerSpec[activeLayer] : nullptr;
            int af = activeLayer < kMaxLayers ? layerFloorNumber[activeLayer] : 0;
            ImGui::Text("floor %d: %s (target pop %u)", af,
                        as ? as->name : "maze", as ? as->population : 64u);
            if (genMode == WorldGenMode::Maze) {
                ImGui::Checkbox("pause fluid", &fluidPaused);
                ImGui::SliderInt("fluid step every", &fluidStepEvery, 1, 30);
            }
            ImGui::TextUnformatted(
                "WASD move | mouse look | Tab toggle look | Space jump | "
                "F fly | [ / ] floor down/up | Esc quit");
            ImGui::End();
        }

        // Clear to black so fogged-out geometry blends into the void seamlessly
        // (fog fades to black at the toroidal render radius).
        if (renderer.begin_frame(window, 0.0f, 0.0f, 0.0f)) {
            VkCommandBuffer cmd = renderer.current_cmd();
            gpu::CubePush push{};
            push.viewProj = mat4_mul(camMat.proj, camMat.view);
            push.sunDir = vec4{0.4f, 0.3f, 0.85f, 0.0f};
            push.camPos = vec4{camMat.eye.x, camMat.eye.y, camMat.eye.z, 0.0f};
            // Fog fades to black between 0.30 and 0.50 of the torus period. The
            // end (kWorldExtent/2 = 64 cells) is the minimal-image radius, so
            // the wrap seam is always hidden inside full-black fog.
            push.fog = vec4{kWorldExtent * 0.30f, kWorldExtent * 0.50f, 0.0f, 0.0f};
            cubePass.record(cmd, renderer.currentFrame,
                            stack.layer(activeLayer), push);
            // Draw the embodied population on the active layer (shared depth).
            bodyPass.record(cmd, renderer.currentFrame, reg, activeLayer, push);
            hud.render(cmd);
            renderer.end_frame(window);
        }
    }

    // --- teardown (reverse order) -----------------------------------------
    hud.destroy();
    bodyPass.destroy();
    cubePass.destroy();
    renderer.destroy();
    device.destroy();
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
