// GENERATED by tools/gen_material_surface.py from data/materials.csv — do not
// hand-edit. Edit the CSV (or the authored rows in the generator) and re-run it;
// the `source_rules` ctest fails on drift.
//
// Included by shaders/cube.frag, which is shared by the world pass and the body
// pass. Nothing on the CPU reads this table.
//
// sigma is the lognormal width that reproduces each material's MEASURED luminance
// coefficient of variation (lum_std / mean luminance, both linear) through
// exp(sigma*n - sigma*sigma/2) — strictly positive, mean-preserving, and calibrated
// rather than tuned. See the generator's docstring for why the raw lum_std cannot be
// used as an amplitude and why the seam depths are authored instead of measured.

// Rows read from data/materials.csv. The `source_rules` ctest compares this
// against the CSV's data-row count, which is what catches a re-harvest that
// nobody regenerated against.
//
// NOTE this is NOT the material count. It happens to equal 16 today because the
// pack has 16 photographs and materials.h has 16 ids; they are unrelated
// numbers and only 6 of the 16 rows are consumed. Do not "simplify" the gate to
// compare against the array length instead.
const uint kMaterialCsvRows = 16u;

// Family per material id — see the kFam* constants in cube.frag.
//   0 air / body sentinel  generic  authored                 CV 0.0000
//     never drawn by the world pass; body.vert writes this id so bodies
//     keep the pre-existing look exactly
//   1 concrete (maze)      generic  authored                 CV 0.0000
//     maze test bed — left on the legacy path so app/worldgen.cpp renders
//     as it did
//   2 soil (maze)          generic  authored                 CV 0.0000
//     maze test bed
//   3 water marker (maze)  generic  authored                 CV 0.0000
//     maze test bed
//   4 tan slab (maze)      generic  authored                 CV 0.0000
//     maze test bed
//   5 extraction pad       smooth   authored                 CV 0.0300
//     the bank must stay unmistakable (materials.h) — a painted plate, no
//     seams, almost no mottle, so the emerald reads as signage and not as
//     a surface
//   6 unused               generic  authored                 CV 0.0000
//     no generator writes this id
//   7 nav / hub pad        smooth   authored                 CV 0.0300
//     as the extraction pad
//   8 plaster              plaster  authored                 CV 0.1300
//     AUTHORED: the pack has no plaster photograph. Dirty whitewash over
//     precast panel — clearly mottled, not blotchy. Broad stain blobs at
//     0.7 cycles/cell (~2.9 m) give one apartment a different wall from
//     the next
//   9 parquet              plank    authored                 CV 0.1100
//     AUTHORED: the pack has no wood photograph. Varnish is even within a
//     board; the visible variation is board-to-board tone, which the plank
//     family puts in structure rather than in noise. 20 cycles/cell = 10
//     cm boards
//  10 shop shutter         ribbed   painted_metal_shutter    CV 0.1519
//     roller-shutter slats, 28 cycles/cell = 7 cm
//  11 lino                 tile     rubber_tiles             CV 0.0724
//     the CSV role for this row is literally 'smooth dark waterproof
//     rubber with seams' — the seams are the character, the mottle is
//     nearly nil. 50 cm tiles
//  12 factory wall         ribbed   factory_wall             CV 0.2231
//     green corrugated factory metal. Coarser corrugation than a shutter,
//     15 cm, which is what keeps it distinguishable from id 10 beyond its
//     colour
//  13 tread plate          tread    metal_grate_rusty        CV 0.1940
//     walkway grate. 8 cycles/cell = 25 cm studs, coarser than the ~3 cm
//     of real chequer plate: at the range the headlamp lights, real pitch
//     is sub-pixel mush
//  14 rust                 rust     rusty_metal_03           CV 0.4411
//     render.md: real rust has long-range spatial correlation that FBM
//     reproduces badly, so the patches come from a THRESHOLDED
//     low-frequency field, not from another octave. 1.3 cycles/cell = ~1.5
//     m patches
//  15 rubble               rubble   rusty_corrugated_iron    CV 0.4437
//     measured amplitude is a hair above rust (0.4437 vs 0.4411 CV) so
//     amplitude alone cannot separate the two Derelict surfaces — the
//     family does it: chunk plateaus at 33 cm read as debris where rust
//     reads as staining
// Table length. cube.frag clamps the incoming material id against
// this, so a five-bit id the CPU should never emit cannot index
// past the arrays — an out-of-range const-array read is undefined
// in GLSL, which on an untestable driver means anything at all.
const uint kMatSurfaceCount = 16u;

const uint kMatFamily[16] = uint[16](
    0u,  //  0 air / body sentinel
    0u,  //  1 concrete (maze)
    0u,  //  2 soil (maze)
    0u,  //  3 water marker (maze)
    0u,  //  4 tan slab (maze)
    8u,  //  5 extraction pad
    0u,  //  6 unused
    8u,  //  7 nav / hub pad
    1u,  //  8 plaster
    2u,  //  9 parquet
    4u,  // 10 shop shutter
    3u,  // 11 lino
    4u,  // 12 factory wall
    5u,  // 13 tread plate
    6u,  // 14 rust
    7u   // 15 rubble
);

// x = lognormal sigma reproducing the measured luminance CV,
// y = the family's structural pitch in cycles per 2 m cell.
const vec2 kMatSurface[16] = vec2[16](
    vec2(0.00000,   0.00),  //  0 air / body sentinel
    vec2(0.00000,   0.00),  //  1 concrete (maze)
    vec2(0.00000,   0.00),  //  2 soil (maze)
    vec2(0.00000,   0.00),  //  3 water marker (maze)
    vec2(0.00000,   0.00),  //  4 tan slab (maze)
    vec2(0.02999,   0.00),  //  5 extraction pad
    vec2(0.00000,   0.00),  //  6 unused
    vec2(0.02999,   0.00),  //  7 nav / hub pad
    vec2(0.12946,   0.70),  //  8 plaster
    vec2(0.10967,  20.00),  //  9 parquet
    vec2(0.15105,  28.00),  // 10 shop shutter
    vec2(0.07232,   4.00),  // 11 lino
    vec2(0.22041,  13.00),  // 12 factory wall
    vec2(0.19217,   8.00),  // 13 tread plate
    vec2(0.42165,   1.30),  // 14 rust
    vec2(0.42390,   6.00)   // 15 rubble
);
