// GENERATED by tools/gen_material_table.py from data/materials.csv — do not
// hand-edit. Edit the CSV and re-run it; the `source_rules` ctest fails on drift.
//
// Included by shaders/cube.frag, which is shared by the world pass and the body
// pass. Nothing on the CPU reads this table.
//
// sigma is the lognormal width that reproduces each material's MEASURED luminance
// coefficient of variation (lum_std / mean luminance, both linear) through
// exp(sigma*n - sigma*sigma/2) — strictly positive, mean-preserving, and calibrated
// rather than tuned. Amplitudes derive from data/textures.csv's measured stats when
// a material binds a texture and leaves `cv` blank; the seam/groove DEPTHS are
// authored per family in cube.frag (the CSV measured colour, not depth).

// Rows read from data/materials.csv. The `source_rules` ctest compares it
// against the CSV's data-row count; derived rubble twins live PAST this count
// (kMatCount covers all, see materials.h).
const uint kMaterialCsvRows = 26u;

// Family per material id — see the kFam* constants in cube.frag.
//   0 air                  generic  authored                 CV 0.0000
//     never drawn by the world pass; body.vert writes this id so bodies
//     keep the pre-existing look; референс среды: flow/diffusion 1.0 =
//     воздух уступает место и выравнивается за один подтик — единица шкалы
//   1 concrete             smooth   authored                 CV 0.0800
//     aged Soviet panel concrete; poured smooth, no panel seams
//   2 soil                 smooth   authored                 CV 0.2200
//     organic earth / soil mottle
//   3 water                generic  authored                 CV 0.0000
//     вода — настоящая материя автомата (S16); референс текучести: flow
//     1.0 при вязкости 1 мПа·с — flow прочих жидкостей =
//     вязкость_воды/вязкость; имя water_mark умерло с инкр. 2; diffusion
//     0.5 = самовыравнивание лужи: латеральный случайный шаг p*a^2*f/4 =
//     0.5*0.0625*31.25/4 = 0.24 м2/с — фронт метра за ~4 с; у жиж
//     diffusion = flow*0.5
//   4 slab_tan             smooth   authored                 CV 0.0600
//     muted tan concrete slab
//   5 extract              smooth   authored                 CV 0.0300
//     the bank pad: signage, not surface — unbreakable infrastructure
//   6 door                 generic  authored                 CV 0.0000
//     door leaf + frame; carve-immune, owned by the door state machine
//   7 hub_pad              smooth   authored                 CV 0.0300
//     nav / fast-travel pad: lattice ground truth, unbreakable
//   8 plaster              plaster  authored                 CV 0.1300
//     AUTHORED: dirty whitewash over precast panel; broad stains ~2.9 m
//   9 parquet              plank    authored                 CV 0.1100
//     AUTHORED: varnished oak, board-to-board tone; 10 cm boards
//  10 shop_shutter         ribbed   painted_metal_shutter    CV 0.1519
//     roller-shutter slats, 7 cm
//  11 lino                 tile     rubber_tiles             CV 0.0724
//     dark rubber with seams; 50 cm tiles
//  12 factory_wall         ribbed   factory_wall             CV 0.2231
//     green corrugated factory metal, 15 cm corrugation
//  13 tread                tread    metal_grate_rusty        CV 0.1940
//     walkway grate, 25 cm studs
//  14 rust                 rust     rusty_metal_03           CV 0.4411
//     thresholded low-frequency patches ~1.5 m; corroded, weaker than
//     fresh steel
//  15 rubble               rubble   rusty_corrugated_iron    CV 0.4437
//     chunk plateaus at 33 cm; already broken once; рыхлое: flow 0.1 из
//     угла естественного откоса щебня ~40° — (45−40)/45 ≈ 0.1 бокового
//     растекания при осыпании
//  16 electric_grate       tread    authored                 CV 0.0900
//     AUTHORED: electrified floor grate — tread lattice, hot hazard tint
//  17 acid_pool            smooth   authored                 CV 0.1000
//     AUTHORED: caustic pool surface, broad slicks; жижа ~10 мПа·с → flow
//     = вязкость_воды/вязкость = 0.1
//  18 fire_cell            smooth   authored                 CV 0.1500
//     AUTHORED: burning floor cell
//  19 pipe_metal           ribbed   authored                 CV 0.1000
//     AUTHORED: baked wall-pipe runs (antourage) — painted steel conduit,
//     dents and joint rings
//  20 neon_tube            smooth   authored                 CV 0.0400
//     неоновая трубка — светоматериал: лепи вывески/лампы вокселями, бейк
//     кластеризует в эмиттеры (ddalight.md)
//  21 glass                smooth   authored                 CV 0.0300
//     стекло — первый потребитель колонки прозрачности: свет проходит
//     (light_transparent), материя стоит; решение владельца 2026-08-24
//     (neon-topology.md)
//  22 toxic_gas            generic  authored                 CV 0.0000
//     удушливый газ шахт — МАТЕРИЯ автомата (S16): плотность хлора ~3
//     кг/м³ при табличном воздухе 0 — тонет и стелется по полу; diffusion
//     0.5 = тяжёлый газ ползёт вдвое медленней воздуха-референса;
//     твёрдость 0 — рассеивается любым касанием карва; свету не преграда
//  23 asphalt              smooth   authored                 CV 0.1000
//     AUTHORED: дорожное полотно хрущей — тёмный асфальт с широкими
//     латками; твёрдость 224 между slab_tan 192 и concrete 256: битум
//     мягче чистого бетона, полотно уплотнено катком; плотность
//     асфальтобетона ~2300
//  24 door_steel           smooth   authored                 CV 0.0600
//     НОВАЯ ДВЕРЬ 2026-08-28: стальное полотно квартирной двери —
//     настоящая материя мира (дверь = зарастание проёма субвокселями);
//     твёрдость 384 между бетоном 256 и unbreakable: полотно ломается
//     упорным карвом, но дольше стены; плотность стали листовой с рёбрами
//     ~2900
//  25 door_hermetic        smooth   authored                 CV 0.0500
//     НОВАЯ ДВЕРЬ 2026-08-28: гермополотно — неразрушимый материал
//     (hardness 65535 = kHardnessUnbreakable, тот же закон, что
//     extract/hub_pad): гермодверь неразрушима ЕСТЕСТВЕННО, свойством
//     материи, без спец-флагов; модуль сам решает, какой комнате гермо
//  26 rubble_concrete      smooth   authored                 CV 0.0800
//     ВЫВЕДЕННЫЙ рыхлый двойник строки concrete — детач меняет строку,
//     автомат роняет; вид исходника
//  27 rubble_soil          smooth   authored                 CV 0.2200
//     ВЫВЕДЕННЫЙ рыхлый двойник строки soil — детач меняет строку, автомат
//     роняет; вид исходника
//  28 rubble_slab_tan      smooth   authored                 CV 0.0600
//     ВЫВЕДЕННЫЙ рыхлый двойник строки slab_tan — детач меняет строку,
//     автомат роняет; вид исходника
//  29 rubble_plaster       plaster  authored                 CV 0.1300
//     ВЫВЕДЕННЫЙ рыхлый двойник строки plaster — детач меняет строку,
//     автомат роняет; вид исходника
//  30 rubble_parquet       plank    authored                 CV 0.1100
//     ВЫВЕДЕННЫЙ рыхлый двойник строки parquet — детач меняет строку,
//     автомат роняет; вид исходника
//  31 rubble_shop_shutter  ribbed   painted_metal_shutter    CV 0.1519
//     ВЫВЕДЕННЫЙ рыхлый двойник строки shop_shutter — детач меняет строку,
//     автомат роняет; вид исходника
//  32 rubble_lino          tile     rubber_tiles             CV 0.0724
//     ВЫВЕДЕННЫЙ рыхлый двойник строки lino — детач меняет строку, автомат
//     роняет; вид исходника
//  33 rubble_factory_wall  ribbed   factory_wall             CV 0.2231
//     ВЫВЕДЕННЫЙ рыхлый двойник строки factory_wall — детач меняет строку,
//     автомат роняет; вид исходника
//  34 rubble_tread         tread    metal_grate_rusty        CV 0.1940
//     ВЫВЕДЕННЫЙ рыхлый двойник строки tread — детач меняет строку,
//     автомат роняет; вид исходника
//  35 rubble_rust          rust     rusty_metal_03           CV 0.4411
//     ВЫВЕДЕННЫЙ рыхлый двойник строки rust — детач меняет строку, автомат
//     роняет; вид исходника
//  36 rubble_electric_grate tread    authored                 CV 0.0900
//     ВЫВЕДЕННЫЙ рыхлый двойник строки electric_grate — детач меняет
//     строку, автомат роняет; вид исходника
//  37 rubble_fire_cell     smooth   authored                 CV 0.1500
//     ВЫВЕДЕННЫЙ рыхлый двойник строки fire_cell — детач меняет строку,
//     автомат роняет; вид исходника
//  38 rubble_pipe_metal    ribbed   authored                 CV 0.1000
//     ВЫВЕДЕННЫЙ рыхлый двойник строки pipe_metal — детач меняет строку,
//     автомат роняет; вид исходника
//  39 rubble_neon_tube     smooth   authored                 CV 0.0400
//     ВЫВЕДЕННЫЙ рыхлый двойник строки neon_tube — детач меняет строку,
//     автомат роняет; вид исходника
//  40 rubble_glass         smooth   authored                 CV 0.0300
//     ВЫВЕДЕННЫЙ рыхлый двойник строки glass — детач меняет строку,
//     автомат роняет; вид исходника
//  41 rubble_asphalt       smooth   authored                 CV 0.1000
//     ВЫВЕДЕННЫЙ рыхлый двойник строки asphalt — детач меняет строку,
//     автомат роняет; вид исходника
//  42 rubble_door_steel    smooth   authored                 CV 0.0600
//     ВЫВЕДЕННЫЙ рыхлый двойник строки door_steel — детач меняет строку,
//     автомат роняет; вид исходника
// Table length. cube.frag clamps the incoming material id against
// this, so an id the CPU should never emit cannot index past the
// arrays — an out-of-range const-array read is undefined in GLSL.
const uint kMatSurfaceCount = 43u;

const uint kMatFamily[43] = uint[43](
    0u,  //  0 air
    8u,  //  1 concrete
    8u,  //  2 soil
    0u,  //  3 water
    8u,  //  4 slab_tan
    8u,  //  5 extract
    0u,  //  6 door
    8u,  //  7 hub_pad
    1u,  //  8 plaster
    2u,  //  9 parquet
    4u,  // 10 shop_shutter
    3u,  // 11 lino
    4u,  // 12 factory_wall
    5u,  // 13 tread
    6u,  // 14 rust
    7u,  // 15 rubble
    5u,  // 16 electric_grate
    8u,  // 17 acid_pool
    8u,  // 18 fire_cell
    4u,  // 19 pipe_metal
    8u,  // 20 neon_tube
    8u,  // 21 glass
    0u,  // 22 toxic_gas
    8u,  // 23 asphalt
    8u,  // 24 door_steel
    8u,  // 25 door_hermetic
    8u,  // 26 rubble_concrete
    8u,  // 27 rubble_soil
    8u,  // 28 rubble_slab_tan
    1u,  // 29 rubble_plaster
    2u,  // 30 rubble_parquet
    4u,  // 31 rubble_shop_shutter
    3u,  // 32 rubble_lino
    4u,  // 33 rubble_factory_wall
    5u,  // 34 rubble_tread
    6u,  // 35 rubble_rust
    5u,  // 36 rubble_electric_grate
    8u,  // 37 rubble_fire_cell
    4u,  // 38 rubble_pipe_metal
    8u,  // 39 rubble_neon_tube
    8u,  // 40 rubble_glass
    8u,  // 41 rubble_asphalt
    8u   // 42 rubble_door_steel
);

// x = lognormal sigma reproducing measured luminance CV,
// y = structural pitch in cycles per 2 m cell,
// z = chroma_sigma (lognormal chroma width),
// w = bump_scale (normal perturbation scale).
const vec4 kMatSurface[43] = vec4[43](
    vec4(0.00000,   0.00, 0.00000, 0.00000),  //  0 air
    vec4(0.07987,   1.00, 0.03000, 0.04000),  //  1 concrete
    vec4(0.21741,   0.80, 0.12000, 0.10000),  //  2 soil
    vec4(0.00000,   0.00, 0.00000, 0.00000),  //  3 water
    vec4(0.05995,   1.00, 0.04000, 0.03000),  //  4 slab_tan
    vec4(0.02999,   0.00, 0.00000, 0.02000),  //  5 extract
    vec4(0.00000,   0.00, 0.00000, 0.00000),  //  6 door
    vec4(0.02999,   0.00, 0.00000, 0.02000),  //  7 hub_pad
    vec4(0.12946,   0.70, 0.08000, 0.12000),  //  8 plaster
    vec4(0.10967,  20.00, 0.07000, 0.18000),  //  9 parquet
    vec4(0.15105,  28.00, 0.05000, 0.40000),  // 10 shop_shutter
    vec4(0.07232,   4.00, 0.04000, 0.20000),  // 11 lino
    vec4(0.22041,  13.00, 0.08000, 0.35000),  // 12 factory_wall
    vec4(0.19217,   8.00, 0.09000, 0.30000),  // 13 tread
    vec4(0.42165,   1.30, 0.18000, 0.25000),  // 14 rust
    vec4(0.42390,   6.00, 0.15000, 0.35000),  // 15 rubble
    vec4(0.08982,   8.00, 0.06000, 0.30000),  // 16 electric_grate
    vec4(0.09975,   0.80, 0.10000, 0.05000),  // 17 acid_pool
    vec4(0.14917,   1.20, 0.12000, 0.05000),  // 18 fire_cell
    vec4(0.09975,  10.00, 0.06000, 0.30000),  // 19 pipe_metal
    vec4(0.03998,   0.00, 0.00000, 0.00000),  // 20 neon_tube
    vec4(0.02999,   1.00, 0.02000, 0.02000),  // 21 glass
    vec4(0.00000,   0.00, 0.00000, 0.00000),  // 22 toxic_gas
    vec4(0.09975,   1.10, 0.03000, 0.06000),  // 23 asphalt
    vec4(0.05995,   1.00, 0.02000, 0.05000),  // 24 door_steel
    vec4(0.04997,   1.00, 0.02000, 0.04000),  // 25 door_hermetic
    vec4(0.07987,   1.00, 0.03000, 0.04000),  // 26 rubble_concrete
    vec4(0.21741,   0.80, 0.12000, 0.10000),  // 27 rubble_soil
    vec4(0.05995,   1.00, 0.04000, 0.03000),  // 28 rubble_slab_tan
    vec4(0.12946,   0.70, 0.08000, 0.12000),  // 29 rubble_plaster
    vec4(0.10967,  20.00, 0.07000, 0.18000),  // 30 rubble_parquet
    vec4(0.15105,  28.00, 0.05000, 0.40000),  // 31 rubble_shop_shutter
    vec4(0.07232,   4.00, 0.04000, 0.20000),  // 32 rubble_lino
    vec4(0.22041,  13.00, 0.08000, 0.35000),  // 33 rubble_factory_wall
    vec4(0.19217,   8.00, 0.09000, 0.30000),  // 34 rubble_tread
    vec4(0.42165,   1.30, 0.18000, 0.25000),  // 35 rubble_rust
    vec4(0.08982,   8.00, 0.06000, 0.30000),  // 36 rubble_electric_grate
    vec4(0.14917,   1.20, 0.12000, 0.05000),  // 37 rubble_fire_cell
    vec4(0.09975,  10.00, 0.06000, 0.30000),  // 38 rubble_pipe_metal
    vec4(0.03998,   0.00, 0.00000, 0.00000),  // 39 rubble_neon_tube
    vec4(0.02999,   1.00, 0.02000, 0.02000),  // 40 rubble_glass
    vec4(0.09975,   1.10, 0.03000, 0.06000),  // 41 rubble_asphalt
    vec4(0.05995,   1.00, 0.02000, 0.05000)   // 42 rubble_door_steel
);

// RGB chroma tint axis per material id.
const vec3 kMatChromaAxis[43] = vec3[43](
    vec3(1.00000, 1.00000, 1.00000),  //  0 air
    vec3(1.00000, 1.00000, 1.00000),  //  1 concrete
    vec3(1.15000, 0.90000, 0.65000),  //  2 soil
    vec3(1.00000, 1.00000, 1.00000),  //  3 water
    vec3(1.05000, 0.95000, 0.85000),  //  4 slab_tan
    vec3(1.00000, 1.00000, 1.00000),  //  5 extract
    vec3(1.00000, 1.00000, 1.00000),  //  6 door
    vec3(1.00000, 1.00000, 1.00000),  //  7 hub_pad
    vec3(1.10000, 1.00000, 0.70000),  //  8 plaster
    vec3(1.15000, 0.95000, 0.75000),  //  9 parquet
    vec3(0.90000, 0.95000, 1.10000),  // 10 shop_shutter
    vec3(0.95000, 1.05000, 0.90000),  // 11 lino
    vec3(0.85000, 1.15000, 0.80000),  // 12 factory_wall
    vec3(1.15000, 0.85000, 0.65000),  // 13 tread
    vec3(1.25000, 0.60000, 0.20000),  // 14 rust
    vec3(1.10000, 0.90000, 0.70000),  // 15 rubble
    vec3(1.10000, 1.00000, 0.60000),  // 16 electric_grate
    vec3(0.80000, 1.20000, 0.70000),  // 17 acid_pool
    vec3(1.25000, 0.85000, 0.50000),  // 18 fire_cell
    vec3(0.95000, 1.00000, 1.05000),  // 19 pipe_metal
    vec3(1.00000, 1.00000, 1.00000),  // 20 neon_tube
    vec3(1.00000, 1.00000, 1.00000),  // 21 glass
    vec3(1.00000, 1.00000, 1.00000),  // 22 toxic_gas
    vec3(1.00000, 1.00000, 1.00000),  // 23 asphalt
    vec3(1.00000, 1.00000, 1.00000),  // 24 door_steel
    vec3(1.00000, 1.00000, 1.00000),  // 25 door_hermetic
    vec3(1.00000, 1.00000, 1.00000),  // 26 rubble_concrete
    vec3(1.15000, 0.90000, 0.65000),  // 27 rubble_soil
    vec3(1.05000, 0.95000, 0.85000),  // 28 rubble_slab_tan
    vec3(1.10000, 1.00000, 0.70000),  // 29 rubble_plaster
    vec3(1.15000, 0.95000, 0.75000),  // 30 rubble_parquet
    vec3(0.90000, 0.95000, 1.10000),  // 31 rubble_shop_shutter
    vec3(0.95000, 1.05000, 0.90000),  // 32 rubble_lino
    vec3(0.85000, 1.15000, 0.80000),  // 33 rubble_factory_wall
    vec3(1.15000, 0.85000, 0.65000),  // 34 rubble_tread
    vec3(1.25000, 0.60000, 0.20000),  // 35 rubble_rust
    vec3(1.10000, 1.00000, 0.60000),  // 36 rubble_electric_grate
    vec3(1.25000, 0.85000, 0.50000),  // 37 rubble_fire_cell
    vec3(0.95000, 1.00000, 1.05000),  // 38 rubble_pipe_metal
    vec3(1.00000, 1.00000, 1.00000),  // 39 rubble_neon_tube
    vec3(1.00000, 1.00000, 1.00000),  // 40 rubble_glass
    vec3(1.00000, 1.00000, 1.00000),  // 41 rubble_asphalt
    vec3(1.00000, 1.00000, 1.00000)   // 42 rubble_door_steel
);

// Самосвечение поверхности (albedo * kMatEmissive): нарисованный
// светоматериал читается источником даже в полной тьме; сам СВЕТ
// от него в сетку кладёт бейк этажа ([ddalight.md]).
const float kMatEmissive[43] = float[43](
    0.000,  //  0 air
    0.000,  //  1 concrete
    0.000,  //  2 soil
    0.000,  //  3 water
    0.000,  //  4 slab_tan
    0.000,  //  5 extract
    0.000,  //  6 door
    0.000,  //  7 hub_pad
    0.000,  //  8 plaster
    0.000,  //  9 parquet
    0.000,  // 10 shop_shutter
    0.000,  // 11 lino
    0.000,  // 12 factory_wall
    0.000,  // 13 tread
    0.000,  // 14 rust
    0.000,  // 15 rubble
    0.000,  // 16 electric_grate
    0.000,  // 17 acid_pool
    0.000,  // 18 fire_cell
    0.000,  // 19 pipe_metal
    1.600,  // 20 neon_tube
    0.000,  // 21 glass
    0.000,  // 22 toxic_gas
    0.000,  // 23 asphalt
    0.000,  // 24 door_steel
    0.000,  // 25 door_hermetic
    0.000,  // 26 rubble_concrete
    0.000,  // 27 rubble_soil
    0.000,  // 28 rubble_slab_tan
    0.000,  // 29 rubble_plaster
    0.000,  // 30 rubble_parquet
    0.000,  // 31 rubble_shop_shutter
    0.000,  // 32 rubble_lino
    0.000,  // 33 rubble_factory_wall
    0.000,  // 34 rubble_tread
    0.000,  // 35 rubble_rust
    0.000,  // 36 rubble_electric_grate
    0.000,  // 37 rubble_fire_cell
    0.000,  // 38 rubble_pipe_metal
    0.000,  // 39 rubble_neon_tube
    0.000,  // 40 rubble_glass
    0.000,  // 41 rubble_asphalt
    0.000   // 42 rubble_door_steel
);

// ПРОЗРАЧНОСТЬ ДЛЯ СВЕТА (light_transparent + выведенные
// воздух/эмиттеры): теневой луч прощает субвоксель
// прозрачного материала. Тот же закон на CPU —
// material_passes_light ([world/material_props.h]).
const uint kMatLightPass[43] = uint[43](
    1u,  //  0 air
    0u,  //  1 concrete
    0u,  //  2 soil
    0u,  //  3 water
    0u,  //  4 slab_tan
    0u,  //  5 extract
    0u,  //  6 door
    0u,  //  7 hub_pad
    0u,  //  8 plaster
    0u,  //  9 parquet
    0u,  // 10 shop_shutter
    0u,  // 11 lino
    0u,  // 12 factory_wall
    0u,  // 13 tread
    0u,  // 14 rust
    0u,  // 15 rubble
    0u,  // 16 electric_grate
    0u,  // 17 acid_pool
    0u,  // 18 fire_cell
    0u,  // 19 pipe_metal
    1u,  // 20 neon_tube
    1u,  // 21 glass
    1u,  // 22 toxic_gas
    0u,  // 23 asphalt
    0u,  // 24 door_steel
    0u,  // 25 door_hermetic
    0u,  // 26 rubble_concrete
    0u,  // 27 rubble_soil
    0u,  // 28 rubble_slab_tan
    0u,  // 29 rubble_plaster
    0u,  // 30 rubble_parquet
    0u,  // 31 rubble_shop_shutter
    0u,  // 32 rubble_lino
    0u,  // 33 rubble_factory_wall
    0u,  // 34 rubble_tread
    0u,  // 35 rubble_rust
    0u,  // 36 rubble_electric_grate
    0u,  // 37 rubble_fire_cell
    0u,  // 38 rubble_pipe_metal
    0u,  // 39 rubble_neon_tube
    0u,  // 40 rubble_glass
    0u,  // 41 rubble_asphalt
    0u   // 42 rubble_door_steel
);

// СРЕДЫ (CANON S16): x = flow (0 = твёрдое, 1 = вода),
// y = diffusion (газы; 1 = воздух), z = шанс истаивания
// ОДИНОЧКИ на подтик (закон 2026-08-25: атом без своего
// материала в блоке — брызг, тает; шанс обратен массе
// кванта, калибровка — одиночный квант газа живёт ~1 с).
// Читатель — автомат материи; движение НЕ читает kMatPhase
// (метка для геймплейных предикатов — S16.2).
const vec3 kMatMedium[43] = vec3[43](
    vec3(1.000, 1.000, 0.000000),  //  0 air
    vec3(0.000, 0.000, 0.000000),  //  1 concrete
    vec3(0.000, 0.000, 0.000000),  //  2 soil
    vec3(1.000, 0.500, 0.000960),  //  3 water
    vec3(0.000, 0.000, 0.000000),  //  4 slab_tan
    vec3(0.000, 0.000, 0.000000),  //  5 extract
    vec3(0.000, 0.000, 0.000000),  //  6 door
    vec3(0.000, 0.000, 0.000000),  //  7 hub_pad
    vec3(0.000, 0.000, 0.000000),  //  8 plaster
    vec3(0.000, 0.000, 0.000000),  //  9 parquet
    vec3(0.000, 0.000, 0.000000),  // 10 shop_shutter
    vec3(0.000, 0.000, 0.000000),  // 11 lino
    vec3(0.000, 0.000, 0.000000),  // 12 factory_wall
    vec3(0.000, 0.000, 0.000000),  // 13 tread
    vec3(0.000, 0.000, 0.000000),  // 14 rust
    vec3(0.100, 0.000, 0.000533),  // 15 rubble
    vec3(0.000, 0.000, 0.000000),  // 16 electric_grate
    vec3(0.100, 0.050, 0.000873),  // 17 acid_pool
    vec3(0.000, 0.000, 0.000000),  // 18 fire_cell
    vec3(0.000, 0.000, 0.000000),  // 19 pipe_metal
    vec3(0.000, 0.000, 0.000000),  // 20 neon_tube
    vec3(0.000, 0.000, 0.000000),  // 21 glass
    vec3(0.000, 0.500, 0.031250),  // 22 toxic_gas
    vec3(0.000, 0.000, 0.000000),  // 23 asphalt
    vec3(0.000, 0.000, 0.000000),  // 24 door_steel
    vec3(0.000, 0.000, 0.000000),  // 25 door_hermetic
    vec3(0.100, 0.000, 0.000533),  // 26 rubble_concrete
    vec3(0.100, 0.000, 0.000800),  // 27 rubble_soil
    vec3(0.100, 0.000, 0.000582),  // 28 rubble_slab_tan
    vec3(0.100, 0.000, 0.001600),  // 29 rubble_plaster
    vec3(0.100, 0.000, 0.001829),  // 30 rubble_parquet
    vec3(0.100, 0.000, 0.000164),  // 31 rubble_shop_shutter
    vec3(0.100, 0.000, 0.001067),  // 32 rubble_lino
    vec3(0.100, 0.000, 0.000164),  // 33 rubble_factory_wall
    vec3(0.100, 0.000, 0.000164),  // 34 rubble_tread
    vec3(0.100, 0.000, 0.000246),  // 35 rubble_rust
    vec3(0.100, 0.000, 0.000164),  // 36 rubble_electric_grate
    vec3(0.100, 0.000, 0.006400),  // 37 rubble_fire_cell
    vec3(0.100, 0.000, 0.000164),  // 38 rubble_pipe_metal
    vec3(0.100, 0.000, 0.000914),  // 39 rubble_neon_tube
    vec3(0.100, 0.000, 0.000512),  // 40 rubble_glass
    vec3(0.100, 0.000, 0.000557),  // 41 rubble_asphalt
    vec3(0.100, 0.000, 0.000441)   // 42 rubble_door_steel
);

const uint kMatPhase[43] = uint[43](
    2u,  //  0 air
    0u,  //  1 concrete
    0u,  //  2 soil
    1u,  //  3 water
    0u,  //  4 slab_tan
    0u,  //  5 extract
    0u,  //  6 door
    0u,  //  7 hub_pad
    0u,  //  8 plaster
    0u,  //  9 parquet
    0u,  // 10 shop_shutter
    0u,  // 11 lino
    0u,  // 12 factory_wall
    0u,  // 13 tread
    0u,  // 14 rust
    0u,  // 15 rubble
    0u,  // 16 electric_grate
    1u,  // 17 acid_pool
    0u,  // 18 fire_cell
    0u,  // 19 pipe_metal
    0u,  // 20 neon_tube
    0u,  // 21 glass
    2u,  // 22 toxic_gas
    0u,  // 23 asphalt
    0u,  // 24 door_steel
    0u,  // 25 door_hermetic
    0u,  // 26 rubble_concrete
    0u,  // 27 rubble_soil
    0u,  // 28 rubble_slab_tan
    0u,  // 29 rubble_plaster
    0u,  // 30 rubble_parquet
    0u,  // 31 rubble_shop_shutter
    0u,  // 32 rubble_lino
    0u,  // 33 rubble_factory_wall
    0u,  // 34 rubble_tread
    0u,  // 35 rubble_rust
    0u,  // 36 rubble_electric_grate
    0u,  // 37 rubble_fire_cell
    0u,  // 38 rubble_pipe_metal
    0u,  // 39 rubble_neon_tube
    0u,  // 40 rubble_glass
    0u,  // 41 rubble_asphalt
    0u   // 42 rubble_door_steel
);

// Плотность кг/м³ — третий параметр движения материи
// (CANON S16.2: тяжелее — тонет, легче — всплывает).
// Зеркало kMatDensity [world/material_props.h].
const float kMatDensity[43] = float[43](
    0.0   ,  //  0 air
    2400.0,  //  1 concrete
    1600.0,  //  2 soil
    1000.0,  //  3 water
    2200.0,  //  4 slab_tan
    2400.0,  //  5 extract
    7800.0,  //  6 door
    2400.0,  //  7 hub_pad
    800.0 ,  //  8 plaster
    700.0 ,  //  9 parquet
    7800.0,  // 10 shop_shutter
    1200.0,  // 11 lino
    7800.0,  // 12 factory_wall
    7800.0,  // 13 tread
    5200.0,  // 14 rust
    1800.0,  // 15 rubble
    7800.0,  // 16 electric_grate
    1100.0,  // 17 acid_pool
    200.0 ,  // 18 fire_cell
    7800.0,  // 19 pipe_metal
    1400.0,  // 20 neon_tube
    2500.0,  // 21 glass
    3.0   ,  // 22 toxic_gas
    2300.0,  // 23 asphalt
    2900.0,  // 24 door_steel
    7800.0,  // 25 door_hermetic
    1800.0,  // 26 rubble_concrete
    1200.0,  // 27 rubble_soil
    1650.0,  // 28 rubble_slab_tan
    600.0 ,  // 29 rubble_plaster
    525.0 ,  // 30 rubble_parquet
    5850.0,  // 31 rubble_shop_shutter
    900.0 ,  // 32 rubble_lino
    5850.0,  // 33 rubble_factory_wall
    5850.0,  // 34 rubble_tread
    3900.0,  // 35 rubble_rust
    5850.0,  // 36 rubble_electric_grate
    150.0 ,  // 37 rubble_fire_cell
    5850.0,  // 38 rubble_pipe_metal
    1050.0,  // 39 rubble_neon_tube
    1875.0,  // 40 rubble_glass
    1725.0,  // 41 rubble_asphalt
    2175.0   // 42 rubble_door_steel
);
