#!/usr/bin/env python3
"""Generate src/game/verb_table.h from data/verbs.csv.

THE VERB VOCABULARY (CANON S12.2-S12.3): one table of verbs is the shared
language of five tables — what a prop PROVIDES, what an item SATISFIES, what a
room OFFERS, what an agent WANTS, and what a deed IS (S19). K — the vector
length every one of them speaks — comes from this CSV's row count and exists
nowhere in code as a literal; that is the whole point (rooms-object gate A).

Same contract as gen_status_table.py / gen_material_table.py: the CSV is the
truth, the generated header is committed so the build needs no Python, an
unknown/duplicate token is a hard error, and the `source_rules` ctest compares
the CSV row count against kVerbCount.

Ids are the CSV row order and STABLE BY CONTRACT: agent demand vectors and room
declarations will be saved keyed on these ordinals, so a new verb is appended,
never inserted (same law as materials.csv).

PATIENCE (CANON S13.5): one number 0..1 per verb, stored x1000 (`_e3`) —
integer, because this tree pins bit-exact digests and a float chain is not
identical between MSVC and Clang (same rationale as status_table). From it the
urgency threshold is DERIVED (reference formula: 58 + p*42); no list of
"emergency intents" exists anywhere.

    python tools/gen_verb_table.py
"""

import csv
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERBS_CSV = os.path.join(REPO, "data", "verbs.csv")
OUT_PATH = os.path.join(REPO, "src", "game", "verb_table.h")

EXPECTED_COLS = ["id", "name", "patience_e3", "rel_delta", "rep_delta",
                 "turf_mult_e3", "victim_mult_e3", "hear_m", "note"]


def die(msg):
    sys.stderr.write("gen_verb_table: %s\n" % msg)
    sys.exit(1)


def camel(ident):
    return "".join(p.capitalize() for p in ident.split("_"))


def main():
    with open(VERBS_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != EXPECTED_COLS:
            die("verbs.csv columns %r != expected %r" % (reader.fieldnames, EXPECTED_COLS))
        rows = list(reader)
    if not rows:
        die("verbs.csv has no data rows")

    seen = set()
    for row in rows:
        vid = (row["id"] or "").strip()
        if not re.fullmatch(r"[a-z][a-z0-9_]*", vid):
            die("bad id %r — lowercase snake_case only" % vid)
        if vid in seen:
            die("duplicate id %r — a silent overwrite is exactly the bug "
                "the vocabulary exists to prevent" % vid)
        seen.add(vid)
        if not (row["name"] or "").strip():
            die("%r: empty display name" % vid)
        try:
            p = int(row["patience_e3"])
        except ValueError:
            die("%r: patience_e3 %r is not an integer" % (vid, row["patience_e3"]))
        if not (0 <= p <= 1000):
            die("%r: patience_e3 %d out of [0, 1000]" % (vid, p))
        # ЦЕНЫ ДЕЯНИЙ (S19.2): новая механика с ценой = правка данных,
        # ноль веток. Диапазоны — узкие рамки от здравого смысла матрицы
        # (int8 в faction_relations) и репутации комнаты (int16).
        for col, lo, hi in (("rel_delta", -100, 100),
                            ("rep_delta", -1000, 1000),
                            ("turf_mult_e3", 0, 4000),
                            ("victim_mult_e3", 0, 4000),
                            ("hear_m", 0, 48)):
            try:
                val = int(row[col])
            except ValueError:
                die("%r: %s %r is not an integer" % (vid, col, row[col]))
            if not (lo <= val <= hi):
                die("%r: %s %d out of [%d, %d]" % (vid, col, val, lo, hi))

    lines = []
    w = lines.append
    w("// GENERATED by tools/gen_verb_table.py from data/verbs.csv — do not")
    w("// hand-edit. Edit the CSV and re-run the generator; the `source_rules`")
    w("// ctest fails on drift.")
    w("//")
    w("// THE VERB VOCABULARY (CANON S12.2-S12.3): the shared language of prop,")
    w("// item, room, agent and deed. K = kVerbCount comes from the CSV and is")
    w("// never a literal in code. Ids are the CSV row order, STABLE BY CONTRACT")
    w("// (saved vectors key on them): append, never insert.")
    w("//")
    w("// PATIENCE (S13.5): 0..1 stored x1000; the urgency threshold is derived")
    w("// from it, never listed. shelter 0 = tolerates nothing; wander 1000 =")
    w("// never urgent, never zero demand.")
    w("#pragma once")
    w("")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("")
    w("namespace giga::game {")
    w("")
    w("// Ordinal into every verb-indexed vector (demand, offer, declared, price).")
    w("using VerbId = std::uint8_t;")
    w("")
    for i, row in enumerate(rows):
        vid = row["id"].strip()
        note = (row["note"] or "").strip()
        comment = ("  // %s" % note) if note else ""
        w("inline constexpr VerbId kVerb%s = %d;%s" % (camel(vid), i, comment))
    w("")
    w("inline constexpr std::size_t kVerbCount = %d;" % len(rows))
    w("")
    w("// Patience x1000 (S13.5), CSV column patience_e3.")
    w("inline constexpr std::uint16_t kVerbPatienceE3[kVerbCount] = {")
    for row in rows:
        w("    %s,  // %s" % (row["patience_e3"].strip(), row["id"].strip()))
    w("};")
    w("")
    w("// ЦЕНЫ ДЕЯНИЙ (CANON S19.2) — колонки CSV, кодоген как materials.csv:")
    w("// базовая дельта матрицы фракций, дельта репутации комнаты, множитель")
    w("// своей территории (свидетель из фракции собственника), множитель")
    w("// своей жертвы (жертва из фракции свидетеля), радиус слышимости деяния")
    w("// в метрах (0 = только видимое). Уместность (комната предлагает глагол)")
    w("// зануляет цену ЦЕЛИКОМ — механика, не колонка (S19.1.3).")
    w("inline constexpr std::int8_t kVerbRelDelta[kVerbCount] = {")
    for row in rows:
        w("    %s,  // %s" % (row["rel_delta"].strip(), row["id"].strip()))
    w("};")
    w("")
    w("inline constexpr std::int16_t kVerbRepDelta[kVerbCount] = {")
    for row in rows:
        w("    %s,  // %s" % (row["rep_delta"].strip(), row["id"].strip()))
    w("};")
    w("")
    w("inline constexpr std::uint16_t kVerbTurfMultE3[kVerbCount] = {")
    for row in rows:
        w("    %s,  // %s" % (row["turf_mult_e3"].strip(), row["id"].strip()))
    w("};")
    w("")
    w("inline constexpr std::uint16_t kVerbVictimMultE3[kVerbCount] = {")
    for row in rows:
        w("    %s,  // %s" % (row["victim_mult_e3"].strip(), row["id"].strip()))
    w("};")
    w("")
    w("inline constexpr std::uint8_t kVerbHearM[kVerbCount] = {")
    for row in rows:
        w("    %s,  // %s" % (row["hear_m"].strip(), row["id"].strip()))
    w("};")
    w("")
    w("// CSV tokens — for sibling generators' column names and debug output.")
    w("inline constexpr const char* kVerbIds[kVerbCount] = {")
    for row in rows:
        w("    \"%s\"," % row["id"].strip())
    w("};")
    w("")
    w("// Display names — text for the player, never a lookup key (S13.9).")
    w("inline constexpr const char* kVerbNames[kVerbCount] = {")
    for row in rows:
        w("    \"%s\"," % row["name"].strip())
    w("};")
    w("")
    w("} // namespace giga::game")
    w("")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("gen_verb_table: wrote %s (%d verbs)" % (OUT_PATH, len(rows)))


if __name__ == "__main__":
    main()
