#!/usr/bin/env python3
"""Generate the WHOLE material vocabulary from data/materials.csv + data/textures.csv.

One CSV row per CellType is the single source of truth for everything a material
is — its id, its C++ constant name, its carve hardness, its mean albedo, which
texture set skins it and its procedural surface character. This generator emits
every artifact that used to be a hand-maintained copy of that truth:

    src/world/materials.h            kMat* id constants + kMatCount
    src/world/material_props.h       kMatHardness + material_hardness()
    src/render/material_table.h      albedo table + texture-map bindings
    shaders/material_surface.glsl    per-id surface family/sigma/pitch/chroma

Same contract as gen_item_table.py / gen_mob_table.py: the CSVs are the truth,
the generated files are committed so the build needs no Python, an unknown token
is a hard error, and the `source_rules` ctest compares the CSV row count against
the count the GLSL declares. Adding a material is ONE ROW in data/materials.csv
plus a re-run — never an edit to a C++ file.

data/textures.csv is the ASSET catalog: one row per KTX2 texture set (albedo /
normal / roughness files, tile scale, sRGB flag) plus the measured linear mean
and luminance deviation tools/measure_materials.py harvested, and the source
provenance. A material row binds to a texture by `texture_id`; when it does and
its `cv` column is blank, the surface amplitude is DERIVED from the texture's
measured statistics (lum_std / mean luminance) — the calibrated pipeline the old
gen_material_surface.py carried, folded in here so there is one generator and
one truth. See that math's rationale in shaders/material_surface.glsl's header.

    python tools/gen_material_table.py
"""

import csv
import math
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAT_CSV = os.path.join(REPO, "data", "materials.csv")
TEX_CSV = os.path.join(REPO, "data", "textures.csv")
OUT_MATERIALS_H = os.path.join(REPO, "src", "world", "materials.h")
OUT_PROPS_H = os.path.join(REPO, "src", "world", "material_props.h")
OUT_RENDER_H = os.path.join(REPO, "src", "render", "material_table.h")
OUT_GLSL = os.path.join(REPO, "shaders", "material_surface.glsl")

UNBREAKABLE = 65535

# Structure families. Must match the kFam* constants in shaders/cube.frag.
FAM = {
    "generic": 0, "plaster": 1, "plank": 2, "tile": 3, "ribbed": 4,
    "tread": 5, "rust": 6, "rubble": 7, "smooth": 8,
}

# Rec. 709 luminance, matching tools/measure_materials.py.
LUM = (0.2126, 0.7152, 0.0722)

# Phase is a LABEL for gameplay predicates (passability, buoyancy, breathing);
# matter MOVEMENT never reads it — only flow/diffusion/density (CANON S16.2).
PHASE = {"solid": 0, "liquid": 1, "gas": 2}


def die(msg):
    sys.stderr.write("gen_material_table: %s\n" % msg)
    sys.exit(1)


def fnum(row, col, i, lo=None, hi=None):
    try:
        v = float(row[col])
    except (KeyError, ValueError):
        die("row %d: bad %s %r" % (i, col, row.get(col)))
    if lo is not None and v < lo:
        die("row %d: %s %s below %s" % (i, col, v, lo))
    if hi is not None and v > hi:
        die("row %d: %s %s above %s" % (i, col, v, hi))
    return v


def elements(out, values, names):
    """One array element per line, comma BEFORE the trailing comment.

    A GLSL array constructor takes no trailing comma, and a comment placed
    before the comma swallows it. One place to get it right (C++ tolerates the
    same layout).
    """
    w = max(len(v) for v in values)
    lines = []
    for i, (v, n) in enumerate(zip(values, names)):
        sep = "," if i + 1 < len(values) else " "
        lines.append("    %-*s%s  // %2d %s" % (w, v, sep, i, n))
    return "\n".join(lines) + "\n"


def wrap_note(note, width=68):
    words, line, lines = note.split(), "", []
    for w in words:
        if line and len(line) + 1 + len(w) > width:
            lines.append(line)
            line = w
        else:
            line = w if not line else line + " " + w
    if line:
        lines.append(line)
    return lines


def gen_header(tool):
    return ("// GENERATED by tools/gen_material_table.py from data/materials.csv"
            " + data/textures.csv\n"
            "// — do not hand-edit. Edit the CSV and re-run the generator; the\n"
            "// `source_rules` ctest fails on drift.\n")


def main():
    with open(TEX_CSV, encoding="utf-8", newline="") as fh:
        texRows = list(csv.DictReader(fh))
    tex = {r["id"]: r for r in texRows}
    if len(tex) != len(texRows):
        die("duplicate id in %s" % TEX_CSV)

    with open(MAT_CSV, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        die("no rows in %s" % MAT_CSV)

    mats = []
    for i, r in enumerate(rows):
        if int(r["id"]) != i:
            die("row %d declares id %s — materials.csv must be dense and in id "
                "order (CellType IS the row index)" % (i, r["id"]))
        fam = r["family"].strip()
        if fam not in FAM:
            die("row %d (%s): unknown family %r" % (i, r["name"], fam))
        texId = r["texture_id"].strip()
        if texId and texId not in tex:
            die("row %d (%s): texture_id %r is not a row in %s"
                % (i, r["name"], texId, TEX_CSV))
        # Surface amplitude: derived from the bound texture's measured stats
        # when `cv` is blank, authored otherwise.
        cvRaw = r["cv"].strip()
        if cvRaw == "":
            if not texId:
                die("row %d (%s): blank cv needs a texture_id to derive from"
                    % (i, r["name"]))
            t = tex[texId]
            lin = [float(t["lin_r"]), float(t["lin_g"]), float(t["lin_b"])]
            mean = sum(c * w for c, w in zip(lin, LUM))
            if mean <= 0.0:
                die("row %d (%s): texture %r has non-positive mean luminance"
                    % (i, r["name"], texId))
            cv = float(t["lum_std"]) / mean
            src = texId
        else:
            cv = float(cvRaw)
            src = "authored"
        sigma = math.sqrt(math.log(1.0 + cv * cv))
        if not (0.0 <= sigma < 1.0):
            die("row %d (%s): sigma %.4f outside [0, 1)" % (i, r["name"], sigma))
        mats.append({
            "id": i, "name": r["name"], "cpp": r["cpp_name"].strip(),
            "hardness": int(r["hardness"]),
            "albedo": (fnum(r, "albedo_r", i, 0, 1), fnum(r, "albedo_g", i, 0, 1),
                       fnum(r, "albedo_b", i, 0, 1)),
            "tex": texId, "fam": fam, "cv": cv, "sigma": sigma, "src": src,
            "pitch": fnum(r, "pitch", i, 0),
            "chroma_sigma": fnum(r, "chroma_sigma", i, 0),
            "chroma_axis": (fnum(r, "chroma_r", i), fnum(r, "chroma_g", i),
                            fnum(r, "chroma_b", i)),
            "bump": fnum(r, "bump_scale", i, 0),
            "density": fnum(r, "density_kg_m3", i, 0),
            "emissive_e3": int(fnum(r, "emissive_e3", i, 0, 4000)),
            "light_radius_mm": int(fnum(r, "light_radius_mm", i, 0, 65535)),
            "light_intensity_e3": int(fnum(r, "light_intensity_e3", i, 0, 65535)),
            "phase": r["phase"].strip(),
            "flow": fnum(r, "flow", i, 0, 1),
            "diffusion": fnum(r, "diffusion", i, 0, 1),
            "light_transparent": int(fnum(r, "light_transparent", i, 0, 1)),
            "note": r["note"],
        })
        if (mats[-1]["light_radius_mm"] == 0) != (mats[-1]["light_intensity_e3"] == 0):
            die("row %d (%s): light_radius_mm and light_intensity_e3 must be "
                "both zero or both set" % (i, r["name"]))
        # ПРОЗРАЧНОСТЬ ДЛЯ СВЕТА (решение владельца 2026-08-24, neon-topology):
        # колонка light_transparent руками ставится только стеклу; воздух и
        # эмиттеры прозрачны ПО ПОСТРОЕНИЮ (эмиттер не преграда своему свету,
        # воздух не преграда ничему) — их значение ВЫВОДИТСЯ, не назначается.
        mats[-1]["light_pass"] = 1 if (i == 0 or
                                       mats[-1]["light_radius_mm"] != 0 or
                                       mats[-1]["light_transparent"]) else 0
        # Label and parameters must not be able to disagree (CANON S16.2): the
        # gameplay label promises behaviour the movement parameters deliver.
        m = mats[-1]
        if m["phase"] not in PHASE:
            die("row %d (%s): unknown phase %r (solid/liquid/gas)"
                % (i, r["name"], m["phase"]))
        if i == 0 and m["phase"] != "gas":
            die("row 0 (air) must be phase=gas — it IS the default medium")
        if m["phase"] == "liquid" and m["flow"] <= 0.0:
            die("row %d (%s): a liquid that cannot flow — label/params disagree"
                % (i, r["name"]))
        if m["phase"] == "gas" and m["diffusion"] <= 0.0:
            die("row %d (%s): a gas that cannot diffuse — label/params disagree"
                % (i, r["name"]))
    # --- РЫХЛЫЕ ДВОЙНИКИ СТРОК (решение владельца 2026-08-24; эстафета
    # п.15: «rubble_* на исходный материал, никаких флажков»). Каждой
    # РУШИМОЙ твёрдой строке (solid, бьётся, flow==0) порождается двойник
    # rubble_<имя>: отвязанный детачем кусок меняет строку и падает
    # автоматом, ВЫГЛЯДЯ исходником — альбедо чуть темнее (0.85, читаемость
    # обвала), текстура/зерно наследуются. Всё выведено: плотность насыпная
    # 0.75x (упаковка случайной засыпки), flow 0.1 (угол откоса ~40°, как у
    # строки rubble), твёрдость /8 (дробить дроблёное легче), света нет
    # (обломок неона не запитан), прозрачности нет (щебень стекла не лист).
    # Двойники — ВЫВЕДЕННЫЕ данные, в CSV НЕ пишутся: kMaterialCsvRows
    # остаётся счётом CSV (гейт Rule 7), kMatCount покрывает всех; сейвы
    # хранят id — двойники аппендятся ПОСЛЕ CSV-строк, порядок стабилен.
    csvN = len(mats)
    rubbleOf = {m["id"]: m["id"] for m in mats}  # дефолт: сам себя
    derived = []
    for m in list(mats):
        if (m["phase"] != "solid" or m["hardness"] >= 65535 or
                m["flow"] > 0.0 or m["id"] == 0):
            continue
        d = dict(m)
        d["id"] = csvN + len(derived)
        d["name"] = "rubble_" + m["name"]
        d["cpp"] = ("Rubble" + m["cpp"]) if m["cpp"] else ""
        d["hardness"] = max(8, m["hardness"] // 8)
        d["albedo"] = tuple(a * 0.85 for a in m["albedo"])
        d["density"] = m["density"] * 0.75
        d["flow"] = 0.1
        d["diffusion"] = 0.0
        d["emissive_e3"] = 0
        d["light_radius_mm"] = 0
        d["light_intensity_e3"] = 0
        d["light_transparent"] = 0
        d["light_pass"] = 0
        d["note"] = ("ВЫВЕДЕННЫЙ рыхлый двойник строки %s — детач меняет "
                     "строку, автомат роняет; вид исходника" % m["name"])
        rubbleOf[m["id"]] = d["id"]
        derived.append(d)
    for d in derived:
        rubbleOf[d["id"]] = d["id"]  # двойник двойника — сам он
    mats.extend(derived)

    n = len(mats)
    names = [m["name"] for m in mats]

    cpps = [m["cpp"] for m in mats if m["cpp"]]
    if len(set(cpps)) != len(cpps):
        die("duplicate cpp_name")

    # --- src/world/materials.h ---------------------------------------------
    with open(OUT_MATERIALS_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(gen_header("materials"))
        fh.write("""//
// Cell material ids — the shared vocabulary between the generators that WRITE
// cells and the render pass that gives them a colour. `CellType` is an opaque
// uint16 to the engine ([voxels.md]); these constants are the game's meanings
// for it. They live in world/ because the render pass needs them and render
// must never include game/ ([ARCHITECTURE.md] layering). A material id is a
// LABEL: the only tables keyed on it are generated siblings of this file.
//
// Ids are the CSV row order and STABLE BY CONTRACT: geometry in saves stores
// CellType verbatim, so a new material is appended, never inserted.
#pragma once

#include "world/macro_grid.h"  // CellType, kCellAir

namespace giga {

""")
        for m in mats:
            if not m["cpp"]:
                continue
            fh.write("inline constexpr CellType kMat%s = %d;%s// %s\n"
                     % (m["cpp"], m["id"], " " * max(1, 15 - len(m["cpp"])),
                        m["note"][:72]))
        fh.write("""
// One past the last id in use. Every generated sibling table is sized from the
// same CSV, so a row added without regenerating fails the source_rules gate
// rather than rendering as an unremarkable default.
inline constexpr CellType kMatCount = %d;

// CSV-имена строк по id — словарь команд и логов (консоль `sphere <имя>`
// говорит на языке таблицы, не констант). Указатели на литералы, без аллокаций.
inline constexpr const char* kMatNames[kMatCount] = {
%s};

// id по CSV-имени (линейный скан таблицы — она мала, зов из консоли).
// kMatCount = «нет такого материала».
inline CellType material_id_by_name(const char* name) {
    for (CellType i = 0; i < kMatCount; ++i) {
        const char* a = kMatNames[i];
        const char* b = name;
        while (*a && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0) return i;
    }
    return kMatCount;
}

} // namespace giga
""" % (n, elements(mats, ['"%s"' % m["name"] for m in mats], names)))

    # --- src/world/material_props.h ----------------------------------------
    with open(OUT_PROPS_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(gen_header("props"))
        fh.write("""//
// Physical material properties — the SIMULATION side of the vocabulary.
// Hardness is the integer resistance a hit's `power` is rolled against
// ([destruct.h]): power == hardness removes the sub-voxel with certainty,
// power == hardness/2 with probability 1/2, and so on. 0 = removed by any
// touch; kHardnessUnbreakable = infrastructure protected as DATA (doors carry
// their own HP machine, the hub/extract pads are the nav lattice's ground
// truth) — rows, not special cases in the carve loop.
#pragma once
#include <cstdint>

#include "world/materials.h"

namespace giga {

inline constexpr std::uint16_t kHardnessUnbreakable = 0xFFFF;

// Indexed by CellType. Scale anchored on concrete = 256 ([jirnyak.md] §1).
inline constexpr std::uint16_t kMatHardness[kMatCount] = {
""")
        vals = [("kHardnessUnbreakable" if m["hardness"] == UNBREAKABLE
                 else "%d" % m["hardness"]) for m in mats]
        fh.write(elements(mats, vals, names))
        fh.write("""};

static_assert(sizeof(kMatHardness) / sizeof(kMatHardness[0]) == kMatCount,
              "every material needs a hardness row");

inline std::uint16_t material_hardness(CellType t) {
    return t < kMatCount ? kMatHardness[t] : kHardnessUnbreakable;
}

// Density in kg/m^3 — THE universal mass context ([jirnyak, 2026-08-02]): the
// mass of one sub-voxel is density * (0.25 m)^3, so debris, a falling chunk and
// a carve's ejecta all weigh what their material says with no per-thing
// authoring. Every impact law in the game is E = m v^2 / 2 and p = m v over
// masses that ultimately come from here or from a table's mass column.
inline constexpr float kMatDensity[kMatCount] = {
""")
        vals = ["%.1ff" % m["density"] for m in mats]
        fh.write(elements(mats, vals, names))
        fh.write("""};

// Mass of ONE sub-voxel (0.25 m cube) of this material, in kg.
inline constexpr float kSubVoxelVolumeM3 = 0.25f * 0.25f * 0.25f;
inline float material_subvoxel_mass_kg(CellType t) {
    return (t < kMatCount ? kMatDensity[t] : 0.0f) * kSubVoxelVolumeM3;
}

// СРЕДЫ (CANON S16, мир-автомат). Движение материи читает ТОЛЬКО параметры:
//   flow      — доля, перетекающая вбок за подтик автомата: 0 = твёрдое
//               (лежит; падает, когда опоры нет — это и есть обломки),
//               1 = вода (референс: вязкость 1 мПа·с; прочие жидкости =
//               вязкость_воды/вязкость — вывод в note строки CSV);
//   diffusion — расползание без гравитации (газы); 1 = воздух (референс:
//               выравнивается за один подтик).
// phase — МЕТКА для геймплейных предикатов (проходимость, плавучесть,
// дыхание); физика движения её НЕ читает и ветки по ней не имеет (S16.2).
// Метка и параметры не могут разойтись — генератор это гейтит (жидкость
// обязана течь, газ обязан диффундировать; воздух обязан быть газом).
enum class MatPhase : std::uint8_t { Solid = 0, Liquid = 1, Gas = 2 };

inline constexpr std::uint8_t kMatPhase[kMatCount] = {
%(phase)s};

inline constexpr float kMatFlow[kMatCount] = {
%(flow)s};

inline constexpr float kMatDiffusion[kMatCount] = {
%(diffusion)s};

inline MatPhase material_phase(CellType t) {
    return t < kMatCount ? static_cast<MatPhase>(kMatPhase[t]) : MatPhase::Solid;
}

// «Материя сред» — строка даёт движение (flow или diffusion > 0) и это не
// воздух. ЕДИНСТВЕННАЯ выписка закона: класс-байт 3 зеркала
// (render/voxel_mirror.cpp), агностичный карв (world/destruct.cpp) и
// GPU-двойник (shaders/medium_sim.comp, mobile()) обязаны совпадать с ней.
inline bool material_is_medium(CellType t) {
    return t != 0 && t < kMatCount &&
           (kMatFlow[t] > 0.0f || kMatDiffusion[t] > 0.0f);
}

// РЫХЛЫЙ ДВОЙНИК строки (решение владельца 2026-08-24): детач меняет строку
// куска на двойника — тот выглядит исходником (альбедо/текстура
// наследуются) и падает автоматом. Не-рушимое и среды — сами себя.
inline constexpr CellType kMatRubbleOf[kMatCount] = {
%(rubble_of)s};

inline CellType material_rubble_of(CellType t) {
    return t < kMatCount ? kMatRubbleOf[t] : t;
}

// СВЕТОМАТЕРИАЛЫ ([ddalight.md]): light_radius_mm != 0 — ячейки этого
// материала излучают; бейк этажа кластеризует их в статические эмиттеры
// (game/light_bake.h). Цвет источника = альбедо материала: нарисованный
// неон светит тем цветом, каким покрашен. Единицы — мм и x1000, как в
// data/props.csv (одна величина = одна единица во всех таблицах).
inline constexpr std::uint16_t kMatLightRadiusMm[kMatCount] = {
%(light_radius)s};

inline constexpr std::uint16_t kMatLightIntensityE3[kMatCount] = {
%(light_intensity)s};

// Linear albedo per id — the light colour source for emitters (and the same
// numbers render/material_table.h carries for shading).
inline constexpr float kMatAlbedoR[kMatCount] = {
%(albedo_r)s};
inline constexpr float kMatAlbedoG[kMatCount] = {
%(albedo_g)s};
inline constexpr float kMatAlbedoB[kMatCount] = {
%(albedo_b)s};

inline bool material_emits_light(CellType t) {
    return t < kMatCount && kMatLightRadiusMm[t] != 0 && kMatLightIntensityE3[t] != 0;
}

// ПРОЗРАЧНОСТЬ ДЛЯ СВЕТА (data/materials.csv light_transparent; решение
// владельца 2026-08-24, neon-topology): теневой луч и бейк видимости прощают
// субвоксель, если его материал ПРОЗРАЧЕН — а не если светится. Воздух и
// эмиттеры прозрачны по построению (выведено кодогеном); стекло — строкой
// CSV: свет проходит, материя стоит. Оба места одного закона читают эту
// колонку: shaders/raymarch.frag shadow_cell_occluded (kMatLightPass) и
// game/light_vis_bake.cpp light_ray_passes (material_passes_light).
inline constexpr std::uint8_t kMatLightPass[kMatCount] = {
%(light_pass)s};

inline bool material_passes_light(CellType t) {
    return t < kMatCount && kMatLightPass[t] != 0;
}

} // namespace giga
""" % {
            "phase": elements(mats, ["%d" % PHASE[m["phase"]] for m in mats], names),
            "flow": elements(mats, ["%.3ff" % m["flow"] for m in mats], names),
            "diffusion": elements(mats, ["%.3ff" % m["diffusion"] for m in mats], names),
            "light_radius": elements(mats, ["%d" % m["light_radius_mm"] for m in mats], names),
            "light_intensity": elements(mats, ["%d" % m["light_intensity_e3"] for m in mats], names),
            "light_pass": elements(mats, ["%d" % m["light_pass"] for m in mats], names),
            "albedo_r": elements(mats, ["%.3ff" % m["albedo"][0] for m in mats], names),
            "albedo_g": elements(mats, ["%.3ff" % m["albedo"][1] for m in mats], names),
            "albedo_b": elements(mats, ["%.3ff" % m["albedo"][2] for m in mats], names),
            "rubble_of": elements(mats, ["%d" % rubbleOf[m["id"]] for m in mats], names),
        })

    # --- src/render/material_table.h ---------------------------------------
    textured = [m for m in mats if m["tex"]]
    with open(OUT_RENDER_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(gen_header("render"))
        fh.write("""//
// The RENDER side of the material vocabulary: mean albedo per id (display-
// referred — the shading linearises once with pow(2.2)), and which KTX2 texture
// set skins an id. Albedos bound to a texture are MEASURED off the real
// photograph (data/textures.csv carries the linear mean and provenance);
// unbound rows are authored. Consumed by render/cube_pass.cpp only.
#pragma once

#include "core/math.h"
#include "world/materials.h"

namespace giga {

inline constexpr vec3 kMaterial[kMatCount] = {
""")
        vals = ["{%.2ff, %.2ff, %.2ff}" % m["albedo"] for m in mats]
        fh.write(elements(mats, vals, names))
        fh.write("""};
static_assert(sizeof(kMaterial) / sizeof(kMaterial[0]) == kMatCount,
              "one albedo row per material id");

// Texture bindings: ids skinned by a KTX2 set. File names are the asset
// catalog's (data/textures.csv), joined onto the texture directory by the pass.
struct MaterialMap {
    CellType id;
    const char* albedo;     // never null for a row in this table
    const char* normal;     // "" when the set carries no normal map
    const char* roughness;  // "" when the set carries no roughness map
    float tileScale;        // world-space tiling multiplier
};
inline constexpr MaterialMap kMaterialMaps[] = {
""")
        tvals = []
        for m in textured:
            t = tex[m["tex"]]
            tvals.append("{kMat%s, \"%s\", \"%s\", \"%s\", %sf}"
                         % (m["cpp"], t["albedo_file"], t["normal_file"],
                            t["roughness_file"], t["tile_scale"]))
        fh.write(elements(textured, tvals, [m["name"] for m in textured]))
        fh.write("""};
inline constexpr int kMaterialMapCount =
    static_cast<int>(sizeof(kMaterialMaps) / sizeof(kMaterialMaps[0]));

} // namespace giga
""")

    # --- shaders/material_surface.glsl --------------------------------------
    measured = sum(1 for m in mats if m["src"] != "authored")
    with open(OUT_GLSL, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("""// GENERATED by tools/gen_material_table.py from data/materials.csv — do not
// hand-edit. Edit the CSV and re-run it; the `source_rules` ctest fails on drift.
//
// Included by shaders/cube.frag, which is shared by the world pass and the body
// pass. Nothing on the CPU reads this table.
//
// sigma is the lognormal width that reproduces each material's MEASURED luminance
// coefficient of variation (lum_std / mean luminance, both linear) through
// exp(sigma*n - sigma*sigma/2) — strictly positive, mean-preserving, and calibrated
// rather than tuned. Amplitudes derive from data/textures.csv's measured stats when
// a material binds a texture and leaves `cv` blank; the seam/groove DEPTHS are
// authored per family in cube.frag (the CSV measured colour, not depth).

// Rows read from data/materials.csv. The `source_rules` ctest compares it
// against the CSV's data-row count; derived rubble twins live PAST this count
// (kMatCount covers all, see materials.h).
const uint kMaterialCsvRows = %du;

""" % csvN)
        fh.write("// Family per material id — see the kFam* constants in cube.frag.\n")
        for m in mats:
            fh.write("//  %2d %-20s %-8s %-24s CV %.4f\n"
                     % (m["id"], m["name"], m["fam"], m["src"], m["cv"]))
            for line in wrap_note(m["note"]):
                fh.write("//     %s\n" % line)
        fh.write("// Table length. cube.frag clamps the incoming material id against\n"
                 "// this, so an id the CPU should never emit cannot index past the\n"
                 "// arrays — an out-of-range const-array read is undefined in GLSL.\n")
        fh.write("const uint kMatSurfaceCount = %du;\n\n" % n)

        fh.write("const uint kMatFamily[%d] = uint[%d](\n" % (n, n))
        fh.write(elements(mats, ["%du" % FAM[m["fam"]] for m in mats], names))
        fh.write(");\n\n")

        fh.write("// x = lognormal sigma reproducing measured luminance CV,\n"
                 "// y = structural pitch in cycles per 2 m cell,\n"
                 "// z = chroma_sigma (lognormal chroma width),\n"
                 "// w = bump_scale (normal perturbation scale).\n")
        fh.write("const vec4 kMatSurface[%d] = vec4[%d](\n" % (n, n))
        fh.write(elements(mats,
                          ["vec4(%.5f, %6.2f, %.5f, %.5f)"
                           % (m["sigma"], m["pitch"], m["chroma_sigma"], m["bump"])
                           for m in mats], names))
        fh.write(");\n\n")

        fh.write("// RGB chroma tint axis per material id.\n")
        fh.write("const vec3 kMatChromaAxis[%d] = vec3[%d](\n" % (n, n))
        fh.write(elements(mats,
                          ["vec3(%.5f, %.5f, %.5f)" % m["chroma_axis"]
                           for m in mats], names))
        fh.write(");\n\n")

        fh.write("// Самосвечение поверхности (albedo * kMatEmissive): нарисованный\n"
                 "// светоматериал читается источником даже в полной тьме; сам СВЕТ\n"
                 "// от него в сетку кладёт бейк этажа ([ddalight.md]).\n")
        fh.write("const float kMatEmissive[%d] = float[%d](\n" % (n, n))
        fh.write(elements(mats,
                          ["%.3f" % (m["emissive_e3"] * 0.001) for m in mats],
                          names))
        fh.write(");\n\n")

        fh.write("// ПРОЗРАЧНОСТЬ ДЛЯ СВЕТА (light_transparent + выведенные\n"
                 "// воздух/эмиттеры): теневой луч прощает субвоксель\n"
                 "// прозрачного материала. Тот же закон на CPU —\n"
                 "// material_passes_light ([world/material_props.h]).\n")
        fh.write("const uint kMatLightPass[%d] = uint[%d](\n" % (n, n))
        fh.write(elements(mats, ["%du" % m["light_pass"] for m in mats], names))
        fh.write(");\n\n")

        # ИСТАИВАНИЕ ОДИНОЧЕК (закон владельца 2026-08-25): подвижный атом
        # без единого атома своего материала в блоке Марголуса тает роллом.
        # Шанс обратен МАССЕ кванта (вывод, не назначение): масса = плотность
        # × объём субвокселя 0.25³; калибровка — одинокий квант газа
        # (3 кг/м³, 47 г) живёт ~секунду = 31.25 подтика (125 Гц / 4).
        # p = C/масса, C = 47 г / 31.25 = 1.5 г  =>  p = 0.09375/плотность.
        # Воздух (материал 0) — вытесняемая пустота, не истаивает.
        kSubVolume = 0.25 ** 3
        kGasRefDensity = 3.0
        kLoneGasLifeSubsteps = 125.0 / 4.0
        loneC = kGasRefDensity * kSubVolume / kLoneGasLifeSubsteps
        def lone_fade(i, m):
            mobile = m["flow"] > 0.0 or m["diffusion"] > 0.0
            if i == 0 or not mobile or m["density"] <= 0.0:
                return 0.0
            return loneC / (m["density"] * kSubVolume)
        fh.write("// СРЕДЫ (CANON S16): x = flow (0 = твёрдое, 1 = вода),\n"
                 "// y = diffusion (газы; 1 = воздух), z = шанс истаивания\n"
                 "// ОДИНОЧКИ на подтик (закон 2026-08-25: атом без своего\n"
                 "// материала в блоке — брызг, тает; шанс обратен массе\n"
                 "// кванта, калибровка — одиночный квант газа живёт ~1 с).\n"
                 "// Читатель — автомат материи; движение НЕ читает kMatPhase\n"
                 "// (метка для геймплейных предикатов — S16.2).\n")
        fh.write("const vec3 kMatMedium[%d] = vec3[%d](\n" % (n, n))
        fh.write(elements(mats,
                          ["vec3(%.3f, %.3f, %.6f)" %
                           (m["flow"], m["diffusion"], lone_fade(i, m))
                           for i, m in enumerate(mats)], names))
        fh.write(");\n\n")
        fh.write("const uint kMatPhase[%d] = uint[%d](\n" % (n, n))
        fh.write(elements(mats, ["%du" % PHASE[m["phase"]] for m in mats], names))
        fh.write(");\n\n")

        fh.write("// Плотность кг/м³ — третий параметр движения материи\n"
                 "// (CANON S16.2: тяжелее — тонет, легче — всплывает).\n"
                 "// Зеркало kMatDensity [world/material_props.h].\n")
        fh.write("const float kMatDensity[%d] = float[%d](\n" % (n, n))
        fh.write(elements(mats,
                          ["%.1f" % m["density"] for m in mats], names))
        fh.write(");\n")

    sys.stderr.write(
        "gen_material_table: %d materials (%d measured, %d authored), "
        "%d textured, %d texture assets -> materials.h, material_props.h, "
        "material_table.h, material_surface.glsl\n"
        % (n, measured, n - measured, len(textured), len(texRows)))


if __name__ == "__main__":
    main()
