#!/usr/bin/env python3
"""Generate src/game/weapon_table.cpp from data/weapons_melee.csv.

Third sibling of gen_mob_table.py / gen_item_table.py, same contract: data is the
truth, the generated .cpp is committed so the build needs no Python, and an unknown
token is a hard error rather than a silent default.

    python tools/gen_weapon_table.py

Only MELEE weapons are ported. The reference has 71 weapon stat rows, 48 of them
ranged — those need projectiles, ammo pools, magazines, spread and reload, none of
which exist yet, and porting the numbers without the systems would be a table
nothing reads. The 23 melee rows have a live consumer today: the player's swing.

The linkage is by ITEM ID: 22 of the 23 keys in the reference's PHYS_WEAPON_STATS
are also ids in data/items.csv. The 23rd is the empty-string key — fists, which are
correctly not an item. That is verified here, so a renamed item cannot silently
orphan a weapon's stats.
"""

import csv
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MELEE_CSV = os.path.join(REPO, "data", "weapons_melee.csv")
ITEMS_CSV = os.path.join(REPO, "data", "items.csv")
OUT_PATH = os.path.join(REPO, "src", "game", "weapon_table.cpp")

EXPECTED_ROWS = 22        # 21 item-backed + fists
EXPECTED_ITEM_ROWS = 443  # must agree with kItemCount


def die(msg):
    sys.stderr.write("gen_weapon_table: %s\n" % msg)
    sys.exit(1)


def fixed(row, col, scale, lo, hi):
    text = (row.get(col) or "").strip()
    v = 0 if not text else int(round(float(text) * scale))
    if not (lo <= v <= hi):
        die("%r: %s = %r -> %d out of [%d, %d]"
            % (row["item_id"], col, text, v, lo, hi))
    return v


def main():
    with open(MELEE_CSV, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    with open(ITEMS_CSV, encoding="utf-8", newline="") as fh:
        items = [r["id"] for r in csv.DictReader(fh)]

    if len(rows) != EXPECTED_ROWS:
        die("expected %d melee rows, got %d — update EXPECTED_ROWS here AND "
            "kMeleeCount in weapon_table.h" % (EXPECTED_ROWS, len(rows)))
    if len(items) != EXPECTED_ITEM_ROWS:
        die("items.csv has %d rows, expected %d — the item table moved; the "
            "kMeleeByItem index width depends on it" % (len(items), EXPECTED_ITEM_ROWS))

    # item id -> 1-based ItemId, matching item_table.h's convention.
    item_index = {name: i + 1 for i, name in enumerate(items)}

    fists = [r for r in rows if not r["item_id"].strip()]
    if len(fists) != 1:
        die("expected exactly one unarmed row (empty item_id), found %d" % len(fists))
    if rows[0] is not fists[0]:
        die("the unarmed row must be first so index 0 is the fists fallback")

    # Sparse index: 0 means "this item is not a melee weapon", which is why the
    # unarmed row has to sit at index 0 and be reachable only as a fallback.
    by_item = [0] * (EXPECTED_ITEM_ROWS + 1)
    out = []
    for i, r in enumerate(rows):
        name = r["item_id"].strip()
        if name:
            if name not in item_index:
                die("melee weapon %r has no matching id in items.csv — a rename "
                    "orphaned its stats" % name)
            iid = item_index[name]
            if by_item[iid]:
                die("item %r already mapped to melee index %d" % (name, by_item[iid]))
            by_item[iid] = i

        out.append(
            "    // [%d] %s\n"
            "    MeleeDef{ %d, %d, %d, %d, %d, %d }," % (
                i, name if name else "(unarmed)",
                fixed(r, "dmg", 1, 1, 4000),
                fixed(r, "range_cells", 1000, 100, 4000),
                fixed(r, "cooldown_s", 1000, 50, 10000),
                fixed(r, "durability", 1, 0, 65535),
                fixed(r, "knockback", 1000, 0, 65535),
                fixed(r, "hit_radius", 1000, 0, 65535)))

    mapped = sum(1 for v in by_item if v)
    if mapped != EXPECTED_ROWS - 1:
        die("mapped %d items but expected %d" % (mapped, EXPECTED_ROWS - 1))

    idx = []
    for i in range(0, len(by_item), 24):
        idx.append("    " + ", ".join(str(v) for v in by_item[i:i + 24]) + ",")

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER)
        fh.write("const std::array<MeleeDef, kMeleeCount> kMeleeTable = {{\n")
        fh.write("\n".join(out))
        fh.write("\n}};\n\n")
        fh.write("// Index by ItemId; 0 means the item is not a melee weapon.\n")
        fh.write("const std::array<std::uint8_t, kItemCount + 1> kMeleeByItem = {{\n")
        fh.write("\n".join(idx))
        fh.write("\n}};\n\n")
        fh.write(FOOTER)

    sys.stderr.write("gen_weapon_table: wrote %d melee rows, %d item links, to %s\n"
                     % (len(rows), mapped, OUT_PATH))


HEADER = """// GENERATED by tools/gen_weapon_table.py from data/weapons_melee.csv — do not
// hand-edit. Edit the CSV and re-run the generator; see [items.md].
#include "game/weapon_table.h"

namespace giga::game {

"""

FOOTER = """} // namespace giga::game
"""

if __name__ == "__main__":
    main()
