#!/usr/bin/env python3
"""Generate src/game/interact_table.h from data/interactables.csv.

The INTERACTABLES table (owner's design, 2026-08-02): attaching an interactive
to a prop/feature is one system (the placement seeders), and the interactive
itself is a self-sufficient row here — its prompt, its reach, and (as the epic
grows) its gate and the EventBus event it publishes. A new interactive is a new
ROW, never a new enum branch: the enum below is GENERATED from the CSV, so the
row IS the identity and the `source_rules` ctest pins the count.

Row order is ABI: PropDef.interactKind stores the ordinal, so rows are appended,
never reordered — same law as materials.csv ids.

    python tools/gen_interact_table.py
"""
import csv
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(REPO, "data", "interactables.csv")
OUT_PATH = os.path.join(REPO, "src", "game", "interact_table.h")


def die(msg):
    sys.stderr.write("gen_interact_table: %s\n" % msg)
    sys.exit(1)


def main():
    with open(CSV_PATH, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        die("no rows")
    names = [r["cpp_name"].strip() for r in rows]
    if len(set(names)) != len(names):
        die("duplicate cpp_name")

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("""// GENERATED by tools/gen_interact_table.py from data/interactables.csv — do
// not hand-edit. Edit the CSV and re-run the generator; the `source_rules`
// ctest fails on drift.
//
// One row per INTERACTIVE — a self-sufficient mechanic module: what it says
// ([E] prompt), how close a body must stand, and (as the epic grows) what it
// gates on and which EventBus event it publishes. Attachment is a different
// system (the placement seeders + props.csv's interact column); this table is
// the interactive ITSELF, so app code keys on rows and never hardcodes a
// prompt string or a reach literal again.
#pragma once

#include <cstdint>

namespace giga::game {

// Row ordinals — GENERATED, in CSV order (append-only: PropDef.interactKind
// stores this ordinal).
enum class InteractKind : std::uint8_t {
""")
        for i, n in enumerate(names):
            fh.write("    %s = %d,\n" % (n, i))
        fh.write("""    Count
};

inline constexpr std::uint8_t kInteractCount = %du;

struct InteractDef {
    const char* id;      // CSV slug
    const char* prompt;  // the [E] hint text
    float reachM;        // interaction reach, metres
};

inline constexpr InteractDef kInteractTable[kInteractCount] = {
""" % len(rows))
        for r in rows:
            fh.write("    {\"%s\", \"%s\", %sf},\n"
                     % (r["id"].strip(), r["prompt"].strip(),
                        r["reach_m"].strip()))
        fh.write("""};

inline const InteractDef& interact_def(InteractKind k) {
    const std::uint8_t i = static_cast<std::uint8_t>(k);
    return kInteractTable[i < kInteractCount ? i : 0];
}

} // namespace giga::game
""")
    sys.stderr.write("gen_interact_table: wrote %d rows to %s\n"
                     % (len(rows), OUT_PATH))


if __name__ == "__main__":
    main()
