#!/usr/bin/env python3
"""Generate src/game/particle_table.h from data/particles.csv.

The UNIFIED PARTICLE POOL's type vocabulary (owner's design, 2026-08-03):
NPC blood, pipe drips, concrete dust and bullet sparks differ by a CSV ROW,
never by code — one GPU pool simulates them all (render/particle_pass.h), and
every writer (carve, apply_damage, projectile hit, a severed pipe) names a
row here. `color_mode=material` means the writer supplies a material id and
the app resolves the albedo from the generated kMaterial table; `fixed` rows
carry their own colour.

Row order is ABI the same way interactables.csv is: ParticleBurst stores the
ordinal, so rows are appended, never reordered.

    python tools/gen_particle_table.py
"""
import csv
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(REPO, "data", "particles.csv")
OUT_PATH = os.path.join(REPO, "src", "game", "particle_table.h")


def die(msg):
    sys.stderr.write("gen_particle_table: %s\n" % msg)
    sys.exit(1)


def main():
    with open(CSV_PATH, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        die("no rows")
    names = [r["cpp_name"].strip() for r in rows]
    if len(set(names)) != len(names):
        die("duplicate cpp_name")
    for r in rows:
        if r["color_mode"].strip() not in ("fixed", "material"):
            die("row %s: color_mode must be fixed|material" % r["id"])

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("""// GENERATED by tools/gen_particle_table.py from data/particles.csv — do not
// hand-edit. Edit the CSV and re-run the generator; the `source_rules` ctest
// fails on drift.
//
// One row per PARTICLE TYPE of the unified GPU pool: mob blood and concrete
// dust differ by a row, never by code. The physics knobs (gravity multiplier,
// per-tick drag, restitution) are stamped onto each particle at spawn, so the
// compute sim (shaders/particle_sim.comp) needs no table of its own and can
// never drift from this one. `colorFromMaterial` rows take their tint from the
// generated kMaterial albedo of whatever was hit; the rest carry their own.
#pragma once

#include <cstdint>

namespace giga::game {

// Row ordinals — GENERATED, in CSV order (append-only: ParticleBurst stores
// this ordinal).
enum class ParticleKind : std::uint8_t {
""")
        for i, n in enumerate(names):
            fh.write("    %s = %d,\n" % (n, i))
        fh.write("""    Count
};

inline constexpr std::uint8_t kParticleKindCount = %du;

struct ParticleDef {
    const char* id;         // CSV slug
    bool colorFromMaterial; // tint = kMaterial[matId] instead of r/g/b
    float r, g, b;          // fixed tint (ignored when colorFromMaterial)
    std::uint8_t emissive;  // 0..255, glows through fog like prop emissives
    float gravityMul;       // x world gravity (dust floats, debris drops)
    float drag;             // velocity retained per 60 Hz step (pow'd by dt)
    float bounce;           // restitution; 0 = the hit kills the particle
    float sizeM;            // billboard edge, metres
    float lifeS;            // seconds from spawn to gone
    float speedMps;         // writers' base burst speed
};

inline constexpr ParticleDef kParticleTable[kParticleKindCount] = {
""" % len(rows))
        for r in rows:
            fh.write("    {\"%s\", %s, %sf, %sf, %sf, %s, %sf, %sf, %sf, %sf, %sf, %sf},\n"
                     % (r["id"].strip(),
                        "true" if r["color_mode"].strip() == "material" else "false",
                        r["color_r"].strip(), r["color_g"].strip(),
                        r["color_b"].strip(), r["emissive"].strip(),
                        r["gravity_mul"].strip(), r["drag"].strip(),
                        r["bounce"].strip(), r["size_m"].strip(),
                        r["life_s"].strip(), r["speed_mps"].strip()))
        fh.write("""};

inline const ParticleDef& particle_def(ParticleKind k) {
    const std::uint8_t i = static_cast<std::uint8_t>(k);
    return kParticleTable[i < kParticleKindCount ? i : 0];
}

} // namespace giga::game
""")
    sys.stderr.write("gen_particle_table: wrote %d rows to %s\n"
                     % (len(rows), OUT_PATH))


if __name__ == "__main__":
    main()
